DROP SCHEMA IF EXISTS test_160 CASCADE;
CREATE SCHEMA test_160;
SET search_path TO test_160;

CREATE SEQUENCE custom_seq START WITH 100 INCREMENT BY 5;

CREATE TABLE seq_test (
    id integer PRIMARY KEY DEFAULT nextval('custom_seq'),
    name text NOT NULL
);

CREATE TABLE identity_test (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL
);

INSERT INTO seq_test(name) VALUES ('a'), ('b');

-- begin-expected
-- columns: nextv
-- row: 110
-- end-expected
SELECT nextval('custom_seq') AS nextv;

SELECT setval('custom_seq', 200, true);

INSERT INTO seq_test(name) VALUES ('c');

INSERT INTO identity_test(name) VALUES ('x'), ('y');
INSERT INTO identity_test(id, name) VALUES (10, 'z');

-- begin-expected
-- columns: id|name
-- row: 100|a
-- row: 105|b
-- row: 205|c
-- end-expected
SELECT id, name
FROM seq_test
ORDER BY id;

-- begin-expected
-- columns: id|name
-- row: 1|x
-- row: 2|y
-- row: 10|z
-- end-expected
SELECT id, name
FROM identity_test
ORDER BY id;

DROP SCHEMA test_160 CASCADE;
