DROP SCHEMA IF EXISTS test_210 CASCADE;
CREATE SCHEMA test_210;
SET search_path TO test_210;

CREATE TABLE line_items (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    qty integer NOT NULL DEFAULT 1,
    unit_price numeric(10,2) NOT NULL DEFAULT 0.00,
    note text DEFAULT 'none',
    total_price numeric(10,2) GENERATED ALWAYS AS (qty * unit_price) STORED
);

INSERT INTO line_items(qty, unit_price, note) VALUES
    (2, 3.50, 'first'),
    (DEFAULT, 9.99, DEFAULT);

-- begin-expected
-- columns: id|qty|unit_price|note|total_price
-- row: 1|2|3.50|first|7.00
-- row: 2|1|9.99|none|9.99
-- end-expected
SELECT id, qty, unit_price, note, total_price
FROM line_items
ORDER BY id;

-- begin-expected-error
-- message-like: cannot insert a non-DEFAULT value into column "total_price"
-- end-expected-error
INSERT INTO line_items(id, qty, unit_price, total_price)
VALUES (10, 1, 1.00, 1.00);

DROP SCHEMA test_210 CASCADE;
