-- source: investigation-2026-08.md
-- finding: 145
-- title: The identity-column option parser returns a two-element long[] of {START, INCREMENT}; MINVALUE, MAXVALUE, CACHE and CYCLE are consumed and thrown away, SEQUENCE
-- begin-expected
-- ok: 0
-- end-expected
CREATE TABLE zz_t (i int GENERATED ALWAYS AS IDENTITY (MINVALUE 1 MAXVALUE 2 CYCLE), j int);
-- begin-expected
-- ok: 3
-- end-expected
INSERT INTO zz_t (j) VALUES (1),(2),(3);
-- begin-expected
-- columns: i:serial | j:int4
-- row: 1 | 1
-- row: 2 | 2
-- row: 1 | 3
-- rowcount: 3
-- end-expected
SELECT i, j FROM zz_t ORDER BY j;
-- begin-expected-error
-- sqlstate: 42P07
-- message-like: relation "zz_t" already exists
-- end-expected-error
CREATE TABLE zz_t (i int GENERATED ALWAYS AS IDENTITY (SEQUENCE NAME zz_my_seq), j int);
-- begin-expected
-- columns: pg_get_serial_sequence:text
-- row: public.zz_t_i_seq
-- rowcount: 1
-- end-expected
SELECT pg_get_serial_sequence('zz_t','i');
-- begin-expected-error
-- sqlstate: 42P07
-- message-like: relation "zz_t" already exists
-- end-expected-error
CREATE TABLE zz_t (a int GENERATED BY DEFAULT AS IDENTITY, b text);
-- begin-expected-error
-- sqlstate: 42703
-- message-like: column "a" of relation "zz_t" does not exist
-- end-expected-error
ALTER TABLE zz_t ALTER COLUMN a SET INCREMENT BY 10;
-- begin-expected-error
-- sqlstate: 42703
-- message-like: column "b" of relation "zz_t" does not exist
-- end-expected-error
INSERT INTO zz_t (b) VALUES ('p');
-- begin-expected-error
-- sqlstate: 42703
-- message-like: column "b" of relation "zz_t" does not exist
-- end-expected-error
INSERT INTO zz_t (b) VALUES ('q') RETURNING a;
-- begin-expected-error
-- sqlstate: 42P07
-- message-like: relation "zz_t" already exists
-- end-expected-error
CREATE TABLE zz_t (a int GENERATED ALWAYS AS IDENTITY, b int) PARTITION BY RANGE (b);
-- begin-expected-error
-- sqlstate: 42P17
-- message-like: "zz_t" is not partitioned
-- end-expected-error
CREATE TABLE zz_tp PARTITION OF zz_t FOR VALUES FROM (0) TO (10);
-- begin-expected
-- columns: relname:name
-- row: zz_t_i_seq
-- rowcount: 1
-- end-expected
SELECT relname FROM pg_class WHERE relkind='S' AND relname LIKE 'zz\_t%' ORDER BY relname;
-- begin-expected-error
-- sqlstate: 22023
-- message-like: CACHE (0) must be greater than zero
-- end-expected-error
CREATE TABLE zz_t (i int GENERATED ALWAYS AS IDENTITY (CACHE 0), j int);
