-- source: investigation-2026-08.md
-- finding: 355
-- title: Unrelated singletons in this area
-- begin-expected-error
-- sqlstate: 42704
-- message-like: type "zz_vf2_ct" does not exist
-- end-expected-error
SELECT ('(t,"a""b",1)'::zz_vf2_ct).s;
-- begin-expected-error
-- sqlstate: 42704
-- message-like: type "zz_vf2_ct" does not exist
-- end-expected-error
SELECT ((ROW(true, 'a"b', 1)::zz_vf2_ct)::text::zz_vf2_ct).s;
-- begin-expected-error
-- sqlstate: 42704
-- message-like: type "zz_vf2_ct" does not exist
-- end-expected-error
SELECT ('(t,a\,b,1)'::zz_vf2_ct).s;
-- begin-expected
-- ok: 0
-- end-expected
CREATE TABLE zz_vf2_t (a int, s text, arr int[], ts timestamptz);
-- begin-expected
-- ok: 0
-- end-expected
CREATE VIEW zz_vf2_w1 AS SELECT a, row_number() OVER (ORDER BY a) AS rn FROM zz_vf2_t;
-- begin-expected
-- columns: pg_get_viewdef:text
-- row:  SELECT a,\n    row_number() OVER (ORDER BY a) AS rn\n   FROM zz_vf2_t;
-- rowcount: 1
-- end-expected
SELECT pg_get_viewdef('zz_vf2_w1'::regclass);
-- begin-expected
-- ok: 0
-- end-expected
CREATE SCHEMA zz_vf2_s;
-- begin-expected
-- ok: 0
-- end-expected
CREATE TABLE zz_vf2_s.t2 (c int);
-- begin-expected
-- ok: 0
-- end-expected
CREATE TABLE zz_vf2_qt ("From" int, "A b" int);
-- begin-expected
-- ok: 0
-- end-expected
CREATE VIEW zz_vf2_k1 AS SELECT "From" FROM zz_vf2_qt;
-- begin-expected
-- ok: 0
-- end-expected
CREATE VIEW zz_vf2_k2 AS SELECT "A b" AS "Out Col" FROM zz_vf2_qt;
-- begin-expected
-- ok: 0
-- end-expected
CREATE VIEW zz_vf2_k3 AS SELECT c FROM zz_vf2_s.t2;
-- begin-expected
-- columns: pg_get_viewdef:text
-- row:  SELECT "From"\n   FROM zz_vf2_qt;
-- rowcount: 1
-- end-expected
SELECT pg_get_viewdef('zz_vf2_k1'::regclass);
-- begin-expected
-- columns: pg_get_viewdef:text
-- row:  SELECT "A b" AS "Out Col"\n   FROM zz_vf2_qt;
-- rowcount: 1
-- end-expected
SELECT pg_get_viewdef('zz_vf2_k2'::regclass);
-- begin-expected
-- columns: pg_get_viewdef:text
-- row:  SELECT c\n   FROM zz_vf2_s.t2;
-- rowcount: 1
-- end-expected
SELECT pg_get_viewdef('zz_vf2_k3'::regclass);
-- begin-expected
-- ok: 0
-- end-expected
CREATE TABLE zz_vf2_pk (id int primary key);
-- begin-expected-error
-- sqlstate: 42601
-- message-like: constraint declared INITIALLY DEFERRED must be DEFERRABLE
-- end-expected-error
CREATE TABLE zz_vf2_fk (id int, p int REFERENCES zz_vf2_pk(id) NOT DEFERRABLE INITIALLY DEFERRED);
-- begin-expected-error
-- sqlstate: 42601
-- message-like: constraint declared INITIALLY DEFERRED must be DEFERRABLE
-- end-expected-error
CREATE TABLE zz_vf2_fk2 (id int, p int, CONSTRAINT zz_vf2_c1 FOREIGN KEY (p) REFERENCES zz_vf2_pk(id) NOT DEFERRABLE INITIALLY DEFERRED);
-- begin-expected-error
-- sqlstate: 42601
-- message-like: constraint declared INITIALLY DEFERRED must be DEFERRABLE
-- end-expected-error
CREATE TABLE zz_vf2_u1 (a int, CONSTRAINT zz_vf2_c2 UNIQUE (a) NOT DEFERRABLE INITIALLY DEFERRED);
-- begin-expected-error
-- sqlstate: 42601
-- message-like: constraint declared INITIALLY DEFERRED must be DEFERRABLE
-- end-expected-error
CREATE TABLE zz_vf2_p2 (a int PRIMARY KEY NOT DEFERRABLE INITIALLY DEFERRED);
-- begin-expected
-- columns: conname:name | condeferrable:bool | condeferred:bool
-- rowcount: 0
-- end-expected
SELECT conname, condeferrable, condeferred FROM pg_constraint WHERE conname='zz_vf2_c1';
-- begin-expected-error
-- sqlstate: 42601
-- message-like: conflicting NULL/NOT NULL declarations for column "a" of table "zz_vf2_n1"
-- end-expected-error
CREATE TABLE zz_vf2_n1 (a int NOT NULL NULL);
-- begin-expected-error
-- sqlstate: 42601
-- message-like: conflicting NULL/NOT NULL declarations for column "a" of table "zz_vf2_n2"
-- end-expected-error
CREATE TABLE zz_vf2_n2 (a int NULL NOT NULL);
-- begin-expected-error
-- sqlstate: 42601
-- message-like: multiple default values specified for column "a" of table "zz_vf2_d1"
-- end-expected-error
CREATE TABLE zz_vf2_d1 (a int DEFAULT 1 DEFAULT 2);
-- begin-expected
-- columns: is_nullable:varchar
-- rowcount: 0
-- end-expected
SELECT is_nullable FROM information_schema.columns WHERE table_name='zz_vf2_n1' AND column_name='a';
-- begin-expected
-- columns: column_default:varchar
-- rowcount: 0
-- end-expected
SELECT column_default FROM information_schema.columns WHERE table_name='zz_vf2_d1' AND column_name='a';
-- begin-expected-error
-- sqlstate: 42601
-- message-like: syntax error at or near "'4MB'"
-- end-expected-error
SET work_mem '4MB' rubbish;
-- begin-expected-error
-- sqlstate: 42601
-- message-like: syntax error at or near "'ISO'"
-- end-expected-error
SET datestyle 'ISO' junk here;
-- begin-expected-error
-- sqlstate: 22023
-- message-like: START value (-5) cannot be less than MINVALUE (1)
-- end-expected-error
CREATE TABLE zz_vf2_i1 (id int    GENERATED BY DEFAULT AS IDENTITY (START WITH -5), v text);
-- begin-expected-error
-- sqlstate: 22023
-- message-like: START value (1) cannot be greater than MAXVALUE (-1)
-- end-expected-error
CREATE TABLE zz_vf2_i2 (id bigint GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY -1), v text);
-- begin-expected-error
-- sqlstate: 22003
-- message-like: value "99999999999999999999" is out of range for type bigint
-- end-expected-error
CREATE TABLE zz_vf2_i3 (id bigint GENERATED ALWAYS AS IDENTITY (START WITH 99999999999999999999), v text);
-- begin-expected
-- ok: 0
-- end-expected
CREATE TABLE zz_vf2_i4 (id int    GENERATED ALWAYS AS IDENTITY (MINVALUE -10 START WITH -5), v text);
-- begin-expected-error
-- sqlstate: 42601
-- message-like: syntax error at or near "BOGUS"
-- end-expected-error
SELECT sum(g) OVER (ORDER BY g ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW EXCLUDE BOGUS) FROM generate_series(1,3) g;
-- begin-expected-error
-- sqlstate: 42601
-- message-like: syntax error at or near ")"
-- end-expected-error
SELECT sum(g) OVER (ORDER BY g ROWS UNBOUNDED PRECEDING EXCLUDE) FROM generate_series(1,3) g;
-- begin-expected-error
-- sqlstate: 42601
-- message-like: syntax error at or near "END"
-- end-expected-error
SELECT CASE 1 END;
-- begin-expected-error
-- sqlstate: 42601
-- message-like: syntax error at or near "ELSE"
-- end-expected-error
SELECT CASE 1 ELSE 2 END;
-- begin-expected
-- ok: 0
-- end-expected
CREATE TABLE zz_vf2_ix (arr int[]);
-- begin-expected-error
-- sqlstate: 42804
-- message-like: collations are not supported by type integer[]
-- end-expected-error
CREATE INDEX zz_vf2_i3 ON zz_vf2_ix (arr COLLATE "C");
-- begin-expected
-- ok: 0
-- end-expected
CREATE DOMAIN zz_vf2_dom AS int;
-- begin-expected
-- ok: 0
-- end-expected
CREATE TABLE zz_vf2_o3 (a zz_vf2_dom);
-- begin-expected-error
-- sqlstate: 42804
-- message-like: collations are not supported by type public.zz_vf2_dom
-- end-expected-error
CREATE INDEX zz_vf2_dx ON zz_vf2_o3 (a COLLATE "C");
