package com.memgres.catalog;

import com.memgres.core.Memgres;
import org.junit.jupiter.api.*;

import java.sql.*;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Round 16 gap category J: Catalog completeness.
 *
 * Covers missing / hardcoded / wrong-typed columns in pg_class, pg_attribute,
 * pg_type, pg_proc, pg_aggregate, pg_operator, pg_constraint, pg_index,
 * pg_range, pg_ts_config_map, pg_extension, pg_largeobject_metadata,
 * pg_parameter_acl, pg_replication_slots/pg_stat_wal_senders, and
 * information_schema.* fall-throughs.
 */
class Round16CatalogCompletenessTest {

    static Memgres memgres;
    static Connection conn;

    @BeforeAll
    static void setUp() throws Exception {
        memgres = Memgres.builder().port(0).build().start();
        conn = DriverManager.getConnection(
                memgres.getJdbcUrl() + "?preferQueryMode=simple",
                memgres.getUser(), memgres.getPassword());
        conn.setAutoCommit(true);
    }

    @AfterAll
    static void tearDown() throws Exception {
        if (conn != null) conn.close();
        if (memgres != null) memgres.close();
    }

    private static void exec(String sql) throws SQLException {
        try (Statement s = conn.createStatement()) { s.execute(sql); }
    }

    private static String str(String sql) throws SQLException {
        try (Statement s = conn.createStatement(); ResultSet rs = s.executeQuery(sql)) {
            assertTrue(rs.next());
            return rs.getString(1);
        }
    }

    private static int intQ(String sql) throws SQLException {
        try (Statement s = conn.createStatement(); ResultSet rs = s.executeQuery(sql)) {
            assertTrue(rs.next());
            return rs.getInt(1);
        }
    }

    // =========================================================================
    // J1. pg_class.relkind encodes 'm' for matviews, 'I' for partitioned index
    // =========================================================================

    @Test
    void matview_relkind_is_m() throws SQLException {
        exec("DROP MATERIALIZED VIEW IF EXISTS r16_mv");
        exec("CREATE MATERIALIZED VIEW r16_mv AS SELECT 1 AS v");
        String k = str("SELECT relkind::text FROM pg_class WHERE relname='r16_mv'");
        assertEquals("m", k,
                "materialized view must have pg_class.relkind='m'; got '" + k + "'");
    }

    @Test
    void partitioned_index_relkind_is_capital_I() throws SQLException {
        exec("DROP TABLE IF EXISTS r16_pi CASCADE");
        exec("CREATE TABLE r16_pi (id int) PARTITION BY RANGE (id)");
        exec("CREATE INDEX r16_pi_idx ON r16_pi(id)");
        String k = str("SELECT relkind::text FROM pg_class WHERE relname='r16_pi_idx'");
        assertEquals("I", k,
                "partitioned index must have pg_class.relkind='I' (uppercase); got '" + k + "'");
    }

    // =========================================================================
    // J2. pg_class.reloptions stores fillfactor
    // =========================================================================

    @Test
    void reloptions_stores_fillfactor() throws SQLException {
        exec("DROP TABLE IF EXISTS r16_ro");
        exec("CREATE TABLE r16_ro (id int) WITH (fillfactor=70)");
        try (Statement s = conn.createStatement();
             ResultSet rs = s.executeQuery(
                     "SELECT reloptions::text FROM pg_class WHERE relname='r16_ro'")) {
            assertTrue(rs.next());
            String v = rs.getString(1);
            assertNotNull(v, "pg_class.reloptions must be non-null when fillfactor set");
            assertTrue(v.contains("fillfactor=70"),
                    "reloptions must contain 'fillfactor=70'; got " + v);
        }
    }

    // =========================================================================
    // J3. pg_attribute.attidentity
    // =========================================================================

    @Test
    void identity_column_attidentity_a_for_always() throws SQLException {
        exec("DROP TABLE IF EXISTS r16_ida");
        exec("CREATE TABLE r16_ida (id int GENERATED ALWAYS AS IDENTITY)");
        String v = str("SELECT attidentity::text FROM pg_attribute " +
                "WHERE attrelid='r16_ida'::regclass AND attname='id'");
        assertEquals("a", v,
                "GENERATED ALWAYS AS IDENTITY must set attidentity='a'; got '" + v + "'");
    }

    @Test
    void identity_column_attidentity_d_for_by_default() throws SQLException {
        exec("DROP TABLE IF EXISTS r16_idd");
        exec("CREATE TABLE r16_idd (id int GENERATED BY DEFAULT AS IDENTITY)");
        String v = str("SELECT attidentity::text FROM pg_attribute " +
                "WHERE attrelid='r16_idd'::regclass AND attname='id'");
        assertEquals("d", v,
                "GENERATED BY DEFAULT AS IDENTITY must set attidentity='d'; got '" + v + "'");
    }

    // =========================================================================
    // J4. pg_attribute.attcompression
    // =========================================================================

    @Test
    void attcompression_defaults_to_p_or_empty_not_blank() throws SQLException {
        exec("DROP TABLE IF EXISTS r16_comp");
        exec("CREATE TABLE r16_comp (t text)");
        try (Statement s = conn.createStatement();
             ResultSet rs = s.executeQuery(
                     "SELECT attcompression::text FROM pg_attribute " +
                             "WHERE attrelid='r16_comp'::regclass AND attname='t'")) {
            assertTrue(rs.next());
            String v = rs.getString(1);
            // Default should be empty/unset (meaning \"use cluster default\"). But hardcoding \"\" unconditionally
            // hides user SET COMPRESSION. Accept NULL or \"\" here; subsequent test (J4b) exercises set.
            assertTrue(v == null || v.isEmpty() || "p".equals(v) || "l".equals(v),
                    "default attcompression must be empty/p/l; got '" + v + "'");
        }
        exec("ALTER TABLE r16_comp ALTER COLUMN t SET COMPRESSION pglz");
        String after = str("SELECT attcompression::text FROM pg_attribute " +
                "WHERE attrelid='r16_comp'::regclass AND attname='t'");
        assertEquals("p", after,
                "after SET COMPRESSION pglz, attcompression must be 'p'; got '" + after + "'");
    }

    // =========================================================================
    // J5. pg_attribute.atthasmissing / attmissingval for ADD COLUMN DEFAULT
    // =========================================================================

    @Test
    void add_column_with_default_populates_atthasmissing() throws SQLException {
        exec("DROP TABLE IF EXISTS r16_miss");
        exec("CREATE TABLE r16_miss (id int)");
        exec("INSERT INTO r16_miss VALUES (1)");
        exec("ALTER TABLE r16_miss ADD COLUMN v int DEFAULT 42");
        try (Statement s = conn.createStatement();
             ResultSet rs = s.executeQuery(
                     "SELECT atthasmissing FROM pg_attribute " +
                             "WHERE attrelid='r16_miss'::regclass AND attname='v'")) {
            assertTrue(rs.next());
            assertTrue(rs.getBoolean(1),
                    "ADD COLUMN ... DEFAULT const must set atthasmissing=true");
        }
    }

    // =========================================================================
    // J6. pg_type.typrelid for composite
    // =========================================================================

    @Test
    void composite_type_typrelid_is_nonzero() throws SQLException {
        exec("DROP TYPE IF EXISTS r16_ct CASCADE");
        exec("CREATE TYPE r16_ct AS (a int, b text)");
        long oid = Long.parseLong(str(
                "SELECT typrelid::text FROM pg_type WHERE typname='r16_ct'"));
        assertTrue(oid != 0L,
                "composite type pg_type.typrelid must be non-zero; got " + oid);
    }

    // =========================================================================
    // J7. pg_type.typelem non-zero for array type
    // =========================================================================

    @Test
    void array_type_typelem_points_to_element_type() throws SQLException {
        long elem = Long.parseLong(str(
                "SELECT typelem::text FROM pg_type WHERE typname='_int4'"));
        assertTrue(elem != 0L,
                "pg_type._int4.typelem must be the OID of int4 (23); got " + elem);
    }

    // =========================================================================
    // J8. pg_proc.proargmodes / proargnames array element types
    // =========================================================================

    @Test
    void pg_proc_proargmodes_is_char_array() throws SQLException {
        // array_recv is a classic function; simply assert the type of proargmodes
        // column (not its value). PG 18 declares it as `_char` (array of \"char\").
        String t = str(
                "SELECT format_type(atttypid, atttypmod) FROM pg_attribute " +
                "WHERE attrelid='pg_proc'::regclass AND attname='proargmodes'");
        assertEquals("\"char\"[]", t,
                "pg_proc.proargmodes must be declared \"char\"[] (_char); got " + t);
    }

    @Test
    void pg_proc_proargnames_is_text_array() throws SQLException {
        String t = str(
                "SELECT format_type(atttypid, atttypmod) FROM pg_attribute " +
                "WHERE attrelid='pg_proc'::regclass AND attname='proargnames'");
        assertEquals("text[]", t,
                "pg_proc.proargnames must be declared text[] (_text); got " + t);
    }

    // =========================================================================
    // J9. pg_aggregate built-in rows present
    // =========================================================================

    @Test
    void pg_aggregate_has_count_row() throws SQLException {
        int n = intQ("SELECT count(*)::int FROM pg_aggregate a " +
                "JOIN pg_proc p ON a.aggfnoid = p.oid WHERE p.proname='count'");
        assertTrue(n >= 1, "pg_aggregate must have at least one row for count(); got " + n);
    }

    @Test
    void pg_aggregate_has_array_agg_row() throws SQLException {
        int n = intQ("SELECT count(*)::int FROM pg_aggregate a " +
                "JOIN pg_proc p ON a.aggfnoid=p.oid WHERE p.proname='array_agg'");
        assertTrue(n >= 1, "pg_aggregate must have at least one array_agg row; got " + n);
    }

    // =========================================================================
    // J10. pg_operator.oprcode / oprleft / oprresult wired
    // =========================================================================

    @Test
    void pg_operator_int4_eq_has_nonzero_oprcode() throws SQLException {
        long code = Long.parseLong(str(
                "SELECT oprcode::text FROM pg_operator " +
                "WHERE oprname='=' AND oprleft=23 AND oprright=23 LIMIT 1"));
        assertTrue(code != 0L,
                "pg_operator for int4=int4 must have non-zero oprcode; got " + code);
    }

    // =========================================================================
    // J11. pg_constraint.confmatchtype and friends
    // =========================================================================

    @Test
    void pg_constraint_exposes_confmatchtype() throws SQLException {
        exec("DROP TABLE IF EXISTS r16_cm_c");
        exec("DROP TABLE IF EXISTS r16_cm_p");
        exec("CREATE TABLE r16_cm_p (id int PRIMARY KEY)");
        exec("CREATE TABLE r16_cm_c (pid int REFERENCES r16_cm_p MATCH FULL)");
        String m = str("SELECT confmatchtype::text FROM pg_constraint " +
                "WHERE conrelid='r16_cm_c'::regclass AND contype='f'");
        assertEquals("f", m,
                "MATCH FULL FK must set pg_constraint.confmatchtype='f'; got '" + m + "'");
    }

    // =========================================================================
    // J12. pg_index.indoption and indkey type
    // =========================================================================

    @Test
    void pg_index_indoption_encodes_desc_and_nulls_order() throws SQLException {
        exec("DROP TABLE IF EXISTS r16_iopt");
        exec("CREATE TABLE r16_iopt (a int, b int)");
        exec("CREATE INDEX r16_iopt_idx ON r16_iopt (a DESC NULLS LAST, b ASC NULLS FIRST)");
        // indoption encoding: 1 (DESC) + 2 (NULLS FIRST); per column
        // a DESC NULLS LAST = 1; b ASC NULLS FIRST = 2
        String opt = str("SELECT indoption::text FROM pg_index " +
                "WHERE indexrelid='r16_iopt_idx'::regclass");
        assertNotNull(opt);
        assertTrue(opt.contains("1") && opt.contains("2"),
                "pg_index.indoption must encode column DESC/NULLS bits; got " + opt);
    }

    @Test
    void pg_index_indkey_is_int2vector() throws SQLException {
        String t = str(
                "SELECT format_type(atttypid, atttypmod) FROM pg_attribute " +
                "WHERE attrelid='pg_index'::regclass AND attname='indkey'");
        assertEquals("int2vector", t,
                "pg_index.indkey must be declared int2vector; got " + t);
    }

    // =========================================================================
    // J13. pg_range populated for user-defined range
    // =========================================================================

    @Test
    void user_range_type_appears_in_pg_range() throws SQLException {
        exec("DROP TYPE IF EXISTS r16_myrng CASCADE");
        exec("CREATE TYPE r16_myrng AS RANGE (SUBTYPE = int4)");
        int n = intQ("SELECT count(*)::int FROM pg_range r " +
                "JOIN pg_type t ON r.rngtypid=t.oid WHERE t.typname='r16_myrng'");
        assertEquals(1, n,
                "user-defined range type must appear in pg_range; got " + n + " rows");
    }

    // =========================================================================
    // J14. pg_extension row after CREATE EXTENSION
    // =========================================================================

    @Test
    void create_extension_inserts_pg_extension_row() throws SQLException {
        exec("CREATE EXTENSION IF NOT EXISTS pgcrypto");
        int n = intQ("SELECT count(*)::int FROM pg_extension WHERE extname='pgcrypto'");
        assertEquals(1, n,
                "CREATE EXTENSION pgcrypto must insert row into pg_extension; got " + n);
    }

    // =========================================================================
    // J15. pg_parameter_acl relation exists (PG 15+)
    // =========================================================================

    @Test
    void pg_parameter_acl_relation_exists() throws SQLException {
        int n = intQ("SELECT count(*)::int FROM pg_class WHERE relname='pg_parameter_acl'");
        assertEquals(1, n, "pg_parameter_acl must exist (PG 15+)");
    }

    // =========================================================================
    // J16. pg_replication_slots + pg_stat_wal_senders views exist
    // =========================================================================

    @Test
    void pg_replication_slots_view_exists() throws SQLException {
        // Select must not raise \"relation does not exist\"
        try (Statement s = conn.createStatement();
             ResultSet rs = s.executeQuery("SELECT * FROM pg_replication_slots LIMIT 0")) {
            ResultSetMetaData m = rs.getMetaData();
            assertTrue(m.getColumnCount() > 0,
                    "pg_replication_slots must be a queryable relation");
        }
    }

    @Test
    void pg_stat_wal_senders_view_exists() throws SQLException {
        try (Statement s = conn.createStatement();
             ResultSet rs = s.executeQuery("SELECT * FROM pg_stat_wal_senders LIMIT 0")) {
            ResultSetMetaData m = rs.getMetaData();
            assertTrue(m.getColumnCount() > 0,
                    "pg_stat_wal_senders must be a queryable relation");
        }
    }

    // =========================================================================
    // J17. information_schema.views.is_updatable = 'YES' for simple 1-tbl view
    // =========================================================================

    @Test
    void information_schema_views_simple_view_is_updatable_yes() throws SQLException {
        exec("DROP VIEW IF EXISTS r16_uv CASCADE");
        exec("DROP TABLE IF EXISTS r16_uvt CASCADE");
        exec("CREATE TABLE r16_uvt (id int)");
        exec("CREATE VIEW r16_uv AS SELECT id FROM r16_uvt");
        String v = str("SELECT is_updatable FROM information_schema.views " +
                "WHERE table_name='r16_uv'");
        assertEquals("YES", v,
                "simple 1-table view must report is_updatable='YES'; got '" + v + "'");
    }
}
