DROP SCHEMA IF EXISTS test_200 CASCADE;
CREATE SCHEMA test_200;
SET search_path TO test_200;

CREATE TABLE accounts (
    id integer PRIMARY KEY,
    name text NOT NULL,
    balance integer NOT NULL,
    updated_at timestamp
);

CREATE TABLE account_audit (
    audit_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id integer NOT NULL,
    action text NOT NULL,
    old_balance integer,
    new_balance integer
);

CREATE FUNCTION normalize_account_name()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.name := upper(NEW.name);
    NEW.updated_at := TIMESTAMP '2024-01-01 00:00:00';
    RETURN NEW;
END;
$$;

CREATE FUNCTION audit_account_changes()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        INSERT INTO account_audit(account_id, action, old_balance, new_balance)
        VALUES (NEW.id, 'INSERT', NULL, NEW.balance);
        RETURN NEW;
    ELSIF TG_OP = 'UPDATE' THEN
        INSERT INTO account_audit(account_id, action, old_balance, new_balance)
        VALUES (NEW.id, 'UPDATE', OLD.balance, NEW.balance);
        RETURN NEW;
    ELSIF TG_OP = 'DELETE' THEN
        INSERT INTO account_audit(account_id, action, old_balance, new_balance)
        VALUES (OLD.id, 'DELETE', OLD.balance, NULL);
        RETURN OLD;
    END IF;
    RETURN NULL;
END;
$$;

CREATE TRIGGER trg_accounts_before_ins_upd
BEFORE INSERT OR UPDATE ON accounts
FOR EACH ROW
EXECUTE FUNCTION normalize_account_name();

CREATE TRIGGER trg_accounts_after_ins_upd_del
AFTER INSERT OR UPDATE OR DELETE ON accounts
FOR EACH ROW
EXECUTE FUNCTION audit_account_changes();

INSERT INTO accounts(id, name, balance) VALUES (1, 'alice', 10);
UPDATE accounts SET balance = 15, name = 'alice changed' WHERE id = 1;
DELETE FROM accounts WHERE id = 1;

-- begin-expected
-- columns: audit_id|account_id|action|old_balance|new_balance
-- row: 1|1|INSERT||10
-- row: 2|1|UPDATE|10|15
-- row: 3|1|DELETE|15|
-- end-expected
SELECT audit_id, account_id, action, old_balance, new_balance
FROM account_audit
ORDER BY audit_id;

DROP SCHEMA test_200 CASCADE;
