DROP SCHEMA IF EXISTS test_300 CASCADE;
CREATE SCHEMA test_300;
SET search_path TO test_300;

CREATE TABLE app_user (
    user_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email text UNIQUE NOT NULL,
    profile jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE task (
    task_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL REFERENCES app_user(user_id) ON DELETE CASCADE,
    title text NOT NULL,
    status text NOT NULL CHECK (status IN ('todo', 'doing', 'done')),
    estimate_hours numeric(6,2) NOT NULL,
    tags text[] NOT NULL DEFAULT ARRAY[]::text[],
    meta jsonb NOT NULL DEFAULT '{}'::jsonb,
    title_upper text GENERATED ALWAYS AS (upper(title)) STORED
);

CREATE TABLE task_audit (
    audit_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id integer NOT NULL,
    action text NOT NULL,
    old_status text,
    new_status text
);

CREATE FUNCTION audit_task_status()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        INSERT INTO task_audit(task_id, action, old_status, new_status)
        VALUES (NEW.task_id, 'INSERT', NULL, NEW.status);
        RETURN NEW;
    ELSIF TG_OP = 'UPDATE' THEN
        INSERT INTO task_audit(task_id, action, old_status, new_status)
        VALUES (NEW.task_id, 'UPDATE', OLD.status, NEW.status);
        RETURN NEW;
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_task_audit
AFTER INSERT OR UPDATE ON task
FOR EACH ROW
EXECUTE FUNCTION audit_task_status();

CREATE VIEW user_task_summary AS
SELECT
    u.user_id,
    u.email,
    COUNT(t.task_id) AS task_count,
    COALESCE(SUM(t.estimate_hours), 0) AS total_hours
FROM app_user u
LEFT JOIN task t ON t.user_id = u.user_id
GROUP BY u.user_id, u.email;

INSERT INTO app_user(email, profile) VALUES
    ('alice@example.com', '{"team":"eng"}'),
    ('bob@example.com', '{"team":"ops"}');

INSERT INTO task(user_id, title, status, estimate_hours, tags, meta) VALUES
    (1, 'design schema', 'todo', 3.50, ARRAY['db','design'], '{"priority":1}'),
    (1, 'implement api', 'doing', 5.00, ARRAY['api'], '{"priority":2}'),
    (2, 'write docs', 'done', 2.00, ARRAY['docs'], '{"priority":1}');

INSERT INTO task(user_id, title, status, estimate_hours, tags, meta)
VALUES (1, 'implement api', 'doing', 1.00, ARRAY['api','extra'], '{"priority":3}')
ON CONFLICT DO NOTHING;

UPDATE task
SET status = 'done',
    meta = jsonb_set(meta, '{priority}', to_jsonb(5), false)
WHERE user_id = 1
  AND title = 'implement api';

CREATE TABLE incoming_tasks (
    user_email text,
    title text,
    status text,
    estimate_hours numeric(6,2)
);

INSERT INTO incoming_tasks VALUES
    ('alice@example.com', 'review PR', 'todo', 1.50),
    ('bob@example.com', 'write docs', 'done', 1.00);

MERGE INTO task AS t
USING (
    SELECT u.user_id, i.title, i.status, i.estimate_hours
    FROM incoming_tasks i
    JOIN app_user u ON u.email = i.user_email
) AS s
ON t.user_id = s.user_id AND t.title = s.title
WHEN MATCHED THEN
    UPDATE SET estimate_hours = t.estimate_hours + s.estimate_hours
WHEN NOT MATCHED THEN
    INSERT (user_id, title, status, estimate_hours, tags, meta)
    VALUES (s.user_id, s.title, s.status, s.estimate_hours, ARRAY['merged'], '{}'::jsonb);

-- begin-expected
-- columns: user_id|email|task_count|total_hours
-- row: 1|alice@example.com|4|11.00
-- row: 2|bob@example.com|1|3.00
-- end-expected
SELECT user_id, email, task_count, total_hours
FROM user_task_summary
ORDER BY user_id;

-- begin-expected
-- columns: task_id|title|status|priority|rn
-- row: 1|design schema|todo|1|2
-- row: 2|implement api|done|5|1
-- row: 4|implement api|done|5|4
-- row: 5|review PR|todo||3
-- end-expected
SELECT
    task_id,
    title,
    status,
    meta->>'priority' AS priority,
    ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY estimate_hours DESC, task_id) AS rn
FROM task
WHERE user_id = 1
ORDER BY task_id;

BEGIN;
SAVEPOINT before_bad_change;
UPDATE task SET status = 'doing' WHERE task_id = 1;
ROLLBACK TO SAVEPOINT before_bad_change;
COMMIT;

-- begin-expected
-- columns: task_id|status|title_upper
-- row: 1|todo|DESIGN SCHEMA
-- row: 2|done|IMPLEMENT API
-- row: 3|done|WRITE DOCS
-- row: 4|done|IMPLEMENT API
-- row: 5|todo|REVIEW PR
-- end-expected
SELECT task_id, status, title_upper
FROM task
ORDER BY task_id;

-- begin-expected
-- columns: audit_id|task_id|action|old_status|new_status
-- row: 1|1|INSERT||todo
-- row: 2|2|INSERT||doing
-- row: 3|3|INSERT||done
-- row: 4|4|INSERT||doing
-- row: 5|2|UPDATE|doing|done
-- row: 6|4|UPDATE|doing|done
-- row: 7|5|INSERT||todo
-- row: 8|3|UPDATE|done|done
-- end-expected
SELECT audit_id, task_id, action, old_status, new_status
FROM task_audit
ORDER BY audit_id;

DROP SCHEMA test_300 CASCADE;
