package com.memgres.dml;

import com.memgres.core.Memgres;
import org.junit.jupiter.api.*;
import org.postgresql.copy.CopyManager;
import org.postgresql.core.BaseConnection;

import java.io.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.sql.*;
import java.util.*;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Compares COPY TO STDOUT output between PG 18 baseline and Memgres.
 *
 * Does NOT require a real PostgreSQL instance; uses the committed baseline file
 * generated by CopyOutputBaselineCollector.
 *
 * To regenerate the baseline (requires PG 18), run:
 *   mvn -pl memgres-core test-compile exec:java \
 *     -Dexec.mainClass="com.memgres.dml.CopyOutputBaselineCollector" \
 *     -Dexec.classpathScope=test
 */
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
class CopyOutputComparisonTest {

    static final String BASELINE_RESOURCE = "pg-baselines/copy-output-baseline.txt";

    static Memgres memgres;
    static Connection mgConn;
    static CopyManager mgCm;
    static Map<String, CopyEntry> baseline;

        public static final class CopyEntry {
        public final String cmd;
        public final String textOutput;
        public final byte[] binaryOutput;

        public CopyEntry(String cmd, String textOutput, byte[] binaryOutput) {
            this.cmd = cmd;
            this.textOutput = textOutput;
            this.binaryOutput = binaryOutput;
        }

        public String cmd() { return cmd; }
        public String textOutput() { return textOutput; }
        public byte[] binaryOutput() { return binaryOutput; }

        @Override
        public boolean equals(Object o) {
            if (this == o) return true;
            if (o == null || getClass() != o.getClass()) return false;
            CopyEntry that = (CopyEntry) o;
            return java.util.Objects.equals(cmd, that.cmd)
                && java.util.Objects.equals(textOutput, that.textOutput)
                && java.util.Arrays.equals(binaryOutput, that.binaryOutput);
        }

        @Override
        public int hashCode() {
            return java.util.Objects.hash(cmd, textOutput, java.util.Arrays.hashCode(binaryOutput));
        }

        @Override
        public String toString() {
            return "CopyEntry[cmd=" + cmd + ", " + "textOutput=" + textOutput + ", " + "binaryOutput=" + java.util.Arrays.toString(binaryOutput) + "]";
        }
    }

    @BeforeAll
    static void setUp() throws Exception {
        memgres = Memgres.builder().port(0).build().start();
        mgConn = DriverManager.getConnection(memgres.getJdbcUrl(), memgres.getUser(), memgres.getPassword());
        mgConn.setAutoCommit(true);
        mgCm = new CopyManager(mgConn.unwrap(BaseConnection.class));

        try (Statement s = mgConn.createStatement()) { s.execute("SET timezone = 'UTC'"); }

        baseline = loadBaseline();
    }

    @AfterAll
    static void tearDown() throws Exception {
        if (mgConn != null) mgConn.close();
        if (memgres != null) memgres.close();
    }

    // === Baseline loading ================================================

    static Map<String, CopyEntry> loadBaseline() throws Exception {
        InputStream is = CopyOutputComparisonTest.class.getClassLoader()
                .getResourceAsStream(BASELINE_RESOURCE);
        assertNotNull(is, "Baseline file not found: " + BASELINE_RESOURCE +
                ". Run CopyOutputBaselineCollector to generate it.");

        Map<String, CopyEntry> entries = new LinkedHashMap<>();
        try (BufferedReader br = new BufferedReader(new InputStreamReader(is, StandardCharsets.UTF_8))) {
            String line;
            String currentLabel = null;
            String currentCmd = null;
            StringBuilder textBuf = null;
            StringBuilder binaryBuf = null;
            boolean inText = false, inBinary = false;

            while ((line = br.readLine()) != null) {
                if (line.startsWith("=== COPY: ") && line.endsWith(" ===")) {
                    currentLabel = line.substring("=== COPY: ".length(), line.length() - " ===".length());
                } else if (line.startsWith("CMD: ")) {
                    currentCmd = line.substring("CMD: ".length());
                } else if (line.equals("TEXT_OUTPUT_START")) {
                    inText = true;
                    textBuf = new StringBuilder();
                } else if (line.equals("TEXT_OUTPUT_END")) {
                    inText = false;
                    if (currentLabel != null) {
                        entries.put(currentLabel, new CopyEntry(currentCmd, textBuf.toString(), null));
                    }
                } else if (line.equals("BINARY_OUTPUT_START")) {
                    inBinary = true;
                    binaryBuf = new StringBuilder();
                } else if (line.equals("BINARY_OUTPUT_END")) {
                    inBinary = false;
                    if (currentLabel != null) {
                        byte[] bytes = Base64.getDecoder().decode(binaryBuf.toString().trim());
                        entries.put(currentLabel, new CopyEntry(currentCmd, null, bytes));
                    }
                } else if (inText && textBuf != null) {
                    textBuf.append(line).append("\n");
                } else if (inBinary && binaryBuf != null) {
                    binaryBuf.append(line.trim());
                }
            }
        }
        return entries;
    }

    // === Helpers =========================================================

    static void execMg(String sql) throws SQLException {
        try (Statement s = mgConn.createStatement()) { s.execute(sql); }
    }

    static String mgCopyOut(String copyCmd) throws SQLException, IOException {
        StringWriter sw = new StringWriter();
        mgCm.copyOut(copyCmd, sw);
        return sw.toString();
    }

    static byte[] mgCopyOutBytes(String copyCmd) throws SQLException, IOException {
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        mgCm.copyOut(copyCmd, baos);
        return baos.toByteArray();
    }

    void assertCopyMatchesBaseline(String label) throws Exception {
        CopyEntry entry = baseline.get(label);
        assertNotNull(entry, "No baseline entry for: " + label);

        if (entry.textOutput != null) {
            String mgOut = mgCopyOut(entry.cmd);
            if (!entry.textOutput.equals(mgOut)) {
                fail(label + ": COPY output differs from PG 18 baseline:\n" + lineDiff(entry.textOutput, mgOut));
            }
        } else if (entry.binaryOutput != null) {
            byte[] mgOut = mgCopyOutBytes(entry.cmd);
            if (!Arrays.equals(entry.binaryOutput, mgOut)) {
                fail(label + ": BINARY COPY output differs from PG 18 baseline. PG=" +
                        entry.binaryOutput.length + " bytes, MG=" + mgOut.length + " bytes\n"
                        + hexDiff(entry.binaryOutput, mgOut));
            }
        }
    }

    static String lineDiff(String expected, String actual) {
        String[] expLines = expected.split("\n", -1);
        String[] actLines = actual.split("\n", -1);
        StringBuilder sb = new StringBuilder();
        int maxLines = Math.max(expLines.length, actLines.length);
        int diffCount = 0;
        for (int i = 0; i < maxLines && diffCount < 20; i++) {
            String exp = i < expLines.length ? expLines[i] : "<missing>";
            String act = i < actLines.length ? actLines[i] : "<missing>";
            if (!exp.equals(act)) {
                diffCount++;
                sb.append(String.format("  Line %d:%n    PG: %s%n    MG: %s%n", i + 1,
                        escape(exp), escape(act)));
            }
        }
        if (diffCount == 0) sb.append("  (no line differences; may be trailing whitespace)\n");
        return sb.toString();
    }

    static String escape(String s) {
        return s.replace("\t", "\\t").replace("\r", "\\r").replace("\n", "\\n");
    }

    static String hexDiff(byte[] a, byte[] b) {
        StringBuilder sb = new StringBuilder();
        int len = Math.min(a.length, b.length);
        int diffCount = 0;
        for (int i = 0; i < len && diffCount < 10; i++) {
            if (a[i] != b[i]) {
                diffCount++;
                sb.append(String.format("  offset %d: PG=0x%02X MG=0x%02X%n", i, a[i] & 0xFF, b[i] & 0xFF));
            }
        }
        if (a.length != b.length) {
            sb.append(String.format("  Length mismatch: PG=%d bytes, MG=%d bytes%n", a.length, b.length));
        }
        return sb.toString();
    }

    // === Test setup: create tables and insert data in Memgres ============

    @Test @Order(0)
    void setupTables() throws Exception {
        // integers
        execMg("CREATE TABLE copy_integers (a smallint, b integer, c bigint)");
        execMg("INSERT INTO copy_integers VALUES (1, 100, 10000000000)");
        execMg("INSERT INTO copy_integers VALUES (-32768, -2147483648, -9223372036854775808)");
        execMg("INSERT INTO copy_integers VALUES (32767, 2147483647, 9223372036854775807)");
        execMg("INSERT INTO copy_integers VALUES (0, 0, 0)");
        execMg("INSERT INTO copy_integers VALUES (NULL, NULL, NULL)");
        // floats
        execMg("CREATE TABLE copy_floats (a real, b double precision, c numeric(10,2), d numeric)");
        execMg("INSERT INTO copy_floats VALUES (1.5, 2.5, 123.45, 99999999999999999.12345)");
        execMg("INSERT INTO copy_floats VALUES (0.0, 0.0, 0.00, 0)");
        execMg("INSERT INTO copy_floats VALUES (-1.5, -2.5, -123.45, -1)");
        execMg("INSERT INTO copy_floats VALUES ('NaN'::real, 'NaN'::double precision, NULL, NULL)");
        execMg("INSERT INTO copy_floats VALUES ('Infinity'::real, 'Infinity'::double precision, NULL, NULL)");
        execMg("INSERT INTO copy_floats VALUES ('-Infinity'::real, '-Infinity'::double precision, NULL, NULL)");
        execMg("INSERT INTO copy_floats VALUES (NULL, NULL, NULL, NULL)");
        // strings
        execMg("CREATE TABLE copy_strings (a text, b varchar(100), c char(5))");
        execMg("INSERT INTO copy_strings VALUES ('hello', 'world', 'abc')");
        execMg("INSERT INTO copy_strings VALUES ('', '', '     ')");
        execMg("INSERT INTO copy_strings VALUES ('tab\there', 'new\nline', 'bk\\sl')");
        execMg("INSERT INTO copy_strings VALUES ('single''quote', 'double\"quote', 'combo')");
        execMg("INSERT INTO copy_strings VALUES (NULL, NULL, NULL)");
        execMg("INSERT INTO copy_strings VALUES ('emoji: \uD83D\uDE00', 'CJK: \u4e16\u754c', 'ok   ')");
        // temporal
        execMg("CREATE TABLE copy_temporal (a date, b time, c timestamp, d timestamptz, e interval)");
        execMg("INSERT INTO copy_temporal VALUES ('2024-01-15', '10:30:00', '2024-01-15 10:30:00', '2024-01-15 10:30:00+00', '1 year 2 months 3 days')");
        execMg("INSERT INTO copy_temporal VALUES ('1970-01-01', '00:00:00', '1970-01-01 00:00:00', '1970-01-01 00:00:00+00', '0 seconds')");
        execMg("INSERT INTO copy_temporal VALUES ('2099-12-31', '23:59:59.999999', '2099-12-31 23:59:59.999999', '2099-12-31 23:59:59.999999+00', '-1 day')");
        execMg("INSERT INTO copy_temporal VALUES (NULL, NULL, NULL, NULL, NULL)");
        // boolean
        execMg("CREATE TABLE copy_bool (a boolean)");
        execMg("INSERT INTO copy_bool VALUES (true)");
        execMg("INSERT INTO copy_bool VALUES (false)");
        execMg("INSERT INTO copy_bool VALUES (NULL)");
        // uuid
        execMg("CREATE TABLE copy_uuid (a uuid)");
        execMg("INSERT INTO copy_uuid VALUES ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11')");
        execMg("INSERT INTO copy_uuid VALUES ('00000000-0000-0000-0000-000000000000')");
        execMg("INSERT INTO copy_uuid VALUES (NULL)");
        // json
        execMg("CREATE TABLE copy_json (a json, b jsonb)");
        execMg("INSERT INTO copy_json VALUES ('{\"key\": \"value\"}', '{\"key\": \"value\"}')");
        execMg("INSERT INTO copy_json VALUES ('[]', '[]')");
        execMg("INSERT INTO copy_json VALUES ('null', 'null')");
        execMg("INSERT INTO copy_json VALUES ('{\"nested\": {\"arr\": [1,2,3]}}', '{\"nested\": {\"arr\": [1,2,3]}}')");
        execMg("INSERT INTO copy_json VALUES (NULL, NULL)");
        // arrays
        execMg("CREATE TABLE copy_arrays (a int[], b text[], c boolean[])");
        execMg("INSERT INTO copy_arrays VALUES ('{1,2,3}', '{hello,world}', '{t,f,t}')");
        execMg("INSERT INTO copy_arrays VALUES ('{}', '{}', '{}')");
        execMg("INSERT INTO copy_arrays VALUES ('{NULL,1,NULL}', '{NULL,\"has space\",NULL}', '{NULL}')");
        execMg("INSERT INTO copy_arrays VALUES (NULL, NULL, NULL)");
        // bytea
        execMg("CREATE TABLE copy_bytea (a bytea)");
        execMg("INSERT INTO copy_bytea VALUES ('\\x48656c6c6f')");
        execMg("INSERT INTO copy_bytea VALUES ('\\x00ff01fe')");
        execMg("INSERT INTO copy_bytea VALUES ('\\x')");
        execMg("INSERT INTO copy_bytea VALUES (NULL)");
        // network
        execMg("CREATE TABLE copy_network (a inet, b cidr)");
        execMg("INSERT INTO copy_network VALUES ('192.168.1.1', '10.0.0.0/8')");
        execMg("INSERT INTO copy_network VALUES ('::1', '::ffff:0:0/96')");
        execMg("INSERT INTO copy_network VALUES (NULL, NULL)");
        // enum
        execMg("CREATE TYPE test_mood AS ENUM ('happy', 'sad', 'neutral')");
        execMg("CREATE TABLE copy_enum (a test_mood)");
        execMg("INSERT INTO copy_enum VALUES ('happy')");
        execMg("INSERT INTO copy_enum VALUES ('sad')");
        execMg("INSERT INTO copy_enum VALUES (NULL)");
        // mixed
        execMg("CREATE TABLE copy_mixed (id serial PRIMARY KEY, name text NOT NULL, email varchar(255), score numeric(5,2), active boolean DEFAULT true, created_at timestamptz DEFAULT '2024-01-01 00:00:00+00', tags text[], metadata jsonb, uid uuid)");
        execMg("INSERT INTO copy_mixed (name, email, score, active, tags, metadata, uid) VALUES ('Alice', 'alice@test.com', 95.5, true, '{admin,user}', '{\"role\": \"admin\"}', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11')");
        execMg("INSERT INTO copy_mixed (name, email, score, active, tags, metadata, uid) VALUES ('Bob', NULL, NULL, false, '{}', 'null', NULL)");
        execMg("INSERT INTO copy_mixed (name, email, score, active, tags, metadata, uid) VALUES ('Carol', 'carol@test.com', 0.00, true, NULL, NULL, NULL)");
        // nulls
        execMg("CREATE TABLE copy_nulls (a text, b int, c boolean, d jsonb, e text[])");
        execMg("INSERT INTO copy_nulls VALUES (NULL, NULL, NULL, NULL, NULL)");
        execMg("INSERT INTO copy_nulls VALUES ('', 0, false, 'null', '{}')");
        execMg("INSERT INTO copy_nulls VALUES ('\\N', 0, false, '\"\\\\N\"', '{\"\\\\N\"}')");
    }

    // === Text COPY tests =================================================

    @Test @Order(1)  void copyText_integers()            throws Exception { assertCopyMatchesBaseline("integers TEXT"); assertCopyMatchesBaseline("integers CSV"); assertCopyMatchesBaseline("integers CSV+HEADER"); }
    @Test @Order(2)  void copyText_floats()              throws Exception { assertCopyMatchesBaseline("floats TEXT"); assertCopyMatchesBaseline("floats CSV"); }
    @Test @Order(3)  void copyText_strings()             throws Exception { assertCopyMatchesBaseline("strings TEXT"); assertCopyMatchesBaseline("strings CSV"); assertCopyMatchesBaseline("strings CSV custom quote"); }
    @Test @Order(4)  void copyText_temporal()            throws Exception { assertCopyMatchesBaseline("temporal TEXT"); assertCopyMatchesBaseline("temporal CSV"); }
    @Test @Order(5)  void copyText_boolean()             throws Exception { assertCopyMatchesBaseline("bool TEXT"); assertCopyMatchesBaseline("bool CSV"); }
    @Test @Order(6)  void copyText_uuid()                throws Exception { assertCopyMatchesBaseline("uuid TEXT"); assertCopyMatchesBaseline("uuid CSV"); }
    @Test @Order(7)  void copyText_json()                throws Exception { assertCopyMatchesBaseline("json TEXT"); assertCopyMatchesBaseline("json CSV"); }
    @Test @Order(8)  void copyText_arrays()              throws Exception { assertCopyMatchesBaseline("arrays TEXT"); assertCopyMatchesBaseline("arrays CSV"); }
    @Test @Order(9)  void copyText_bytea()               throws Exception { assertCopyMatchesBaseline("bytea TEXT"); assertCopyMatchesBaseline("bytea CSV"); }
    @Test @Order(10) void copyText_network()             throws Exception { assertCopyMatchesBaseline("network TEXT"); assertCopyMatchesBaseline("network CSV"); }
    @Test @Order(11) void copyText_enum()                throws Exception { assertCopyMatchesBaseline("enum TEXT"); assertCopyMatchesBaseline("enum CSV"); }
    @Test @Order(12) void copyText_mixed()               throws Exception { assertCopyMatchesBaseline("mixed TEXT"); assertCopyMatchesBaseline("mixed CSV"); assertCopyMatchesBaseline("mixed CSV+HEADER"); }
    @Test @Order(13) void copyText_nullVariations()      throws Exception { assertCopyMatchesBaseline("nulls TEXT default"); assertCopyMatchesBaseline("nulls TEXT custom NULL"); assertCopyMatchesBaseline("nulls CSV"); assertCopyMatchesBaseline("nulls CSV custom NULL"); }
    @Test @Order(14) void copyText_options_delimiter()   throws Exception { assertCopyMatchesBaseline("integers pipe delimiter"); }
    @Test @Order(15) void copyText_options_forceQuote()  throws Exception { assertCopyMatchesBaseline("strings FORCE_QUOTE *"); assertCopyMatchesBaseline("strings FORCE_QUOTE (a)"); }
    @Test @Order(16) void copyText_options_header()      throws Exception { assertCopyMatchesBaseline("integers HEADER"); assertCopyMatchesBaseline("strings TEXT HEADER"); }
    @Test @Order(17) void copyText_subquery()            throws Exception { assertCopyMatchesBaseline("subquery TEXT"); assertCopyMatchesBaseline("subquery CSV"); }
    @Test @Order(18) void copyText_columnList()          throws Exception { assertCopyMatchesBaseline("column list TEXT"); assertCopyMatchesBaseline("column list CSV"); }

    // === Binary COPY tests ===============================================

    @Test @Order(20) void copyBinary_integers() throws Exception { assertCopyMatchesBaseline("integers BINARY"); }
    @Test @Order(21) void copyBinary_strings()  throws Exception { assertCopyMatchesBaseline("strings BINARY"); }
    @Test @Order(22) void copyBinary_boolean()  throws Exception { assertCopyMatchesBaseline("bool BINARY"); }
    @Test @Order(23) void copyBinary_mixed()    throws Exception { assertCopyMatchesBaseline("mixed BINARY"); }
}
