-- 156 identity
-- begin-expected-error
-- sqlstate: 22023
-- message-like: identity column type must be smallint, integer, or bigint
-- end-expected-error
CREATE TABLE zd_i0 (i text GENERATED ALWAYS AS IDENTITY);
-- begin-expected-error
-- sqlstate: 42601
-- message-like: both default and identity specified for column "i" of table "zd_i1"
-- end-expected-error
CREATE TABLE zd_i1 (i int GENERATED ALWAYS AS IDENTITY DEFAULT 1);
CREATE TABLE zd_i2 (i int, j int GENERATED ALWAYS AS IDENTITY);
-- begin-expected-error
-- sqlstate: 55000
-- message-like: column "i" of relation "zd_i2" is not an identity column
-- end-expected-error
ALTER TABLE zd_i2 ALTER COLUMN i DROP IDENTITY;
INSERT INTO zd_i2 (i) VALUES (NULL);
-- begin-expected-error
-- sqlstate: 55000
-- message-like: column "i" of relation "zd_i2" must be declared NOT NULL before identity can be added
-- end-expected-error
ALTER TABLE zd_i2 ALTER COLUMN i ADD GENERATED ALWAYS AS IDENTITY;
-- begin-expected-error
-- sqlstate: 22023
-- message-like: START value (-5) cannot be less than MINVALUE (1)
-- end-expected-error
CREATE TABLE zd_i3 (id int GENERATED BY DEFAULT AS IDENTITY (START WITH -5), v text);
-- begin-expected-error
-- sqlstate: 22023
-- message-like: START value (1) cannot be greater than MAXVALUE (-1)
-- end-expected-error
CREATE TABLE zd_i4 (id bigint GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY -1), v text);
-- begin-expected-error
-- sqlstate: 22003
-- message-like: value "99999999999999999999" is out of range for type bigint
-- end-expected-error
CREATE TABLE zd_i5 (id bigint GENERATED ALWAYS AS IDENTITY (START WITH 99999999999999999999), v text);
CREATE TABLE zd_i6 (id int GENERATED ALWAYS AS IDENTITY (MINVALUE -10 START WITH -5), v text);
-- begin-expected
-- columns: n
-- row: 1
-- end-expected
SELECT count(*)::int AS n FROM pg_class WHERE relname='zd_i6';
-- 157 virtual generated primary key
-- begin-expected-error
-- sqlstate: 0A000
-- message-like: primary keys on virtual generated columns are not supported
-- end-expected-error
CREATE TABLE zd_g1 (a int, b int GENERATED ALWAYS AS (a) VIRTUAL PRIMARY KEY);
-- 158 SET SCHEMA to a schema that is not there
CREATE TABLE zd_mo (a int);
-- begin-expected-error
-- sqlstate: 3F000
-- message-like: schema "zd_no_such_schema" does not exist
-- end-expected-error
ALTER TABLE zd_mo SET SCHEMA zd_no_such_schema;
-- begin-expected
-- columns: n
-- row: 0
-- end-expected
SELECT count(*)::int AS n FROM zd_mo;
-- 159 storage and compression
CREATE TABLE zd_st (i int, c text);
-- begin-expected-error
-- sqlstate: 22023
-- message-like: invalid storage type "nonsense"
-- end-expected-error
ALTER TABLE zd_st ALTER COLUMN c SET STORAGE NONSENSE;
-- begin-expected-error
-- sqlstate: 0A000
-- message-like: column data type integer can only have storage PLAIN
-- end-expected-error
ALTER TABLE zd_st ALTER COLUMN i SET STORAGE EXTERNAL;
-- begin-expected-error
-- sqlstate: 22023
-- message-like: invalid compression method "nosuchmethod"
-- end-expected-error
ALTER TABLE zd_st ALTER COLUMN c SET COMPRESSION nosuchmethod;
ALTER TABLE zd_st ALTER COLUMN c SET STORAGE EXTERNAL;
-- 160 SET WITHOUT CLUSTER and DISABLE RULE
CREATE INDEX zd_st_ix ON zd_st (i);
ALTER TABLE zd_st CLUSTER ON zd_st_ix;
ALTER TABLE zd_st SET WITHOUT CLUSTER;
CREATE RULE zd_st_r AS ON UPDATE TO zd_st DO ALSO NOTHING;
ALTER TABLE zd_st DISABLE RULE zd_st_r;
ALTER TABLE zd_st ENABLE RULE zd_st_r;
-- 161 SET CONSTRAINTS on a name nobody defined
-- begin-expected-error
-- sqlstate: 42704
-- message-like: constraint "zd_no_such_constraint" does not exist
-- end-expected-error
SET CONSTRAINTS zd_no_such_constraint DEFERRED;
-- begin-expected-error
-- sqlstate: 42601
-- message-like: syntax error at end of input
-- end-expected-error
SET CONSTRAINTS ALL;
SET CONSTRAINTS ALL IMMEDIATE;
-- 162 ATTACH / DETACH PARTITION
CREATE TABLE zd_p (i int, s text) PARTITION BY RANGE (i);
CREATE TABLE zd_pa PARTITION OF zd_p FOR VALUES FROM (1) TO (10);
CREATE TABLE zd_pd PARTITION OF zd_p DEFAULT;
-- begin-expected-error
-- sqlstate: 42P17
-- message-like: partition "zd_pd2" conflicts with existing default partition "zd_pd"
-- end-expected-error
CREATE TABLE zd_pd2 PARTITION OF zd_p DEFAULT;
CREATE TABLE zd_pn (i int, s text);
-- begin-expected-error
-- sqlstate: 42P17
-- message-like: empty range bound specified for partition "zd_pn"
-- end-expected-error
ALTER TABLE zd_p ATTACH PARTITION zd_pn FOR VALUES FROM (30) TO (20);
-- begin-expected-error
-- sqlstate: 42P16
-- message-like: invalid bound specification for a range partition
-- end-expected-error
ALTER TABLE zd_p ATTACH PARTITION zd_pn FOR VALUES IN (100);
CREATE TABLE zd_plain (i int, s text);
-- begin-expected-error
-- sqlstate: 42809
-- message-like: ALTER action ATTACH PARTITION cannot be performed on relation "zd_plain"
-- end-expected-error
ALTER TABLE zd_plain ATTACH PARTITION zd_pn FOR VALUES FROM (30) TO (40);
INSERT INTO zd_p VALUES (500, 'x');
-- begin-expected-error
-- sqlstate: 23514
-- message-like: updated partition constraint for default partition "zd_pd" would be violated by some row
-- end-expected-error
ALTER TABLE zd_p ATTACH PARTITION zd_pn FOR VALUES FROM (400) TO (600);
CREATE TABLE zd_notpart (i int, s text);
-- begin-expected-error
-- sqlstate: 42P01
-- message-like: relation "zd_notpart" is not a partition of relation "zd_p"
-- end-expected-error
ALTER TABLE zd_p DETACH PARTITION zd_notpart;
-- 163 dropping a partitioned parent
DROP TABLE zd_p;
-- begin-expected
-- columns: n
-- row: 0
-- end-expected
SELECT count(*)::int AS n FROM pg_class WHERE relname IN ('zd_p','zd_pa','zd_pd');
-- 164 ALTER TABLE ONLY on a partitioned parent
CREATE TABLE zd_q (i int) PARTITION BY RANGE (i);
CREATE TABLE zd_qa PARTITION OF zd_q FOR VALUES FROM (1) TO (10);
-- begin-expected-error
-- sqlstate: 42P16
-- message-like: column must be added to child tables too
-- end-expected-error
ALTER TABLE ONLY zd_q ADD COLUMN extra2 text;
-- 165 CREATE TRIGGER validation
CREATE TABLE zd_t (i int, j int);
CREATE VIEW zd_tv AS SELECT i, j FROM zd_t;
CREATE FUNCTION zd_tf() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RETURN NEW; END $$;
-- begin-expected-error
-- sqlstate: 0A000
-- message-like: INSTEAD OF triggers must be FOR EACH ROW
-- end-expected-error
CREATE TRIGGER zd_x1 INSTEAD OF INSERT ON zd_tv FOR EACH STATEMENT EXECUTE FUNCTION zd_tf();
-- begin-expected-error
-- sqlstate: 0A000
-- message-like: INSTEAD OF triggers cannot have WHEN conditions
-- end-expected-error
CREATE TRIGGER zd_x2 INSTEAD OF INSERT ON zd_tv FOR EACH ROW WHEN (true) EXECUTE FUNCTION zd_tf();
-- begin-expected-error
-- sqlstate: 42703
-- message-like: column "nosuch" of relation "zd_t" does not exist
-- end-expected-error
CREATE TRIGGER zd_x3 BEFORE UPDATE OF nosuch ON zd_t FOR EACH ROW EXECUTE FUNCTION zd_tf();
-- begin-expected-error
-- sqlstate: 42P17
-- message-like: DELETE trigger's WHEN condition cannot reference NEW values
-- end-expected-error
CREATE TRIGGER zd_x4 BEFORE DELETE ON zd_t FOR EACH ROW WHEN (NEW.i > 0) EXECUTE FUNCTION zd_tf();
-- begin-expected-error
-- sqlstate: 42P17
-- message-like: INSERT trigger's WHEN condition cannot reference OLD values
-- end-expected-error
CREATE TRIGGER zd_x5 BEFORE INSERT ON zd_t FOR EACH ROW WHEN (OLD.i > 0) EXECUTE FUNCTION zd_tf();
-- begin-expected-error
-- sqlstate: 42P17
-- message-like: statement trigger's WHEN condition cannot reference column values
-- end-expected-error
CREATE TRIGGER zd_x6 BEFORE INSERT ON zd_t FOR EACH STATEMENT WHEN (NEW.i > 0) EXECUTE FUNCTION zd_tf();
-- begin-expected-error
-- sqlstate: 0A000
-- message-like: cannot use subquery in trigger WHEN condition
-- end-expected-error
CREATE TRIGGER zd_x7 BEFORE INSERT ON zd_t FOR EACH ROW WHEN ((SELECT count(*) FROM zd_t) > 0) EXECUTE FUNCTION zd_tf();
-- begin-expected-error
-- sqlstate: 0A000
-- message-like: TRUNCATE FOR EACH ROW triggers are not supported
-- end-expected-error
CREATE TRIGGER zd_x8 BEFORE TRUNCATE ON zd_t FOR EACH ROW EXECUTE FUNCTION zd_tf();
CREATE TRIGGER zd_x9 BEFORE INSERT ON zd_t FOR EACH ROW EXECUTE FUNCTION zd_tf();
-- begin-expected-error
-- sqlstate: 42710
-- message-like: trigger "zd_x9" for relation "zd_t" already exists
-- end-expected-error
CREATE TRIGGER zd_x9 BEFORE INSERT ON zd_t FOR EACH ROW EXECUTE FUNCTION zd_tf();
-- begin-expected-error
-- sqlstate: 42P17
-- message-like: transition table name can only be specified for an AFTER trigger
-- end-expected-error
CREATE TRIGGER zd_xa BEFORE INSERT ON zd_t REFERENCING NEW TABLE AS nt FOR EACH STATEMENT EXECUTE FUNCTION zd_tf();
-- begin-expected-error
-- sqlstate: 42P17
-- message-like: OLD TABLE can only be specified for a DELETE or UPDATE trigger
-- end-expected-error
CREATE TRIGGER zd_xb AFTER INSERT ON zd_t REFERENCING OLD TABLE AS ot FOR EACH STATEMENT EXECUTE FUNCTION zd_tf();
-- 166 DISABLE TRIGGER on a name nobody defined
-- begin-expected-error
-- sqlstate: 42704
-- message-like: trigger "zd_no_such" for table "zd_t" does not exist
-- end-expected-error
ALTER TABLE zd_t DISABLE TRIGGER zd_no_such;
-- begin-expected-error
-- sqlstate: 42704
-- message-like: trigger "zd_no_such" for table "zd_t" does not exist
-- end-expected-error
ALTER TABLE zd_t ENABLE TRIGGER zd_no_such;
DROP VIEW zd_tv;
DROP TABLE zd_t CASCADE;
DROP TABLE zd_q CASCADE;
DROP TABLE zd_st CASCADE;
DROP TABLE zd_plain, zd_pn, zd_notpart CASCADE;
DROP FUNCTION zd_tf();
DROP TABLE IF EXISTS zd_i2, zd_i3, zd_i4, zd_i6, zd_mo CASCADE;
