-- ============================================================================
-- Feature Comparison: the CONTENT of information_schema
-- Target: PostgreSQL 18 vs Memgres
--
-- The shape of these views — which columns they have — is covered elsewhere.
-- What is checked here is whether the rows are there, because a standard view
-- that lists its columns and returns nothing is read by a tool as a definite
-- "no such thing" rather than as "I do not know":
--   * element_types is the only place a client can learn what an array column
--     holds, so an empty answer builds the wrong array decoder;
--   * constraint_table_usage answers "which foreign keys point at this table"
--     before a DROP, and it has to name the referenced table, not the
--     referencing one;
--   * the privilege views answer "may I write here", and PostgreSQL fills them
--     in from ownership without anyone having run a GRANT;
--   * views.check_option says whether a write through a view is checked at all.
--
-- Every case names a specific row with a WHERE that pins it and reads specific
-- columns. Nothing counts rows in a catalog: the two servers legitimately
-- contain different numbers of things.
-- ============================================================================

-- ============================================================================
-- Setup
-- ============================================================================

DROP SCHEMA IF EXISTS isv_s CASCADE;
DROP TYPE IF EXISTS isv_ct CASCADE;

CREATE SCHEMA isv_s;
CREATE DOMAIN isv_s.isv_dom AS varchar(10) CHECK (VALUE <> '');
CREATE DOMAIN isv_s.isv_dnum AS numeric(8,2);
CREATE TYPE isv_ct AS (x integer, y varchar(3), z timestamp(2));
CREATE TABLE isv_s.isv_parent (id int PRIMARY KEY, code varchar(20) UNIQUE);
CREATE TABLE isv_s.isv_child (
    cid int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pid int REFERENCES isv_s.isv_parent(id) ON DELETE CASCADE ON UPDATE SET NULL,
    amt numeric(10,2) CONSTRAINT isv_amt_chk CHECK (amt > 0),
    note isv_s.isv_dom,
    tags text[],
    ts timestamp(3),
    created timestamptz,
    flag boolean NOT NULL);
CREATE TABLE isv_s.isv_types (
    c_bit8 bit(8), c_vbit bit varying(9), c_arr int[],
    c_dom isv_s.isv_dom, c_dnum isv_s.isv_dnum,
    c_ts0 timestamp(0), c_ts3 timestamp(3), c_time4 time(4),
    c_iv interval day to second(3));
CREATE VIEW isv_s.isv_v AS SELECT id, code FROM isv_s.isv_parent;
CREATE VIEW isv_s.isv_v2 AS SELECT id FROM isv_s.isv_parent WITH CHECK OPTION;
CREATE FUNCTION isv_s.isv_fn(a int, b text DEFAULT 'x') RETURNS int
    LANGUAGE sql AS $$ SELECT a $$;
CREATE FUNCTION isv_s.isv_trgfn() RETURNS trigger
    LANGUAGE plpgsql AS $$ BEGIN RETURN NEW; END $$;
CREATE TRIGGER isv_trg BEFORE INSERT OR UPDATE OF code ON isv_s.isv_parent
    FOR EACH ROW EXECUTE FUNCTION isv_s.isv_trgfn();

-- ============================================================================
-- Privilege views: what an owner holds without anyone having run a GRANT
-- ============================================================================

-- begin-expected
-- columns: privilege_type,is_grantable,with_hierarchy
-- row: DELETE | YES | NO
-- row: INSERT | YES | NO
-- row: REFERENCES | YES | NO
-- row: SELECT | YES | YES
-- row: TRIGGER | YES | NO
-- row: TRUNCATE | YES | NO
-- row: UPDATE | YES | NO
-- end-expected
SELECT privilege_type, is_grantable, with_hierarchy
  FROM information_schema.table_privileges
 WHERE table_schema = 'isv_s' AND table_name = 'isv_child' AND grantee = current_user
 ORDER BY privilege_type;

-- A view is a relation here too.
-- begin-expected
-- columns: privilege_type,is_grantable
-- row: SELECT | YES
-- end-expected
SELECT privilege_type, is_grantable
  FROM information_schema.table_privileges
 WHERE table_schema = 'isv_s' AND table_name = 'isv_v'
   AND grantee = current_user AND privilege_type = 'SELECT';

-- role_table_grants answers for the same named row. The role's own name differs
-- between the two servers, so it is compared to current_user rather than printed.
-- begin-expected
-- columns: grantor_is_owner,is_grantable,with_hierarchy
-- row: OWNER | YES | YES
-- end-expected
SELECT CASE WHEN grantor = current_user THEN 'OWNER' ELSE grantor END AS grantor_is_owner,
       is_grantable, with_hierarchy
  FROM information_schema.role_table_grants
 WHERE table_schema = 'isv_s' AND table_name = 'isv_child'
   AND privilege_type = 'SELECT' AND grantee = current_user;

-- Only four privileges exist at column granularity.
-- begin-expected
-- columns: column_name,privilege_type,is_grantable
-- row: code | INSERT | YES
-- row: code | REFERENCES | YES
-- row: code | SELECT | YES
-- row: code | UPDATE | YES
-- row: id | INSERT | YES
-- row: id | REFERENCES | YES
-- row: id | SELECT | YES
-- row: id | UPDATE | YES
-- end-expected
SELECT column_name, privilege_type, is_grantable
  FROM information_schema.column_privileges
 WHERE table_schema = 'isv_s' AND table_name = 'isv_parent' AND grantee = current_user
 ORDER BY column_name, privilege_type;

-- begin-expected
-- columns: grantor_is_owner,is_grantable
-- row: OWNER | YES
-- end-expected
SELECT CASE WHEN grantor = current_user THEN 'OWNER' ELSE grantor END AS grantor_is_owner,
       is_grantable
  FROM information_schema.role_column_grants
 WHERE table_schema = 'isv_s' AND table_name = 'isv_parent'
   AND column_name = 'code' AND privilege_type = 'UPDATE' AND grantee = current_user;

-- EXECUTE goes to the owner and to PUBLIC, which is why anyone else may call it.
-- begin-expected
-- columns: grantee,privilege_type,is_grantable
-- row: PUBLIC | EXECUTE | NO
-- row: OWNER | EXECUTE | YES
-- end-expected
SELECT CASE WHEN grantee = current_user THEN 'OWNER' ELSE grantee END AS grantee,
       privilege_type, is_grantable
  FROM information_schema.routine_privileges
 WHERE routine_schema = 'isv_s' AND routine_name = 'isv_fn'
 ORDER BY is_grantable;

-- routine_privileges joins to routines on the specific name, or nothing can get
-- from a privilege to the routine it is about.
-- begin-expected
-- columns: routine_name,privilege_type
-- row: isv_fn | EXECUTE
-- end-expected
SELECT p.routine_name, p.privilege_type
  FROM information_schema.routine_privileges p
  JOIN information_schema.routines r
    ON r.specific_schema = p.specific_schema AND r.specific_name = p.specific_name
 WHERE p.routine_schema = 'isv_s' AND p.routine_name = 'isv_fn' AND p.grantee = current_user;

-- role_routine_grants keeps the grant to PUBLIC: PG's role_* views filter on the
-- grantor and grantee being roles the session may act as, and PUBLIC always is.
-- begin-expected
-- columns: grantee,privilege_type,is_grantable
-- row: PUBLIC | EXECUTE | NO
-- row: OWNER | EXECUTE | YES
-- end-expected
SELECT CASE WHEN grantee = current_user THEN 'OWNER' ELSE grantee END AS grantee,
       privilege_type, is_grantable
  FROM information_schema.role_routine_grants
 WHERE routine_schema = 'isv_s' AND routine_name = 'isv_trgfn'
 ORDER BY is_grantable;

-- A relation has a composite type of its own, and USAGE on it is reported here.
-- begin-expected
-- columns: grantee,privilege_type,is_grantable
-- row: PUBLIC | TYPE USAGE | NO
-- row: OWNER | TYPE USAGE | YES
-- end-expected
SELECT CASE WHEN grantee = current_user THEN 'OWNER' ELSE grantee END AS grantee,
       privilege_type, is_grantable
  FROM information_schema.udt_privileges
 WHERE udt_schema = 'isv_s' AND udt_name = 'isv_parent'
 ORDER BY is_grantable;

-- begin-expected
-- columns: privilege_type,is_grantable
-- row: TYPE USAGE | YES
-- end-expected
SELECT privilege_type, is_grantable
  FROM information_schema.udt_privileges
 WHERE udt_name = 'isv_ct' AND grantee = current_user;

-- begin-expected
-- columns: grantee,object_type,privilege_type,is_grantable
-- row: PUBLIC | DOMAIN | USAGE | NO
-- row: OWNER | DOMAIN | USAGE | YES
-- end-expected
SELECT CASE WHEN grantee = current_user THEN 'OWNER' ELSE grantee END AS grantee,
       object_type, privilege_type, is_grantable
  FROM information_schema.usage_privileges
 WHERE object_schema = 'isv_s' AND object_name = 'isv_dom'
 ORDER BY is_grantable;

-- One type descriptor per column of a table.
-- begin-expected
-- columns: object_type,dtd_identifier
-- row: TABLE | 1
-- row: TABLE | 2
-- row: TABLE | 3
-- row: TABLE | 4
-- row: TABLE | 5
-- row: TABLE | 6
-- row: TABLE | 7
-- row: TABLE | 8
-- end-expected
SELECT object_type, dtd_identifier
  FROM information_schema.data_type_privileges
 WHERE object_schema = 'isv_s' AND object_name = 'isv_child'
 ORDER BY dtd_identifier;

-- A domain has exactly one, and a routine has one per parameter plus 0 for its result.
-- begin-expected
-- columns: object_type,dtd_identifier
-- row: DOMAIN | 1
-- end-expected
SELECT object_type, dtd_identifier
  FROM information_schema.data_type_privileges
 WHERE object_schema = 'isv_s' AND object_name = 'isv_dnum';

-- begin-expected
-- columns: dtd_identifier
-- row: 0
-- row: 1
-- row: 2
-- end-expected
SELECT p.dtd_identifier
  FROM information_schema.data_type_privileges p
  JOIN information_schema.routines r
    ON r.specific_schema = p.object_schema AND r.specific_name = p.object_name
 WHERE p.object_type = 'ROUTINE' AND r.routine_name = 'isv_fn'
 ORDER BY p.dtd_identifier;

-- ============================================================================
-- element_types: what an array column holds
-- ============================================================================

-- tags is the fifth column of isv_child, so the element descriptor is a5.
-- begin-expected
-- columns: object_type,collection_type_identifier,data_type,udt_schema,udt_name,dtd_identifier
-- row: TABLE | 5 | text | pg_catalog | text | a5
-- end-expected
SELECT object_type, collection_type_identifier, data_type, udt_schema, udt_name, dtd_identifier
  FROM information_schema.element_types
 WHERE object_schema = 'isv_s' AND object_name = 'isv_child';

-- begin-expected
-- columns: collection_type_identifier,data_type,udt_name,dtd_identifier
-- row: 3 | integer | int4 | a3
-- end-expected
SELECT collection_type_identifier, data_type, udt_name, dtd_identifier
  FROM information_schema.element_types
 WHERE object_schema = 'isv_s' AND object_name = 'isv_types';

-- The join a driver makes to build an array decoder: from the ARRAY column in
-- columns to its element type, on the dtd_identifier.
-- begin-expected
-- columns: column_name,data_type,udt_name
-- row: tags | ARRAY | text
-- end-expected
SELECT c.column_name, c.data_type, e.udt_name
  FROM information_schema.columns c
  JOIN information_schema.element_types e
    ON e.object_catalog = c.table_catalog
   AND e.object_schema = c.table_schema
   AND e.object_name = c.table_name
   AND e.object_type = 'TABLE'
   AND e.collection_type_identifier = c.dtd_identifier
 WHERE c.table_schema = 'isv_s' AND c.table_name = 'isv_child';

-- ============================================================================
-- The composite type views
-- ============================================================================

-- begin-expected
-- columns: attribute_name,ordinal_position,data_type,character_maximum_length,character_octet_length,numeric_precision,numeric_precision_radix,numeric_scale,datetime_precision,attribute_udt_schema,attribute_udt_name,dtd_identifier,is_derived_reference_attribute
-- row: x | 1 | integer | NULL | NULL | 32 | 2 | 0 | NULL | pg_catalog | int4 | 1 | NO
-- row: y | 2 | character varying | 3 | 12 | NULL | NULL | NULL | NULL | pg_catalog | varchar | 2 | NO
-- row: z | 3 | timestamp without time zone | NULL | NULL | NULL | NULL | NULL | 2 | pg_catalog | timestamp | 3 | NO
-- end-expected
SELECT attribute_name, ordinal_position, data_type,
       character_maximum_length, character_octet_length,
       numeric_precision, numeric_precision_radix, numeric_scale,
       datetime_precision, attribute_udt_schema, attribute_udt_name,
       dtd_identifier, is_derived_reference_attribute
  FROM information_schema.attributes
 WHERE udt_name = 'isv_ct'
 ORDER BY ordinal_position;

-- PG answers the first columns for a composite type and leaves the rest null:
-- is_final and the ordering columns describe a DISTINCT type, which PG has none of.
-- begin-expected
-- columns: user_defined_type_schema,user_defined_type_category,is_instantiable,is_final,ordering_form,reference_type,data_type
-- row: public | STRUCTURED | YES | NULL | NULL | NULL | NULL
-- end-expected
SELECT user_defined_type_schema, user_defined_type_category, is_instantiable,
       is_final, ordering_form, reference_type, data_type
  FROM information_schema.user_defined_types
 WHERE user_defined_type_name = 'isv_ct';

-- ============================================================================
-- What type is behind a column, and which columns a domain types
-- ============================================================================

-- A domain column reports the domain's BASE type here; the domain itself is in
-- column_domain_usage.
-- begin-expected
-- columns: column_name,udt_schema,udt_name
-- row: amt | pg_catalog | numeric
-- row: cid | pg_catalog | int4
-- row: created | pg_catalog | timestamptz
-- row: flag | pg_catalog | bool
-- row: note | pg_catalog | varchar
-- row: pid | pg_catalog | int4
-- row: tags | pg_catalog | _text
-- row: ts | pg_catalog | timestamp
-- end-expected
SELECT column_name, udt_schema, udt_name
  FROM information_schema.column_udt_usage
 WHERE table_schema = 'isv_s' AND table_name = 'isv_child'
 ORDER BY column_name;

-- begin-expected
-- columns: domain_name,table_name,column_name
-- row: isv_dom | isv_child | note
-- row: isv_dnum | isv_types | c_dnum
-- row: isv_dom | isv_types | c_dom
-- end-expected
SELECT domain_name, table_name, column_name
  FROM information_schema.column_domain_usage
 WHERE domain_schema = 'isv_s'
 ORDER BY table_name, column_name;

-- begin-expected
-- columns: domain_name,udt_schema,udt_name
-- row: isv_dnum | pg_catalog | numeric
-- row: isv_dom | pg_catalog | varchar
-- end-expected
SELECT domain_name, udt_schema, udt_name
  FROM information_schema.domain_udt_usage
 WHERE domain_schema = 'isv_s'
 ORDER BY domain_name;

-- ============================================================================
-- What depends on what
-- ============================================================================

-- begin-expected
-- columns: view_name,table_schema,table_name
-- row: isv_v | isv_s | isv_parent
-- row: isv_v2 | isv_s | isv_parent
-- end-expected
SELECT view_name, table_schema, table_name
  FROM information_schema.view_table_usage
 WHERE view_schema = 'isv_s'
 ORDER BY view_name;

-- begin-expected
-- columns: view_name,table_name,column_name
-- row: isv_v | isv_parent | code
-- row: isv_v | isv_parent | id
-- row: isv_v2 | isv_parent | id
-- end-expected
SELECT view_name, table_name, column_name
  FROM information_schema.view_column_usage
 WHERE view_schema = 'isv_s'
 ORDER BY view_name, column_name;

-- The FK lives on isv_child; the view names the table it points AT. This is the
-- query that answers "which constraints depend on this table" before a DROP.
-- begin-expected
-- columns: table_schema,table_name
-- row: isv_s | isv_parent
-- end-expected
SELECT table_schema, table_name
  FROM information_schema.constraint_table_usage
 WHERE constraint_name = 'isv_child_pid_fkey';

-- PG lists PRIMARY KEY, UNIQUE and FOREIGN KEY here and nothing else — no CHECK,
-- and none of the NOT NULL constraints PG 18 synthesizes.
-- begin-expected
-- columns: constraint_name,table_name
-- row: isv_child_pid_fkey | isv_parent
-- row: isv_child_pkey | isv_child
-- row: isv_parent_code_key | isv_parent
-- row: isv_parent_pkey | isv_parent
-- end-expected
SELECT constraint_name, table_name
  FROM information_schema.constraint_table_usage
 WHERE table_schema = 'isv_s'
 ORDER BY constraint_name;

-- begin-expected
-- columns: constraint_schema,constraint_name,domain_schema,domain_name,is_deferrable,initially_deferred
-- row: isv_s | isv_dom_check | isv_s | isv_dom | NO | NO
-- end-expected
SELECT constraint_schema, constraint_name, domain_schema, domain_name,
       is_deferrable, initially_deferred
  FROM information_schema.domain_constraints
 WHERE domain_schema = 'isv_s';

-- A domain's CHECK is filed under the domain's own schema, not under public.
-- begin-expected
-- columns: check_clause
-- row: ((VALUE)::text <> ''::text)
-- end-expected
SELECT check_clause
  FROM information_schema.check_constraints
 WHERE constraint_schema = 'isv_s' AND constraint_name = 'isv_dom_check';

-- begin-expected
-- columns: trigger_name,event_object_schema,event_object_table,event_object_column
-- row: isv_trg | isv_s | isv_parent | code
-- end-expected
SELECT trigger_name, event_object_schema, event_object_table, event_object_column
  FROM information_schema.triggered_update_columns
 WHERE trigger_schema = 'isv_s';

-- ============================================================================
-- Column values that were wrong rather than absent
-- ============================================================================

-- The ceiling of an int identity is the column's own type, not the counter's.
-- begin-expected
-- columns: is_identity,identity_generation,identity_start,identity_increment,identity_maximum,identity_minimum,identity_cycle
-- row: YES | BY DEFAULT | 1 | 1 | 2147483647 | 1 | NO
-- end-expected
SELECT is_identity, identity_generation, identity_start, identity_increment,
       identity_maximum, identity_minimum, identity_cycle
  FROM information_schema.columns
 WHERE table_schema = 'isv_s' AND table_name = 'isv_child' AND column_name = 'cid';

-- identity_cycle is answered for every column, identity or not.
-- begin-expected
-- columns: is_identity,identity_generation,identity_start,identity_cycle
-- row: NO | NULL | NULL | NO
-- end-expected
SELECT is_identity, identity_generation, identity_start, identity_cycle
  FROM information_schema.columns
 WHERE table_schema = 'isv_s' AND table_name = 'isv_child' AND column_name = 'pid';

-- A bit string declares its width in bits, so it has a maximum length and no
-- octet length.
-- begin-expected
-- columns: column_name,data_type,udt_name,character_maximum_length,character_octet_length
-- row: c_bit8 | bit | bit | 8 | NULL
-- row: c_vbit | bit varying | varbit | 9 | NULL
-- end-expected
SELECT column_name, data_type, udt_name, character_maximum_length, character_octet_length
  FROM information_schema.columns
 WHERE table_schema = 'isv_s' AND table_name = 'isv_types'
   AND column_name IN ('c_bit8', 'c_vbit')
 ORDER BY column_name;

-- The typmod of a temporal column is its datetime_precision.
-- begin-expected
-- columns: column_name,data_type,datetime_precision,interval_type
-- row: c_ts0 | timestamp without time zone | 0 | NULL
-- row: c_ts3 | timestamp without time zone | 3 | NULL
-- row: c_time4 | time without time zone | 4 | NULL
-- row: c_iv | interval | 3 | DAY TO SECOND(3)
-- end-expected
SELECT column_name, data_type, datetime_precision, interval_type
  FROM information_schema.columns
 WHERE table_schema = 'isv_s' AND table_name = 'isv_types'
   AND column_name IN ('c_ts0', 'c_ts3', 'c_time4', 'c_iv')
 ORDER BY ordinal_position;

-- WITH CHECK OPTION is what stops a write through the view from disappearing.
-- begin-expected
-- columns: table_name,check_option,is_updatable,is_insertable_into
-- row: isv_v | NONE | YES | YES
-- row: isv_v2 | CASCADED | YES | YES
-- end-expected
SELECT table_name, check_option, is_updatable, is_insertable_into
  FROM information_schema.views
 WHERE table_schema = 'isv_s'
 ORDER BY table_name;

-- The trigger function is written schema-qualified.
-- begin-expected
-- columns: event_manipulation,action_statement
-- row: INSERT | EXECUTE FUNCTION isv_s.isv_trgfn()
-- row: UPDATE | EXECUTE FUNCTION isv_s.isv_trgfn()
-- end-expected
SELECT event_manipulation, action_statement
  FROM information_schema.triggers
 WHERE trigger_schema = 'isv_s'
 ORDER BY event_manipulation;

-- routine_body is SQL only for a routine whose body really is SQL, and
-- type_udt_name is the internal type name where data_type is the SQL one.
-- begin-expected
-- columns: routine_body,external_language,data_type,type_udt_schema,type_udt_name
-- row: SQL | SQL | integer | pg_catalog | int4
-- end-expected
SELECT routine_body, external_language, data_type, type_udt_schema, type_udt_name
  FROM information_schema.routines
 WHERE routine_schema = 'isv_s' AND routine_name = 'isv_fn';

-- begin-expected
-- columns: routine_body,external_language,data_type,type_udt_name
-- row: EXTERNAL | PLPGSQL | trigger | trigger
-- end-expected
SELECT routine_body, external_language, data_type, type_udt_name
  FROM information_schema.routines
 WHERE routine_schema = 'isv_s' AND routine_name = 'isv_trgfn';

-- The columns PostgreSQL has no answer for are null, not NO.
-- begin-expected
-- columns: is_null_call,is_user_defined_cast,is_implicitly_invocable,new_savepoint_level,security_type,sql_data_access,is_deterministic,parameter_style,max_dynamic_result_sets
-- row: NO | NULL | NULL | NULL | INVOKER | MODIFIES | NO | GENERAL | 0
-- end-expected
SELECT is_null_call, is_user_defined_cast, is_implicitly_invocable,
       new_savepoint_level, security_type, sql_data_access, is_deterministic,
       parameter_style, max_dynamic_result_sets
  FROM information_schema.routines
 WHERE routine_schema = 'isv_s' AND routine_name = 'isv_fn';

-- A text default carries the cast that gives it its type.
-- begin-expected
-- columns: parameter_name,ordinal_position,parameter_mode,data_type,udt_schema,udt_name,parameter_default
-- row: a | 1 | IN | integer | pg_catalog | int4 | NULL
-- row: b | 2 | IN | text | pg_catalog | text | 'x'::text
-- end-expected
SELECT p.parameter_name, p.ordinal_position, p.parameter_mode, p.data_type,
       p.udt_schema, p.udt_name, p.parameter_default
  FROM information_schema.parameters p
  JOIN information_schema.routines r
    ON r.specific_schema = p.specific_schema AND r.specific_name = p.specific_name
 WHERE r.routine_name = 'isv_fn'
 ORDER BY p.ordinal_position;

-- The public schema belongs to the pg_database_owner pseudo-role, which is what
-- a tool reads to decide whether public is the database's shared schema.
-- begin-expected
-- columns: schema_owner
-- row: pg_database_owner
-- end-expected
SELECT schema_owner FROM information_schema.schemata WHERE schema_name = 'public';

-- The database encoding is one anonymous character set with no default collation.
-- begin-expected
-- columns: character_set_catalog,character_set_schema,character_set_name,character_repertoire,form_of_use,default_collate_schema,default_collate_name
-- row: NULL | NULL | UTF8 | UCS | UTF8 | NULL | NULL
-- end-expected
SELECT character_set_catalog, character_set_schema, character_set_name,
       character_repertoire, form_of_use, default_collate_schema, default_collate_name
  FROM information_schema.character_sets;

-- begin-expected
-- columns: collation_schema,collation_name,pad_attribute
-- row: pg_catalog | C | NO PAD
-- row: pg_catalog | POSIX | NO PAD
-- row: pg_catalog | ucs_basic | NO PAD
-- row: pg_catalog | unicode | NO PAD
-- end-expected
SELECT collation_schema, collation_name, pad_attribute
  FROM information_schema.collations
 WHERE collation_name IN ('C', 'POSIX', 'ucs_basic', 'unicode')
 ORDER BY collation_name;

-- ============================================================================
-- The constant tables PostgreSQL ships
-- ============================================================================

-- begin-expected
-- columns: feature_id,feature_name,is_supported
-- row: 1 | Framework (SQL/Framework) | NO
-- row: 2 | Foundation (SQL/Foundation) | NO
-- row: 11 | Information and Definition Schema (SQL/Schemata) | NO
-- row: 16 | Property Graph Queries (SQL/PGQ) | NO
-- end-expected
SELECT feature_id, feature_name, is_supported
  FROM information_schema.sql_parts
 WHERE feature_id IN ('1', '2', '11', '16')
 ORDER BY feature_id::int;

-- begin-expected
-- columns: sizing_name,supported_value,comments
-- row: MAXIMUM IDENTIFIER LENGTH | 63 | Might be less, depending on character set.
-- end-expected
SELECT sizing_name, supported_value, comments
  FROM information_schema.sql_sizing WHERE sizing_id = 10005;

-- begin-expected
-- columns: sizing_id,sizing_name,supported_value
-- row: 100 | MAXIMUM COLUMNS IN SELECT | 1664
-- row: 101 | MAXIMUM COLUMNS IN TABLE | 1600
-- end-expected
SELECT sizing_id, sizing_name, supported_value
  FROM information_schema.sql_sizing WHERE sizing_id IN (100, 101)
 ORDER BY sizing_id;

-- begin-expected
-- columns: implementation_info_name,character_value
-- row: DBMS NAME | PostgreSQL
-- end-expected
SELECT implementation_info_name, character_value
  FROM information_schema.sql_implementation_info
 WHERE implementation_info_id = '17';

-- begin-expected
-- columns: implementation_info_name,integer_value,comments
-- row: DEFAULT TRANSACTION ISOLATION | 2 | READ COMMITTED; user-settable
-- end-expected
SELECT implementation_info_name, integer_value, comments
  FROM information_schema.sql_implementation_info
 WHERE implementation_info_id = '26';

-- ============================================================================
-- The catalog still answers the queries that join it
-- ============================================================================

-- begin-expected
-- columns: table_type,data_type,privilege_type
-- row: BASE TABLE | character varying | SELECT
-- end-expected
SELECT t.table_type, c.data_type, cp.privilege_type
  FROM information_schema.tables t
  JOIN information_schema.columns c
    ON c.table_schema = t.table_schema AND c.table_name = t.table_name
  JOIN information_schema.column_privileges cp
    ON cp.table_schema = c.table_schema AND cp.table_name = c.table_name
   AND cp.column_name = c.column_name
 WHERE t.table_schema = 'isv_s' AND t.table_name = 'isv_parent'
   AND c.column_name = 'code' AND cp.privilege_type = 'SELECT'
   AND cp.grantee = current_user;

-- begin-expected
-- columns: check_option,data_type
-- row: CASCADED | integer
-- end-expected
SELECT v.check_option, c.data_type
  FROM information_schema.views v
  JOIN information_schema.view_column_usage u
    ON u.view_schema = v.table_schema AND u.view_name = v.table_name
  JOIN information_schema.columns c
    ON c.table_schema = u.table_schema AND c.table_name = u.table_name
   AND c.column_name = u.column_name
 WHERE v.table_schema = 'isv_s' AND v.table_name = 'isv_v2';

-- ============================================================================
-- Cleanup
-- ============================================================================

DROP SCHEMA isv_s CASCADE;
DROP TYPE isv_ct CASCADE;
