-- begin-expected
-- columns: a|b|c|d
-- row: -2147483648|1|4|-2147483648
-- end-expected
SELECT 1::int4 << 31 AS a, 1 << 32 AS b, 1024 >> 40 AS c, 1 << -1 AS d;

-- begin-expected
-- columns: a|b
-- row: -32768|4611686018427387904
-- end-expected
SELECT 1::int2 << 15 AS a, 1::int8 << 62 AS b;

CREATE SEQUENCE zz_sq_s START 9223372036854775807;

-- begin-expected
-- columns: a
-- row: 9223372036854775807
-- end-expected
SELECT nextval('zz_sq_s') AS a;

-- begin-expected-error
-- sqlstate: 2200H
-- message-like: ERROR: nextval: reached maximum value of sequence "zz_sq_s" (9223372036854775807)
-- end-expected-error
SELECT nextval('zz_sq_s') AS a;

CREATE TABLE zz_sq_id (a int GENERATED BY DEFAULT AS IDENTITY, b text);

-- begin-expected
-- columns: max_value
-- row: 2147483647
-- end-expected
SELECT max_value FROM pg_sequences WHERE sequencename = 'zz_sq_id_a_seq';

-- begin-expected
-- columns: setval
-- row: 2147483647
-- end-expected
SELECT setval('zz_sq_id_a_seq', 2147483647);

-- begin-expected-error
-- sqlstate: 2200H
-- message-like: ERROR: nextval: reached maximum value of sequence "zz_sq_id_a_seq" (2147483647)
-- end-expected-error
INSERT INTO zz_sq_id (b) VALUES ('x');

-- begin-expected
-- columns: v
-- row: 9999999999
-- end-expected
SELECT * FROM xmltable('/r/x' PASSING '<r><x><v>9999999999</v></x></r>' COLUMNS v bigint PATH 'v');

CREATE TABLE zz_sq_sk (a int);

INSERT INTO zz_sq_sk VALUES (1),(2),(3),(4),(5);

-- begin-expected
-- columns: a
-- row: 3
-- row: 4
-- row: 5
-- end-expected
SELECT a FROM zz_sq_sk ORDER BY a OFFSET 2 FOR UPDATE SKIP LOCKED;

-- begin-expected-error
-- sqlstate: 22003
-- message-like: ERROR: integer out of range
-- end-expected-error
SELECT information_schema._pg_char_octet_length(1043, 2147483647);

-- begin-expected-error
-- sqlstate: 54023
-- message-like: ERROR: GROUPING must have fewer than 32 arguments
-- end-expected-error
SELECT grouping(a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a) FROM zz_sq_sk GROUP BY a;

DROP TABLE zz_sq_id, zz_sq_sk;

DROP SEQUENCE zz_sq_s;

