-- ============================================================================
-- Feature Comparison: Round 16 — Catalog completeness
-- Target: PostgreSQL 18 vs Memgres
-- ============================================================================

DROP SCHEMA IF EXISTS r16_cat CASCADE;
CREATE SCHEMA r16_cat;
SET search_path = r16_cat, public;

-- ============================================================================
-- SECTION J1: pg_class.relkind
-- ============================================================================

CREATE MATERIALIZED VIEW mv AS SELECT 1 AS v;

-- 1. Matview relkind = 'm'
-- begin-expected
-- columns: k
-- row: m
-- end-expected
SELECT relkind::text AS k FROM pg_class WHERE relname='mv'
  AND relnamespace='r16_cat'::regnamespace;

CREATE TABLE pi (id int) PARTITION BY RANGE (id);
CREATE INDEX pi_idx ON pi(id);

-- 2. Partitioned index relkind = 'I'
-- begin-expected
-- columns: k
-- row: I
-- end-expected
SELECT relkind::text AS k FROM pg_class WHERE relname='pi_idx'
  AND relnamespace='r16_cat'::regnamespace;

-- ============================================================================
-- SECTION J2: pg_class.reloptions
-- ============================================================================

CREATE TABLE ro (id int) WITH (fillfactor=70);

-- 3. reloptions contains fillfactor=70
-- begin-expected
-- columns: ok
-- row: t
-- end-expected
SELECT (reloptions::text LIKE '%fillfactor=70%') AS ok
FROM pg_class WHERE relname='ro' AND relnamespace='r16_cat'::regnamespace;

-- ============================================================================
-- SECTION J3: pg_attribute.attidentity
-- ============================================================================

CREATE TABLE ida (id int GENERATED ALWAYS AS IDENTITY);
CREATE TABLE idd (id int GENERATED BY DEFAULT AS IDENTITY);

-- 4. attidentity='a' for ALWAYS
-- begin-expected
-- columns: i
-- row: a
-- end-expected
SELECT attidentity::text AS i FROM pg_attribute
WHERE attrelid='r16_cat.ida'::regclass AND attname='id';

-- 5. attidentity='d' for BY DEFAULT
-- begin-expected
-- columns: i
-- row: d
-- end-expected
SELECT attidentity::text AS i FROM pg_attribute
WHERE attrelid='r16_cat.idd'::regclass AND attname='id';

-- ============================================================================
-- SECTION J4: pg_attribute.attcompression
-- ============================================================================

CREATE TABLE comp (t text);
ALTER TABLE comp ALTER COLUMN t SET COMPRESSION pglz;

-- 6. attcompression='p' after SET COMPRESSION pglz
-- begin-expected
-- columns: c
-- row: p
-- end-expected
SELECT attcompression::text AS c FROM pg_attribute
WHERE attrelid='r16_cat.comp'::regclass AND attname='t';

-- ============================================================================
-- SECTION J5: atthasmissing populated on ADD COLUMN ... DEFAULT const
-- ============================================================================

CREATE TABLE miss (id int);
INSERT INTO miss VALUES (1);
ALTER TABLE miss ADD COLUMN v int DEFAULT 42;

-- 7. atthasmissing=true for back-filled default
-- begin-expected
-- columns: m
-- row: t
-- end-expected
SELECT atthasmissing AS m FROM pg_attribute
WHERE attrelid='r16_cat.miss'::regclass AND attname='v';

-- ============================================================================
-- SECTION J6: pg_type.typrelid for composite
-- ============================================================================

CREATE TYPE ct AS (a int, b text);

-- 8. composite type typrelid != 0
-- begin-expected
-- columns: ok
-- row: t
-- end-expected
SELECT (typrelid::oid <> 0) AS ok FROM pg_type WHERE typname='ct';

-- ============================================================================
-- SECTION J7: pg_type.typelem for array
-- ============================================================================

-- 9. _int4.typelem = 23 (int4)
-- begin-expected
-- columns: e
-- row: 23
-- end-expected
SELECT typelem::int AS e FROM pg_type WHERE typname='_int4';

-- ============================================================================
-- SECTION J8: pg_proc column types
-- ============================================================================

-- 10. pg_proc.proargmodes declared \"char\"[]
-- begin-expected
-- columns: t
-- row: "char"[]
-- end-expected
SELECT format_type(atttypid, atttypmod) AS t FROM pg_attribute
WHERE attrelid='pg_proc'::regclass AND attname='proargmodes';

-- 11. pg_proc.proargnames declared text[]
-- begin-expected
-- columns: t
-- row: text[]
-- end-expected
SELECT format_type(atttypid, atttypmod) AS t FROM pg_attribute
WHERE attrelid='pg_proc'::regclass AND attname='proargnames';

-- ============================================================================
-- SECTION J9: pg_aggregate built-ins present
-- ============================================================================

-- 12. count() aggregate in pg_aggregate
-- begin-expected
-- columns: ok
-- row: t
-- end-expected
SELECT (count(*) >= 1) AS ok FROM pg_aggregate a
JOIN pg_proc p ON a.aggfnoid=p.oid WHERE p.proname='count';

-- 13. array_agg in pg_aggregate
-- begin-expected
-- columns: ok
-- row: t
-- end-expected
SELECT (count(*) >= 1) AS ok FROM pg_aggregate a
JOIN pg_proc p ON a.aggfnoid=p.oid WHERE p.proname='array_agg';

-- ============================================================================
-- SECTION J10: pg_operator.oprcode wired for built-ins
-- ============================================================================

-- 14. int4=int4 has non-zero oprcode
-- begin-expected
-- columns: ok
-- row: t
-- end-expected
SELECT (oprcode::oid <> 0) AS ok FROM pg_operator
WHERE oprname='=' AND oprleft=23 AND oprright=23 LIMIT 1;

-- ============================================================================
-- SECTION J11: pg_constraint.confmatchtype
-- ============================================================================

CREATE TABLE cm_p (id int PRIMARY KEY);
CREATE TABLE cm_c (pid int REFERENCES cm_p MATCH FULL);

-- 15. MATCH FULL → confmatchtype='f'
-- begin-expected
-- columns: m
-- row: f
-- end-expected
SELECT confmatchtype::text AS m FROM pg_constraint
WHERE conrelid='r16_cat.cm_c'::regclass AND contype='f';

-- ============================================================================
-- SECTION J12: pg_index.indoption + indkey type
-- ============================================================================

CREATE TABLE iopt (a int, b int);
CREATE INDEX iopt_idx ON iopt (a DESC NULLS LAST, b ASC NULLS FIRST);

-- 16. indoption contains per-column bits (1 for a, 2 for b)
-- begin-expected
-- columns: ok
-- row: t
-- end-expected
SELECT (indoption::text LIKE '%1%' AND indoption::text LIKE '%2%') AS ok
FROM pg_index WHERE indexrelid='r16_cat.iopt_idx'::regclass;

-- 17. pg_index.indkey type is int2vector
-- begin-expected
-- columns: t
-- row: int2vector
-- end-expected
SELECT format_type(atttypid, atttypmod) AS t FROM pg_attribute
WHERE attrelid='pg_index'::regclass AND attname='indkey';

-- ============================================================================
-- SECTION J13: pg_range for user range type
-- ============================================================================

CREATE TYPE myrng AS RANGE (SUBTYPE = int4);

-- 18. user range type appears in pg_range
-- begin-expected
-- columns: n
-- row: 1
-- end-expected
SELECT count(*)::int AS n FROM pg_range r
JOIN pg_type t ON r.rngtypid=t.oid WHERE t.typname='myrng';

-- ============================================================================
-- SECTION J14: pg_extension row on CREATE EXTENSION
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 19. pg_extension row for pgcrypto
-- begin-expected
-- columns: n
-- row: 1
-- end-expected
SELECT count(*)::int AS n FROM pg_extension WHERE extname='pgcrypto';

-- ============================================================================
-- SECTION J15: pg_parameter_acl exists (PG 15+)
-- ============================================================================

-- 20. pg_parameter_acl relation is present
-- begin-expected
-- columns: n
-- row: 1
-- end-expected
SELECT count(*)::int AS n FROM pg_class WHERE relname='pg_parameter_acl';

-- ============================================================================
-- SECTION J16: replication views exist
-- ============================================================================

-- 21. pg_replication_slots is queryable
-- begin-expected
-- columns: ok
-- row: t
-- end-expected
SELECT EXISTS (SELECT 1 FROM pg_class WHERE relname='pg_replication_slots') AS ok;

-- 22. pg_stat_wal_senders is queryable
-- begin-expected
-- columns: ok
-- row: f
-- end-expected
SELECT EXISTS (SELECT 1 FROM pg_class WHERE relname='pg_stat_wal_senders') AS ok;

-- ============================================================================
-- SECTION J17: information_schema.views.is_updatable
-- ============================================================================

CREATE TABLE uvt (id int);
CREATE VIEW uv AS SELECT id FROM uvt;

-- 23. Simple 1-table view is_updatable='YES'
-- begin-expected
-- columns: u
-- row: YES
-- end-expected
SELECT is_updatable AS u FROM information_schema.views
WHERE table_name='uv' AND table_schema='r16_cat';
