-- ============================================================================
-- Feature Comparison: Round 14 — Identity / generated columns
-- Target: PostgreSQL 18 vs Memgres
-- ============================================================================

DROP SCHEMA IF EXISTS r14_id CASCADE;
CREATE SCHEMA r14_id;
SET search_path = r14_id, public;

-- ============================================================================
-- SECTION A: OVERRIDING SYSTEM/USER VALUE
-- ============================================================================

CREATE TABLE r14_os (id int GENERATED ALWAYS AS IDENTITY, v text);

-- 1. Without OVERRIDING, insert into ALWAYS errors
-- begin-expected-error
-- message-like: cannot
-- end-expected-error
INSERT INTO r14_os (id, v) VALUES (100, 'a');

-- 2. OVERRIDING SYSTEM VALUE succeeds
INSERT INTO r14_os (id, v) OVERRIDING SYSTEM VALUE VALUES (100, 'b');

-- begin-expected
-- columns: id
-- row: 100
-- end-expected
SELECT id::text AS id FROM r14_os WHERE v = 'b';

CREATE TABLE r14_ou (id int GENERATED BY DEFAULT AS IDENTITY, v text);
INSERT INTO r14_ou (id, v) OVERRIDING USER VALUE VALUES (999, 'a');

-- 3. With OVERRIDING USER VALUE, user-provided 999 is discarded
-- begin-expected
-- columns: c
-- row: 0
-- end-expected
SELECT count(*)::text AS c FROM r14_ou WHERE id = 999;

-- ============================================================================
-- SECTION B: ALTER COLUMN DROP IDENTITY / SET GENERATED
-- ============================================================================

CREATE TABLE r14_di (id int GENERATED ALWAYS AS IDENTITY, v text);
ALTER TABLE r14_di ALTER COLUMN id DROP IDENTITY;
INSERT INTO r14_di (id, v) VALUES (42, 'x');

-- 4. After DROP IDENTITY, user values work
-- begin-expected
-- columns: id
-- row: 42
-- end-expected
SELECT id::text AS id FROM r14_di WHERE v = 'x';

CREATE TABLE r14_sg (id int GENERATED ALWAYS AS IDENTITY, v text);
ALTER TABLE r14_sg ALTER COLUMN id SET GENERATED BY DEFAULT;
INSERT INTO r14_sg (id, v) VALUES (7, 'a');

-- 5. After SET GENERATED BY DEFAULT, user value works without OVERRIDING
-- begin-expected
-- columns: id
-- row: 7
-- end-expected
SELECT id::text AS id FROM r14_sg WHERE v = 'a';

CREATE TABLE r14_ri (id int GENERATED BY DEFAULT AS IDENTITY, v text);
INSERT INTO r14_ri(v) VALUES ('a'), ('b');
ALTER TABLE r14_ri ALTER COLUMN id RESTART WITH 100;
INSERT INTO r14_ri(v) VALUES ('c');

-- 6. RESTART WITH takes effect on next nextval
-- begin-expected
-- columns: id
-- row: 100
-- end-expected
SELECT id::text AS id FROM r14_ri WHERE v = 'c';

-- ============================================================================
-- SECTION C: pg_sequence_last_value
-- ============================================================================

CREATE SEQUENCE r14_slv_seq;
SELECT nextval('r14_slv_seq');

-- 7. pg_sequence_last_value returns 1 after first nextval
-- begin-expected
-- columns: v
-- row: 1
-- end-expected
SELECT pg_sequence_last_value('r14_slv_seq'::regclass)::text AS v;

-- ============================================================================
-- SECTION D: VIRTUAL generated columns (PG 18)
-- ============================================================================

CREATE TABLE r14_vg (a int, b int GENERATED ALWAYS AS (a * 2) VIRTUAL);
INSERT INTO r14_vg (a) VALUES (5);

-- 8. VIRTUAL computed on read
-- begin-expected
-- columns: b
-- row: 10
-- end-expected
SELECT b::text FROM r14_vg;

-- 9. After UPDATE, VIRTUAL recomputed
UPDATE r14_vg SET a = 10;

-- begin-expected
-- columns: b
-- row: 20
-- end-expected
SELECT b::text FROM r14_vg;

-- 10. VIRTUAL cannot be indexed
-- begin-expected-error
-- message-like: virtual
-- end-expected-error
CREATE INDEX r14_vg_idx ON r14_vg (b);

-- ============================================================================
-- SECTION E: STORED recalc on UPDATE
-- ============================================================================

CREATE TABLE r14_sgc (a int, b int GENERATED ALWAYS AS (a * 2) STORED);
INSERT INTO r14_sgc (a) VALUES (5);
UPDATE r14_sgc SET a = 7;

-- 11. STORED recomputed after UPDATE
-- begin-expected
-- columns: b
-- row: 14
-- end-expected
SELECT b::text FROM r14_sgc;

-- 12. Generated column cannot reference another generated column
-- begin-expected-error
-- message-like: generation expression
-- end-expected-error
CREATE TABLE r14_gcg (
  a int,
  b int GENERATED ALWAYS AS (a * 2) STORED,
  c int GENERATED ALWAYS AS (b + 1) STORED
);

-- ============================================================================
-- SECTION F: ON DELETE SET DEFAULT (column_list) — PG 15+
-- ============================================================================

CREATE TABLE r14_sdp (id int PRIMARY KEY);
INSERT INTO r14_sdp VALUES (1), (99);
CREATE TABLE r14_sdc (pid int DEFAULT 99 REFERENCES r14_sdp(id) ON DELETE SET DEFAULT (pid));
INSERT INTO r14_sdc VALUES (1);
DELETE FROM r14_sdp WHERE id = 1;

-- 13. pid reset to default 99
-- begin-expected
-- columns: pid
-- row: 99
-- end-expected
SELECT pid::text AS pid FROM r14_sdc;
