-- ============================================================================
-- What the DEFAULT keyword resolves to, and where it may stand
--
-- DEFAULT assigned to a column is the one thing that may be written to a
-- GENERATED ALWAYS identity, it draws from a serial's sequence, it falls back
-- to the DOMAIN default of the column's type, and through a view it is the
-- VIEW's own column default -- not the base relation's. Written anywhere else
-- than as the whole value of a VALUES item or of a SET clause it is refused
-- while the statement is analysed, so an empty relation is refused exactly as
-- a full one is.
--
-- Every value was measured against PostgreSQL 18.
-- ============================================================================

-- ============================================================================
-- An identity column takes the next sequence value
-- ============================================================================

CREATE TABLE wdk_id (id int, c int GENERATED ALWAYS AS IDENTITY, d int GENERATED BY DEFAULT AS IDENTITY);
INSERT INTO wdk_id (id) VALUES (1);

-- begin-expected
-- columns: id | c | d
-- row: 1 | 1 | 1
-- end-expected
SELECT id, c, d FROM wdk_id;

UPDATE wdk_id SET c = DEFAULT;

-- begin-expected
-- columns: id | c | d
-- row: 1 | 2 | 1
-- end-expected
SELECT id, c, d FROM wdk_id;

UPDATE wdk_id SET d = DEFAULT;

-- begin-expected
-- columns: id | c | d
-- row: 1 | 2 | 2
-- end-expected
SELECT id, c, d FROM wdk_id;

UPDATE wdk_id SET c = DEFAULT, d = DEFAULT;

-- begin-expected
-- columns: id | c | d
-- row: 1 | 3 | 3
-- end-expected
SELECT id, c, d FROM wdk_id;

DROP TABLE wdk_id;

-- a serial column draws from its own sequence the same way
CREATE TABLE wdk_ser (id serial, v int);
INSERT INTO wdk_ser (v) VALUES (10);
UPDATE wdk_ser SET id = DEFAULT;

-- begin-expected
-- columns: id | v
-- row: 2 | 10
-- end-expected
SELECT id, v FROM wdk_ser;

DROP TABLE wdk_ser;

-- ============================================================================
-- The column's own default wins; the type's domain default stands behind it
-- ============================================================================

CREATE DOMAIN wdk_dm AS int DEFAULT 42;
CREATE TABLE wdk_dt (id int, v wdk_dm, w wdk_dm DEFAULT 7);
INSERT INTO wdk_dt (id,v,w) VALUES (1,1,1);
UPDATE wdk_dt SET v = DEFAULT, w = DEFAULT;

-- begin-expected
-- columns: id | v | w
-- row: 1 | 42 | 7
-- end-expected
SELECT id, v, w FROM wdk_dt;

INSERT INTO wdk_dt (id) VALUES (2);

-- begin-expected
-- columns: id | v | w
-- row: 1 | 42 | 7
-- row: 2 | 42 | 7
-- end-expected
SELECT id, v, w FROM wdk_dt ORDER BY id;

-- the MERGE arm that inserts reads the domain default too
CREATE TABLE wdk_mg (id int PRIMARY KEY, v wdk_dm);
CREATE TABLE wdk_ms (id int);
INSERT INTO wdk_ms VALUES (1),(2);
MERGE INTO wdk_mg t USING wdk_ms s ON t.id = s.id WHEN NOT MATCHED THEN INSERT (id, v) VALUES (s.id, DEFAULT);

-- begin-expected
-- columns: id | v
-- row: 1 | 42
-- row: 2 | 42
-- end-expected
SELECT id, v FROM wdk_mg ORDER BY id;

-- and so does the NEW row a rule on an INSERT is handed
CREATE TABLE wdk_il (v int);
CREATE TABLE wdk_it (id int, v wdk_dm);
CREATE RULE wdk_ir AS ON INSERT TO wdk_it DO ALSO INSERT INTO wdk_il VALUES (NEW.v);
INSERT INTO wdk_it (id) VALUES (1);
INSERT INTO wdk_it (id, v) VALUES (2, DEFAULT);

-- begin-expected
-- columns: id | v
-- row: 1 | 42
-- row: 2 | 42
-- end-expected
SELECT id, v FROM wdk_it ORDER BY id;

-- begin-expected
-- columns: v
-- row: 42
-- row: 42
-- end-expected
SELECT v FROM wdk_il ORDER BY v;

DROP TABLE wdk_it CASCADE;
DROP TABLE wdk_il;
DROP TABLE wdk_mg;
DROP TABLE wdk_ms;
DROP TABLE wdk_dt;
DROP DOMAIN wdk_dm;

-- ============================================================================
-- ON CONFLICT DO UPDATE SET col = DEFAULT is an UPDATE
-- ============================================================================

CREATE DOMAIN wdk_dm2 AS int DEFAULT 42;
CREATE TABLE wdk_oc (id int PRIMARY KEY, v wdk_dm2, c int GENERATED BY DEFAULT AS IDENTITY);
INSERT INTO wdk_oc (id, v) VALUES (1, 5);

-- begin-expected
-- columns: id | v | c
-- row: 1 | 5 | 1
-- end-expected
SELECT id, v, c FROM wdk_oc;

INSERT INTO wdk_oc (id, v) VALUES (1, 9) ON CONFLICT (id) DO UPDATE SET v = DEFAULT;

-- begin-expected
-- columns: id | v | c
-- row: 1 | 42 | 1
-- end-expected
SELECT id, v, c FROM wdk_oc;

-- c reaches 4: each conflicting INSERT attempt drew an identity value of its own
-- before the conflict was found, and the assignment then drew a third
INSERT INTO wdk_oc (id, v) VALUES (1, 9) ON CONFLICT (id) DO UPDATE SET c = DEFAULT;

-- begin-expected
-- columns: id | v | c
-- row: 1 | 42 | 4
-- end-expected
SELECT id, v, c FROM wdk_oc;

DROP TABLE wdk_oc;
DROP DOMAIN wdk_dm2;

-- ============================================================================
-- Through a view, an assignment of DEFAULT asks the VIEW
-- ============================================================================

CREATE TABLE wdk_vt (id int, a text DEFAULT 'BASE');
INSERT INTO wdk_vt VALUES (1,'o');
CREATE VIEW wdk_vv AS SELECT * FROM wdk_vt;

-- the view declares no default of its own, so the assignment writes NULL:
-- the base relation's default is NOT a fallback for an UPDATE
UPDATE wdk_vv SET a = DEFAULT;

-- begin-expected
-- columns: id | a
-- row: 1 | NULL
-- end-expected
SELECT id, a FROM wdk_vt;

ALTER VIEW wdk_vv ALTER COLUMN a SET DEFAULT 'VIEWD';
UPDATE wdk_vv SET a = DEFAULT;

-- begin-expected
-- columns: id | a
-- row: 1 | VIEWD
-- end-expected
SELECT id, a FROM wdk_vt;

INSERT INTO wdk_vv (id,a) VALUES (2,DEFAULT);

-- begin-expected
-- columns: id | a
-- row: 1 | VIEWD
-- row: 2 | VIEWD
-- end-expected
SELECT id, a FROM wdk_vt ORDER BY id;

DROP VIEW wdk_vv;
DROP TABLE wdk_vt;

-- an INSERT is different: after the rewrite it asks the base relation for the
-- defaults of columns the view left it none for
CREATE TABLE wdk_ivt (id int, a text DEFAULT 'BASE');
CREATE VIEW wdk_ivv AS SELECT * FROM wdk_ivt;
INSERT INTO wdk_ivv (id,a) VALUES (2,DEFAULT);
INSERT INTO wdk_ivv (id) VALUES (3);

-- begin-expected
-- columns: id | a
-- row: 2 | BASE
-- row: 3 | BASE
-- end-expected
SELECT id, a FROM wdk_ivt ORDER BY id;

DROP VIEW wdk_ivv;
DROP TABLE wdk_ivt;

-- a domain default still stands behind a view column
CREATE DOMAIN wdk_dm3 AS int DEFAULT 42;
CREATE TABLE wdk_vd (id int, v wdk_dm3);
INSERT INTO wdk_vd VALUES (1,5);
CREATE VIEW wdk_vdv AS SELECT * FROM wdk_vd;
UPDATE wdk_vdv SET v = DEFAULT;

-- begin-expected
-- columns: id | v
-- row: 1 | 42
-- end-expected
SELECT id, v FROM wdk_vd;

DROP VIEW wdk_vdv;
DROP TABLE wdk_vd;

-- an identity sequence does not
CREATE TABLE wdk_vi (id int, c int GENERATED BY DEFAULT AS IDENTITY);
INSERT INTO wdk_vi (id) VALUES (1);
CREATE VIEW wdk_viv AS SELECT * FROM wdk_vi;

-- begin-expected-error
-- sqlstate: 23502
-- message-like: null value in column "c" of relation "wdk_vi" violates not-null constraint
-- end-expected-error
UPDATE wdk_viv SET c = DEFAULT;

-- begin-expected
-- columns: id | c
-- row: 1 | 1
-- end-expected
SELECT id, c FROM wdk_vi;

DROP VIEW wdk_viv;
DROP TABLE wdk_vi;

-- a BEFORE trigger on the base relation is handed the value the view resolved
CREATE TABLE wdk_tlog (v text);
CREATE TABLE wdk_tvt (id int, a text DEFAULT 'BASE');
INSERT INTO wdk_tvt VALUES (1,'o');
CREATE VIEW wdk_tvv AS SELECT * FROM wdk_tvt;
ALTER VIEW wdk_tvv ALTER COLUMN a SET DEFAULT 'VIEWD';
CREATE FUNCTION wdk_tf() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN INSERT INTO wdk_tlog VALUES (coalesce(NEW.a,'<null>')); RETURN NEW; END $$;
CREATE TRIGGER wdk_tg BEFORE UPDATE ON wdk_tvt FOR EACH ROW EXECUTE FUNCTION wdk_tf();
UPDATE wdk_tvv SET a = DEFAULT;

-- begin-expected
-- columns: id | a
-- row: 1 | VIEWD
-- end-expected
SELECT id, a FROM wdk_tvt;

-- begin-expected
-- columns: v
-- row: VIEWD
-- end-expected
SELECT v FROM wdk_tlog;

DROP TRIGGER wdk_tg ON wdk_tvt;
DROP FUNCTION wdk_tf();
DROP VIEW wdk_tvv;
DROP TABLE wdk_tvt;
DROP TABLE wdk_tlog;
DROP DOMAIN wdk_dm3;

-- ============================================================================
-- A relation carrying a rule reads the default the statement would write
-- ============================================================================

CREATE TABLE wdk_rl1 (v text);
CREATE TABLE wdk_rt1 (id int, a text DEFAULT 'DD');
INSERT INTO wdk_rt1 VALUES (1,'o'),(2,'p');
CREATE RULE wdk_rr1 AS ON UPDATE TO wdk_rt1 DO ALSO INSERT INTO wdk_rl1 VALUES (NEW.a);
UPDATE wdk_rt1 SET a = DEFAULT;

-- begin-expected
-- columns: id | a
-- row: 1 | DD
-- row: 2 | DD
-- end-expected
SELECT id, a FROM wdk_rt1 ORDER BY id;

-- NEW.a carries the default, once per row
-- begin-expected
-- columns: v
-- row: DD
-- row: DD
-- end-expected
SELECT v FROM wdk_rl1;

DROP TABLE wdk_rt1 CASCADE;
DROP TABLE wdk_rl1;

-- DO INSTEAD reads it the same way and the statement itself writes nothing
CREATE TABLE wdk_rl2 (v text);
CREATE TABLE wdk_rt2 (id int, a text DEFAULT 'EE');
INSERT INTO wdk_rt2 VALUES (1,'o');
CREATE RULE wdk_rr2 AS ON UPDATE TO wdk_rt2 DO INSTEAD INSERT INTO wdk_rl2 VALUES (NEW.a);
UPDATE wdk_rt2 SET a = DEFAULT;

-- begin-expected
-- columns: id | a
-- row: 1 | o
-- end-expected
SELECT id, a FROM wdk_rt2;

-- begin-expected
-- columns: v
-- row: EE
-- end-expected
SELECT v FROM wdk_rl2;

DROP TABLE wdk_rt2 CASCADE;
DROP TABLE wdk_rl2;

-- a default that draws from a sequence is drawn AGAIN for the rule's own
-- query, and the rule's query runs first
CREATE TABLE wdk_rl3 (v int);
CREATE TABLE wdk_rt3 (id int, s serial);
INSERT INTO wdk_rt3 (id) VALUES (1),(2);
CREATE RULE wdk_rr3 AS ON UPDATE TO wdk_rt3 DO ALSO INSERT INTO wdk_rl3 VALUES (NEW.s);
UPDATE wdk_rt3 SET s = DEFAULT;

-- begin-expected
-- columns: id | s
-- row: 1 | 5
-- row: 2 | 6
-- end-expected
SELECT id, s FROM wdk_rt3 ORDER BY id;

-- begin-expected
-- columns: v
-- row: 3
-- row: 4
-- end-expected
SELECT v FROM wdk_rl3 ORDER BY v;

-- begin-expected
-- columns: last_value
-- row: 6
-- end-expected
SELECT last_value FROM wdk_rt3_s_seq;

DROP TABLE wdk_rt3 CASCADE;
DROP TABLE wdk_rl3;

-- ============================================================================
-- A misplaced DEFAULT is refused while the statement is analysed, so an empty
-- relation is refused exactly as a full one is
-- ============================================================================

CREATE TABLE wdk_dz (a text DEFAULT 'D', b int);

-- begin-expected
-- columns: count
-- row: 0
-- end-expected
SELECT count(*) FROM wdk_dz;

-- begin-expected-error
-- sqlstate: 42601
-- message-like: DEFAULT is not allowed in this context
-- end-expected-error
UPDATE wdk_dz SET a = DEFAULT || 'x';

-- begin-expected-error
-- sqlstate: 42601
-- message-like: DEFAULT is not allowed in this context
-- end-expected-error
UPDATE wdk_dz SET a = 'q' WHERE b = DEFAULT;

-- begin-expected-error
-- sqlstate: 42601
-- message-like: DEFAULT is not allowed in this context
-- end-expected-error
SELECT a FROM wdk_dz WHERE a = DEFAULT;

-- begin-expected-error
-- sqlstate: 42601
-- message-like: DEFAULT is not allowed in this context
-- end-expected-error
DELETE FROM wdk_dz WHERE b = DEFAULT;

-- begin-expected-error
-- sqlstate: 42601
-- message-like: DEFAULT is not allowed in this context
-- end-expected-error
INSERT INTO wdk_dz (a,b) SELECT DEFAULT, b FROM wdk_dz;

-- begin-expected-error
-- sqlstate: 42601
-- message-like: DEFAULT is not allowed in this context
-- end-expected-error
INSERT INTO wdk_dz (a,b) VALUES (DEFAULT || 'y', 1);

-- begin-expected-error
-- sqlstate: 42601
-- message-like: DEFAULT is not allowed in this context
-- end-expected-error
VALUES (DEFAULT);

-- an ORDER BY item is not a place for it either, and the complaint is this one
-- begin-expected-error
-- sqlstate: 42601
-- message-like: DEFAULT is not allowed in this context
-- end-expected-error
SELECT * FROM wdk_dz ORDER BY DEFAULT;

-- begin-expected-error
-- sqlstate: 42601
-- message-like: DEFAULT is not allowed in this context
-- end-expected-error
UPDATE wdk_dz SET a = CASE WHEN true THEN DEFAULT ELSE 'x' END;

-- begin-expected-error
-- sqlstate: 42601
-- message-like: DEFAULT is not allowed in this context
-- end-expected-error
SELECT DEFAULT;

-- begin-expected-error
-- sqlstate: 42601
-- message-like: DEFAULT is not allowed in this context
-- end-expected-error
INSERT INTO wdk_dz (a,b) VALUES ((SELECT DEFAULT), 1);

-- a relation the statement cannot open is reported first: the range table is
-- built before the statement's expressions are analysed
-- begin-expected-error
-- sqlstate: 42P01
-- message-like: relation "wdk_dnosuch" does not exist
-- end-expected-error
UPDATE wdk_dnosuch SET a = DEFAULT || 'x';

-- begin-expected-error
-- sqlstate: 42P01
-- message-like: relation "wdk_nosuch" does not exist
-- end-expected-error
SELECT DEFAULT FROM wdk_nosuch;

-- ============================================================================
-- The legal placements still work, and parentheses do not move the keyword
-- ============================================================================

INSERT INTO wdk_dz (a,b) VALUES ((DEFAULT), 1);
UPDATE wdk_dz SET a = (DEFAULT);
INSERT INTO wdk_dz (a,b) VALUES (DEFAULT,2);
UPDATE wdk_dz SET (a,b) = (DEFAULT, 3);

-- begin-expected
-- columns: a | b
-- row: D | 3
-- row: D | 3
-- end-expected
SELECT a, b FROM wdk_dz ORDER BY a, b;

CREATE TABLE wdk_c (a int PRIMARY KEY, b text DEFAULT 'q');
INSERT INTO wdk_c VALUES (1,'x');

-- begin-expected-error
-- sqlstate: 42601
-- message-like: DEFAULT is not allowed in this context
-- end-expected-error
INSERT INTO wdk_c (a,b) VALUES (1,'y') ON CONFLICT (a) DO UPDATE SET b = DEFAULT || 'z';

-- begin-expected-error
-- sqlstate: 42601
-- message-like: DEFAULT is not allowed in this context
-- end-expected-error
MERGE INTO wdk_c t USING (SELECT 9 AS k) s ON t.a = s.k WHEN MATCHED THEN UPDATE SET b = DEFAULT || 'w';

INSERT INTO wdk_c (a,b) VALUES (1,'y') ON CONFLICT (a) DO UPDATE SET b = DEFAULT;

-- begin-expected
-- columns: a | b
-- row: 1 | q
-- end-expected
SELECT a, b FROM wdk_c ORDER BY a;

MERGE INTO wdk_c t USING (SELECT 9 AS k) s ON t.a = s.k WHEN NOT MATCHED THEN INSERT (a,b) VALUES (s.k, DEFAULT);

-- begin-expected
-- columns: a | b
-- row: 1 | q
-- row: 9 | q
-- end-expected
SELECT a, b FROM wdk_c ORDER BY a;

MERGE INTO wdk_c t USING (SELECT 9 AS k) s ON t.a = s.k WHEN MATCHED THEN UPDATE SET b = DEFAULT;

-- begin-expected
-- columns: a | b
-- row: 1 | q
-- row: 9 | q
-- end-expected
SELECT a, b FROM wdk_c ORDER BY a;

-- INSERT ... DEFAULT VALUES and a data-modifying WITH item are untouched by
-- the check
CREATE TABLE wdk_dv (id int, a text DEFAULT 'CD');
INSERT INTO wdk_dv VALUES (1,'o'),(2,'p');

-- begin-expected
-- columns: count
-- row: 1
-- end-expected
WITH w AS (UPDATE wdk_dv SET a = DEFAULT WHERE id = 1 RETURNING id) SELECT count(*) FROM w;

-- begin-expected
-- columns: id | a
-- row: 1 | CD
-- row: 2 | p
-- end-expected
SELECT id, a FROM wdk_dv ORDER BY id;

INSERT INTO wdk_dv DEFAULT VALUES;

-- begin-expected
-- columns: count
-- row: 3
-- end-expected
SELECT count(*) FROM wdk_dv;

SET datestyle = DEFAULT;

DROP TABLE wdk_dv;
DROP TABLE wdk_c;
DROP TABLE wdk_dz;

-- ============================================================================
-- An integrity-constraint violation carries no parse location; a value the
-- parser had to coerce does
-- ============================================================================

CREATE TABLE wdk_pz (a int NOT NULL DEFAULT 3, b int NOT NULL,
                     c int GENERATED ALWAYS AS IDENTITY,
                     d int GENERATED ALWAYS AS (a*2) STORED);

-- begin-expected-error
-- sqlstate: 23502
-- message-like: null value in column "b" of relation "wdk_pz" violates not-null constraint
-- end-expected-error
INSERT INTO wdk_pz (a,b) VALUES (1, NULL);

-- begin-expected-error
-- sqlstate: 428C9
-- message-like: cannot insert a non-DEFAULT value into column "c"
-- end-expected-error
INSERT INTO wdk_pz (a,b,c) VALUES (1, 2, 5);

-- begin-expected-error
-- sqlstate: 428C9
-- message-like: cannot insert a non-DEFAULT value into column "d"
-- end-expected-error
INSERT INTO wdk_pz (a,b,d) VALUES (1, 2, 5);

INSERT INTO wdk_pz (a,b) VALUES (1, 2);

-- begin-expected-error
-- sqlstate: 428C9
-- message-like: column "c" can only be updated to DEFAULT
-- end-expected-error
UPDATE wdk_pz SET c = 9;

-- begin-expected-error
-- sqlstate: 428C9
-- message-like: column "d" can only be updated to DEFAULT
-- end-expected-error
UPDATE wdk_pz SET d = 9;

-- begin-expected-error
-- sqlstate: 23502
-- message-like: null value in column "b" of relation "wdk_pz" violates not-null constraint
-- end-expected-error
UPDATE wdk_pz SET b = NULL;

CREATE TABLE wdk_pa (k int PRIMARY KEY, q int CHECK (q < 100));
INSERT INTO wdk_pa VALUES (1, 1);

-- begin-expected-error
-- sqlstate: 23505
-- message-like: duplicate key value violates unique constraint "wdk_pa_pkey"
-- end-expected-error
INSERT INTO wdk_pa VALUES (1, 1);

-- begin-expected-error
-- sqlstate: 23514
-- message-like: new row for relation "wdk_pa" violates check constraint "wdk_pa_q_check"
-- end-expected-error
INSERT INTO wdk_pa VALUES (2, 500);

CREATE TABLE wdk_chi (j int REFERENCES wdk_pa(k));

-- begin-expected-error
-- sqlstate: 23503
-- message-like: insert or update on table "wdk_chi" violates foreign key constraint
-- end-expected-error
INSERT INTO wdk_chi VALUES (77);

INSERT INTO wdk_chi VALUES (1);

-- begin-expected-error
-- sqlstate: 23503
-- message-like: update or delete on table "wdk_pa" violates foreign key constraint
-- end-expected-error
DELETE FROM wdk_pa WHERE k = 1;

CREATE TABLE wdk_nn (b int);
INSERT INTO wdk_nn VALUES (NULL);

-- begin-expected-error
-- sqlstate: 23502
-- message-like: column "b" of relation "wdk_nn" contains null values
-- end-expected-error
ALTER TABLE wdk_nn ALTER COLUMN b SET NOT NULL;

CREATE TABLE wdk_ck (b int);
INSERT INTO wdk_ck VALUES (500);

-- begin-expected-error
-- sqlstate: 23514
-- message-like: check constraint "wdk_ckc" of relation "wdk_ck" is violated by some row
-- end-expected-error
ALTER TABLE wdk_ck ADD CONSTRAINT wdk_ckc CHECK (b < 100);

-- class 22 keeps its place in the text
-- begin-expected-error
-- sqlstate: 22P02
-- message-like: invalid input syntax for type integer: "x"
-- end-expected-error
SELECT 'x'::int;

-- begin-expected-error
-- sqlstate: 22008
-- message-like: date/time field value out of range: "2020-13-01"
-- end-expected-error
SELECT CAST('2020-13-01' AS date);

DROP TABLE wdk_ck;
DROP TABLE wdk_nn;
DROP TABLE wdk_chi;
DROP TABLE wdk_pa;
DROP TABLE wdk_pz;
