\pset pager off
\pset format unaligned
\pset tuples_only off
\pset null <NULL>
\set VERBOSITY verbose
\set SHOW_CONTEXT always
\set ON_ERROR_STOP off

DROP SCHEMA IF EXISTS compat CASCADE;
CREATE SCHEMA compat;
SET search_path = compat, pg_catalog;
SET client_min_messages = notice;
SET extra_float_digits = 0;
SET DateStyle = 'ISO, YMD';
SET IntervalStyle = 'postgres';
SET TimeZone = 'UTC';

SELECT current_schema() AS current_schema,
       current_setting('TimeZone') AS timezone,
       current_setting('DateStyle') AS datestyle,
       current_setting('IntervalStyle') AS intervalstyle;

CREATE TABLE base(
  id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  a int NOT NULL,
  b text DEFAULT 'd',
  c int GENERATED ALWAYS AS (a * 10) STORED
);

INSERT INTO base(a, b) VALUES (1, 'x'), (2, 'y');

-- automatically updatable views
CREATE VIEW v_simple AS
SELECT id, a, b FROM base
WHERE a > 0
WITH LOCAL CHECK OPTION;

SELECT * FROM v_simple ORDER BY id;
INSERT INTO v_simple(a, b) VALUES (3, 'z');
UPDATE v_simple SET a = 4, b = 'zz' WHERE b = 'z';
DELETE FROM v_simple WHERE b = 'y';
SELECT * FROM base ORDER BY id;

-- nested views and check option
CREATE VIEW v_nested AS
SELECT * FROM v_simple
WHERE a >= 2
WITH CASCADED CHECK OPTION;

SELECT * FROM v_nested ORDER BY id;
INSERT INTO v_nested(a, b) VALUES (5, 'vv');
UPDATE v_nested SET a = 6 WHERE b = 'vv';
SELECT * FROM base ORDER BY id;

-- defaults / identity nuances
INSERT INTO base(a) VALUES (7) RETURNING *;
INSERT INTO base(id, a, b) OVERRIDING SYSTEM VALUE VALUES (100, 8, 'sys') RETURNING *;
INSERT INTO base(id, a, b) OVERRIDING USER VALUE VALUES (200, 9, 'usr') RETURNING *;

ALTER TABLE base ALTER COLUMN id SET GENERATED BY DEFAULT;
INSERT INTO base(id, a, b) VALUES (300, 10, 'manual') RETURNING *;
ALTER TABLE base ALTER COLUMN id SET GENERATED ALWAYS;

ALTER TABLE base ADD COLUMN d int DEFAULT 42;
ALTER TABLE base ALTER COLUMN d SET DEFAULT 99;
INSERT INTO base(a, b) VALUES (11, 'dd') RETURNING id, a, b, d;
ALTER TABLE base ALTER COLUMN d DROP DEFAULT;

-- generated-column errors/behavior
SELECT id, a, b, c, d FROM base ORDER BY id;

-- bad updatable view / identity / generated cases
INSERT INTO v_simple(id, a, b) VALUES (999, 12, 'bad');
INSERT INTO v_simple(a, b) VALUES (-1, 'fails_check');
UPDATE v_nested SET a = 1 WHERE b = 'vv';
UPDATE base SET c = 123 WHERE id = 1;
INSERT INTO base(id, a, b, c) VALUES (400, 12, 'bad', 999);
INSERT INTO base(id, a, b) VALUES (401, 12, 'bad_always');
ALTER TABLE base ADD COLUMN e int GENERATED ALWAYS AS (no_such_col * 2) STORED;
ALTER TABLE base ALTER COLUMN a ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE base ALTER COLUMN id DROP IDENTITY;
ALTER TABLE base ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
CREATE VIEW v_join AS
SELECT b1.id, b1.a, b2.b
FROM base b1
JOIN base b2 ON b1.id = b2.id;
INSERT INTO v_join VALUES (1, 1, 'x');

DROP SCHEMA compat CASCADE;
