\pset pager off
\pset format unaligned
\pset tuples_only off
\pset null <NULL>
\set VERBOSITY verbose
\set SHOW_CONTEXT always
\set ON_ERROR_STOP off

DROP SCHEMA IF EXISTS compat CASCADE;
CREATE SCHEMA compat;
SET search_path = compat, pg_catalog;
SET client_min_messages = notice;
SET extra_float_digits = 0;
SET DateStyle = 'ISO, YMD';
SET IntervalStyle = 'postgres';
SET TimeZone = 'UTC';

SELECT current_schema() AS current_schema,
       current_setting('TimeZone') AS timezone,
       current_setting('DateStyle') AS datestyle,
       current_setting('IntervalStyle') AS intervalstyle;

CREATE TABLE p(a int, b text);

-- clause-order and delimiter stress
SELECT a b FROM p;
SELECT a, FROM p;
SELECT FROM p WHERE a = 1;
SELECT * FROM p WHERE a = 1 ORDER BY b GROUP BY a;
SELECT * FROM p GROUP BY a WHERE a = 1;
SELECT * FROM p HAVING a = 1 GROUP BY a;
SELECT * FROM p LIMIT 1 ORDER BY a;
SELECT * FROM p OFFSET 1 LIMIT;
SELECT * FROM p FETCH FIRST 1 ROW ONLY OFFSET 1;
SELECT DISTINCT DISTINCT a FROM p;
SELECT ALL DISTINCT a FROM p;

INSERT INTO p VALUES (1, 'x');
INSERT INTO p (a b) VALUES (1, 'x');
INSERT INTO p VALUES (1 'x');
INSERT INTO p SELECT FROM p;
INSERT INTO p DEFAULT VALUES VALUES;
INSERT INTO p OVERRIDING SYSTEM VALUE DEFAULT VALUES;
INSERT INTO p RETURNING;

UPDATE p SET a = 1 b = 'x';
UPDATE p SET (a, b) = (1, 'x', 'y');
UPDATE p SET a = DEFAULT WHERE RETURNING a;
UPDATE p FROM p SET a = 1;
UPDATE ONLY p, p2 SET a = 1;

DELETE FROM p WHERE USING p;
DELETE FROM p USING p WHERE RETURNING a;
DELETE ONLY FROM p WHERE a = 1;

MERGE INTO p USING p s ON p.a = s.a WHEN THEN UPDATE SET a = 1;
MERGE INTO p USING p s ON p.a = s.a WHEN MATCHED UPDATE SET a = 1;
MERGE INTO p USING p s ON p.a = s.a WHEN NOT MATCHED THEN INSERT VALUES ();
MERGE INTO p USING p s ON p.a = s.a RETURNING *;

WITH w AS (SELECT 1) INSERT INTO p VALUES (1, 'x') RETURNING;
WITH RECURSIVE w AS (SELECT 1 UNION ALL) SELECT * FROM w;
WITH w AS MATERIALIZED SELECT 1;
WITH w AS (SELECT 1) SEARCH DEPTH FIRST BY a SET ord SELECT * FROM w;

CREATE TABLE q (a int,) ;
CREATE TABLE q2 (a int b text);
CREATE TABLE q3 (LIKE p INCLUDING);
CREATE TABLE q4 PARTITION BY RANGE (a);
CREATE VIEW vv AS SELECT ;
CREATE VIEW vv2 AS SELECT * FROM p WITH CHECK;
CREATE MATERIALIZED VIEW mv AS WITH DATA SELECT 1;
CREATE INDEX idx ON p USING (a);
CREATE INDEX idx2 ON p (a WHERE a > 1);
CREATE UNIQUE INDEX idx3 ON p ();
CREATE TRIGGER tr AFTER ON p FOR EACH ROW EXECUTE FUNCTION now();
CREATE RULE r AS ON TO p DO INSTEAD NOTHING;

ALTER TABLE p ALTER a TYPE int;
ALTER TABLE p ADD COLUMN c int DEFAULT;
ALTER TABLE p RENAME a TO b;
ALTER TABLE p ADD CONSTRAINT c CHECK a > 0;
ALTER TABLE p DROP CONSTRAINT;
ALTER TABLE p ATTACH PARTITION p FOR VALUES FROM (1) TO;
ALTER TABLE p ALTER COLUMN a SET GENERATED ALWAYS;

CREATE FUNCTION f(a int DEFAULT) RETURNS int LANGUAGE SQL AS $$ SELECT 1 $$;
CREATE FUNCTION f2(a int, b text DEFAULT 'x',) RETURNS int LANGUAGE SQL AS $$ SELECT 1 $$;
CREATE PROCEDURE proc(a int AS $$ SELECT 1 $$ LANGUAGE SQL;
DO LANGUAGE plpgsql $$ BEGIN END $$;

PREPARE stmt AS SELECT $;
PREPARE stmt2(int,) AS SELECT 1;
EXECUTE stmt(,);
DEALLOCATE PREPARE stmt;

SELECT ARRAY[];
SELECT ARRAY[1,2,];
SELECT ROW();
SELECT ROW(,1);
SELECT (ROW(1,2)).;
SELECT CAST(1 AS);
SELECT OPERATOR(pg_catalog.+)();
SELECT OPERATOR(pg_catalog.+)(1,);
SELECT COLLATE "C";
SELECT a COLLATE FROM p;
SELECT * FROM generate_series() WITH ORDINALITY AS;
SELECT * FROM ROWS FROM (generate_series(1,2),) AS x(a,b);

SELECT xmlparse( '<x/>' );
SELECT to_tsquery('english', );
SELECT format('%', 'x');

DROP SCHEMA compat CASCADE;
