\pset pager off
\pset format unaligned
\pset tuples_only off
\pset null <NULL>
\set VERBOSITY verbose
\set SHOW_CONTEXT always
\set ON_ERROR_STOP off

DROP SCHEMA IF EXISTS compat CASCADE;
CREATE SCHEMA compat;
SET search_path = compat, pg_catalog;
SET client_min_messages = notice;
SET extra_float_digits = 0;
SET DateStyle = 'ISO, YMD';
SET IntervalStyle = 'postgres';
SET TimeZone = 'UTC';

SELECT current_schema() AS current_schema,
       current_setting('TimeZone') AS timezone,
       current_setting('DateStyle') AS datestyle,
       current_setting('IntervalStyle') AS intervalstyle;

CREATE TABLE upsert_t(
  id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  code text UNIQUE,
  note text DEFAULT 'd',
  updated_at timestamptz DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO upsert_t(code, note) VALUES
('A', 'a1'),
('B', 'b1')
RETURNING id, code, note, updated_at;

-- returning / generated-key shaped cases
INSERT INTO upsert_t(code) VALUES ('C') RETURNING *;
INSERT INTO upsert_t(id, code, note) OVERRIDING SYSTEM VALUE
VALUES (100, 'SYS', 'sys') RETURNING *;
ALTER TABLE upsert_t ALTER COLUMN id SET GENERATED BY DEFAULT;
INSERT INTO upsert_t(id, code, note) VALUES (200, 'MAN', 'manual') RETURNING *;
ALTER TABLE upsert_t ALTER COLUMN id SET GENERATED ALWAYS;

-- ON CONFLICT coverage
INSERT INTO upsert_t(code, note)
VALUES ('A', 'a2')
ON CONFLICT (code) DO NOTHING
RETURNING *;

INSERT INTO upsert_t(code, note)
VALUES ('A', 'a3')
ON CONFLICT (code) DO UPDATE
SET note = EXCLUDED.note,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, code, note, updated_at;

INSERT INTO upsert_t(code, note)
VALUES ('B', 'b2')
ON CONFLICT ON CONSTRAINT upsert_t_code_key DO UPDATE
SET note = EXCLUDED.note
RETURNING *;

INSERT INTO upsert_t(code, note)
VALUES ('D', 'd1'), ('E', 'e1')
RETURNING id, code, note;

INSERT INTO upsert_t(code, note)
VALUES ('D', 'd2')
ON CONFLICT (code) DO UPDATE
SET note = EXCLUDED.note
WHERE upsert_t.note <> EXCLUDED.note
RETURNING *;

UPDATE upsert_t
SET note = note
WHERE code = 'A'
RETURNING id, code, note;

UPDATE upsert_t
SET note = 'missing'
WHERE code = 'ZZZ'
RETURNING id, code, note;

DELETE FROM upsert_t
WHERE code = 'ZZZ'
RETURNING *;

SELECT * FROM upsert_t ORDER BY id;

-- bad upsert / returning cases
INSERT INTO upsert_t(code, note)
VALUES ('A', 'dup')
ON CONFLICT (note) DO NOTHING;

INSERT INTO upsert_t(code, note)
VALUES ('A', 'dup')
ON CONFLICT (code) DO UPDATE
SET missing_col = EXCLUDED.note;

INSERT INTO upsert_t(code, note)
VALUES ('A', 'dup')
ON CONFLICT (code) DO UPDATE
SET note = (SELECT code FROM upsert_t);

INSERT INTO upsert_t(code, note)
VALUES ('F', 'f1')
ON CONFLICT DO UPDATE SET note = 'x';

INSERT INTO upsert_t(id, code, note)
VALUES (300, 'BAD_ALWAYS', 'x');

DROP SCHEMA compat CASCADE;
