-- source: review-2026-08.md
-- finding: Root cause 2: option lists are consumed to keep the parse going and then dropped on the floor
-- area: LISTEN/NOTIFY, advisory locks and DISCARD
-- title: Root cause 2: option lists are consumed to keep the parse going and then dropped on the floor
-- begin-expected
-- ok: 0
-- end-expected
CREATE TABLE zz_c (id int);
-- begin-expected
-- ok: 0
-- end-expected
COMMENT ON TABLE zz_c IS $$dq body$$;
-- begin-expected
-- columns: obj_description:text
-- row: dq body
-- rowcount: 1
-- end-expected
SELECT obj_description('zz_c'::regclass);
-- begin-expected
-- ok: 0
-- end-expected
COMMENT ON COLUMN zz_c.id IS $tag$dqcol$tag$;
-- begin-expected
-- columns: col_description:text
-- row: dqcol
-- rowcount: 1
-- end-expected
SELECT col_description('zz_c'::regclass, 1);
-- begin-expected
-- ok: 0
-- end-expected
CREATE TABLE zz_ix (id integer, b integer);
-- begin-expected
-- ok: 0
-- end-expected
CREATE INDEX zz_xf ON zz_ix (id, b) WITH (fillfactor = 70);
-- begin-expected
-- columns: array_to_string:text
-- row: fillfactor=70
-- rowcount: 1
-- end-expected
SELECT array_to_string(reloptions, ',') FROM pg_class WHERE relname = 'zz_xf';
-- begin-expected
-- columns: pg_get_indexdef:text
-- row: CREATE INDEX zz_xf ON public.zz_ix USING btree (id, b) WITH (fillfactor='70')
-- rowcount: 1
-- end-expected
SELECT pg_get_indexdef('zz_xf'::regclass);
-- begin-expected
-- ok: 0
-- end-expected
CREATE FUNCTION zz_sum(int, int) RETURNS int LANGUAGE sql IMMUTABLE STRICT AS $$ SELECT $1 + $2 $$;
-- begin-expected
-- ok: 0
-- end-expected
CREATE AGGREGATE zz_agg (int) (SFUNC = zz_sum, STYPE = int, INITCOND = '0',
  MSFUNC = zz_sum, MINVFUNC = zz_sum, MSTYPE = int, MINITCOND = '0',
  SORTOP = <, PARALLEL = SAFE);
-- begin-expected
-- columns: aggmtransfn:text | aggminvtransfn:text | aggmtranstype:text | aggminitval:text | aggsortop:text
-- row: zz_sum | zz_sum | integer | 0 | <(integer,integer)
-- rowcount: 1
-- end-expected
SELECT aggmtransfn::text, aggminvtransfn::text, aggmtranstype::regtype::text,
       aggminitval, aggsortop::regoperator::text FROM pg_aggregate
 WHERE aggfnoid::regproc::text = 'zz_agg';
-- begin-expected
-- columns: proparallel:char
-- row: s
-- rowcount: 1
-- end-expected
SELECT proparallel FROM pg_proc WHERE proname = 'zz_agg';
-- begin-expected-error
-- sqlstate: 0A000
-- message-like: ANALYZE option must be specified when a column list is provided
-- end-expected-error
VACUUM zz_v (id);
-- begin-expected-error
-- sqlstate: 0A000
-- message-like: ANALYZE option must be specified when a column list is provided
-- end-expected-error
VACUUM zz_v (nosuchcol);
-- begin-expected-error
-- sqlstate: 0A000
-- message-like: ANALYZE option must be specified when a column list is provided
-- end-expected-error
VACUUM (ANALYZE FALSE) zz_v (id);
-- begin-expected-error
-- sqlstate: 42601
-- message-like: syntax error at or near ")"
-- end-expected-error
VACUUM zz_v ();
-- begin-expected-error
-- sqlstate: 42P01
-- message-like: relation "zz_v" does not exist
-- end-expected-error
VACUUM (ANALYZE) zz_v (nosuchcol);
-- begin-expected-error
-- sqlstate: 42P01
-- message-like: relation "zz_v" does not exist
-- end-expected-error
ANALYZE zz_v (nosuchcol);
-- begin-expected
-- ok: 0
-- end-expected
CREATE TABLE zz_it (id2 integer GENERATED BY DEFAULT AS IDENTITY,
                    id3 smallint GENERATED ALWAYS AS IDENTITY);
-- begin-expected
-- columns: relname:name | seqmax:int8
-- row: zz_it_id2_seq | 2147483647
-- row: zz_it_id3_seq | 32767
-- rowcount: 2
-- end-expected
SELECT c.relname, s.seqmax FROM pg_sequence s JOIN pg_class c ON c.oid = s.seqrelid
 WHERE c.relname LIKE 'zz\_it\_%' ORDER BY 1;
-- begin-expected
-- ok: 0
-- end-expected
CREATE TABLE zz_d (id integer, d_null text DEFAULT NULL, d_val text DEFAULT 'x');
-- begin-expected
-- columns: count:int8
-- row: 1
-- rowcount: 1
-- end-expected
SELECT count(*) FROM pg_attrdef d JOIN pg_class c ON c.oid = d.adrelid WHERE c.relname = 'zz_d';
-- begin-expected
-- columns: attname:name | atthasdef:bool
-- row: id | f
-- row: d_null | f
-- row: d_val | t
-- rowcount: 3
-- end-expected
SELECT attname, atthasdef FROM pg_attribute a JOIN pg_class c ON c.oid = a.attrelid
 WHERE c.relname = 'zz_d' AND attnum > 0 ORDER BY attnum;
-- begin-expected
-- columns: column_name:name | column_default:varchar
-- row: id | NULL
-- row: d_null | NULL
-- row: d_val | 'x'::text
-- rowcount: 3
-- end-expected
SELECT column_name, column_default FROM information_schema.columns
 WHERE table_name = 'zz_d' ORDER BY ordinal_position;
