-- source: investigation.md
-- finding: 35
-- title: Recursive CTE restrictions are absent
-- unrunnable: the report wrote this reproducer abbreviated
WITH RECURSIVE r(n) AS (SELECT 1 UNION ALL SELECT a.n + b.n FROM r a, r b WHERE a.n < 4) …
--   PG: 42P19 recursive reference must not appear more than once | mg: 3 rows
WITH RECURSIVE r(n) AS (SELECT 1 UNION ALL SELECT max(n) + 1 FROM r WHERE n < 3) …
--   PG: 42P19 aggregate functions are not allowed in the recursive term | mg: 5 rows
WITH RECURSIVE r(n) AS (SELECT 1 UNION ALL SELECT n + 1 FROM r WHERE n < 3 LIMIT 10) …
--   PG: 0A000 LIMIT in a recursive query is not implemented | mg: 3 rows
WITH RECURSIVE r(n) AS (SELECT 1 UNION ALL SELECT t.n + 1 FROM (VALUES (1)) v LEFT JOIN r t ON true …) …
--   PG: 42P19 recursive reference must not appear within an outer join | mg: 3 rows
WITH RECURSIVE r(n) AS (SELECT 1::int UNION SELECT (n + 1)::bigint FROM r WHERE n < 3) …
--   PG: 42804 column 1 has type integer in non-recursive term but bigint overall | mg: 3 rows
WITH RECURSIVE r(n) AS (…) SEARCH DEPTH FIRST BY n SET ord, s AS (SELECT 9) SELECT …
--   PG: works | mg: 42601 syntax error at or near ",";;
