-- source: review-2026-08.md
-- finding: Root cause 12: parse failures reach the client as XX000 rather than as syntax errors
-- area: The parsers
-- title: Root cause 12: parse failures reach the client as XX000 rather than as syntax errors
-- begin-expected-error
-- sqlstate: 22023
-- message-like: START value (-5) cannot be less than MINVALUE (1)
-- end-expected-error
CREATE TABLE zz_vf2_i1 (id int    GENERATED BY DEFAULT AS IDENTITY (START WITH -5), v text);
-- begin-expected-error
-- sqlstate: 22023
-- message-like: START value (1) cannot be greater than MAXVALUE (-1)
-- end-expected-error
CREATE TABLE zz_vf2_i2 (id bigint GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY -1), v text);
-- begin-expected-error
-- sqlstate: 22003
-- message-like: value "99999999999999999999" is out of range for type bigint
-- end-expected-error
CREATE TABLE zz_vf2_i3 (id bigint GENERATED ALWAYS AS IDENTITY (START WITH 99999999999999999999), v text);
-- begin-expected
-- ok: 0
-- end-expected
CREATE TABLE zz_vf2_i4 (id int    GENERATED ALWAYS AS IDENTITY (MINVALUE -10 START WITH -5), v text);
-- begin-expected-error
-- sqlstate: 42601
-- message-like: syntax error at or near "BOGUS"
-- end-expected-error
SELECT sum(g) OVER (ORDER BY g ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW EXCLUDE BOGUS)
  FROM generate_series(1,3) g;
-- begin-expected-error
-- sqlstate: 42601
-- message-like: syntax error at or near ")"
-- end-expected-error
SELECT sum(g) OVER (ORDER BY g ROWS UNBOUNDED PRECEDING EXCLUDE) FROM generate_series(1,3) g;
