package com.memgres.ddl;

import com.memgres.core.Memgres;
import org.junit.jupiter.api.*;

import java.sql.*;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Tests for ALTER TABLE ... ALTER COLUMN ... ADD GENERATED identity syntax.
 *
 * pg_dump outputs this when a table uses GENERATED ALWAYS/BY DEFAULT AS IDENTITY:
 *   ALTER TABLE tbl ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
 *     SEQUENCE NAME tbl_id_seq START WITH 1 INCREMENT BY 1 ...
 *   );
 *
 * Also covers SET GENERATED, DROP IDENTITY, and related identity column operations.
 */
class AlterColumnIdentityTest {

    static Memgres memgres;
    static Connection conn;

    @BeforeAll
    static void setUp() throws Exception {
        memgres = Memgres.builder().port(0).build().start();
        conn = DriverManager.getConnection(
                "jdbc:postgresql://localhost:" + memgres.getPort() + "/test",
                "test", "test"
        );
    }

    @AfterAll
    static void tearDown() throws Exception {
        if (conn != null) conn.close();
        if (memgres != null) memgres.close();
    }

    private void exec(String sql) throws SQLException {
        try (Statement s = conn.createStatement()) { s.execute(sql); }
    }

    private String query1(String sql) throws SQLException {
        try (Statement s = conn.createStatement(); ResultSet rs = s.executeQuery(sql)) {
            assertTrue(rs.next()); return rs.getString(1);
        }
    }

    // =========================================================================
    // ADD GENERATED BY DEFAULT AS IDENTITY
    // =========================================================================

    @Test
    void testAlterColumnAddGeneratedByDefault() throws SQLException {
        exec("CREATE TABLE gen_add1 (id bigint NOT NULL, name text)");
        exec("ALTER TABLE gen_add1 ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY");
        exec("INSERT INTO gen_add1 (name) VALUES ('auto')");
        assertNotNull(query1("SELECT id FROM gen_add1"));
    }

    @Test
    void testAlterColumnAddGeneratedByDefaultWithSequenceOptions() throws SQLException {
        // pg_dump format: includes SEQUENCE NAME and options
        exec("CREATE TABLE gen_add2 (id bigint NOT NULL, name text)");
        exec("CREATE SEQUENCE gen_add2_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1");
        exec("""
            ALTER TABLE gen_add2 ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
                SEQUENCE NAME gen_add2_id_seq
                START WITH 1
                INCREMENT BY 1
                NO MINVALUE
                NO MAXVALUE
                CACHE 1
            )
        """);
        exec("INSERT INTO gen_add2 (name) VALUES ('auto')");
        assertEquals("1", query1("SELECT id FROM gen_add2"));
    }

    @Test
    void testAlterColumnAddGeneratedAlwaysAsIdentity() throws SQLException {
        exec("CREATE TABLE gen_add3 (id bigint NOT NULL, name text)");
        exec("ALTER TABLE gen_add3 ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY");
        exec("INSERT INTO gen_add3 (name) VALUES ('always')");
        assertNotNull(query1("SELECT id FROM gen_add3"));
    }

    @Test
    void testAlterColumnAddGeneratedAlwaysWithOptions() throws SQLException {
        exec("CREATE TABLE gen_add4 (id bigint NOT NULL, name text)");
        exec("""
            ALTER TABLE gen_add4 ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
                START WITH 100
                INCREMENT BY 10
            )
        """);
        exec("INSERT INTO gen_add4 (name) VALUES ('starts_at_100')");
        assertEquals("100", query1("SELECT id FROM gen_add4"));
    }

    // =========================================================================
    // SET GENERATED
    // =========================================================================

    @Test
    void testAlterColumnSetGeneratedAlways() throws SQLException {
        exec("CREATE TABLE gen_set1 (id bigint GENERATED BY DEFAULT AS IDENTITY, name text)");
        exec("ALTER TABLE gen_set1 ALTER COLUMN id SET GENERATED ALWAYS");
    }

    @Test
    void testAlterColumnSetGeneratedByDefault() throws SQLException {
        exec("CREATE TABLE gen_set2 (id bigint GENERATED ALWAYS AS IDENTITY, name text)");
        exec("ALTER TABLE gen_set2 ALTER COLUMN id SET GENERATED BY DEFAULT");
        // BY DEFAULT allows explicit values
        exec("INSERT INTO gen_set2 (id, name) VALUES (999, 'explicit')");
        assertEquals("999", query1("SELECT id FROM gen_set2"));
    }

    // =========================================================================
    // DROP IDENTITY
    // =========================================================================

    @Test
    void testAlterColumnDropIdentity() throws SQLException {
        exec("CREATE TABLE gen_drop1 (id bigint GENERATED ALWAYS AS IDENTITY, name text)");
        exec("ALTER TABLE gen_drop1 ALTER COLUMN id DROP IDENTITY");
    }

    @Test
    void testAlterColumnDropIdentityIfExists() throws SQLException {
        exec("CREATE TABLE gen_drop2 (id bigint NOT NULL, name text)");
        exec("ALTER TABLE gen_drop2 ALTER COLUMN id DROP IDENTITY IF EXISTS");
    }

    // =========================================================================
    // Multiple identity columns in pg_dump pattern
    // =========================================================================

    @Test
    void testMultipleTablesWithIdentityPgDumpStyle() throws SQLException {
        // pg_dump creates tables without identity, then adds it via ALTER
        exec("CREATE TABLE pgd_orders (id bigint NOT NULL, customer_id bigint, total numeric)");
        exec("CREATE TABLE pgd_items (id bigint NOT NULL, order_id bigint, product text)");
        exec("CREATE SEQUENCE pgd_orders_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1");
        exec("CREATE SEQUENCE pgd_items_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1");
        exec("""
            ALTER TABLE pgd_orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
                SEQUENCE NAME pgd_orders_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
            )
        """);
        exec("""
            ALTER TABLE pgd_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
                SEQUENCE NAME pgd_items_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
            )
        """);
        exec("INSERT INTO pgd_orders (customer_id, total) VALUES (1, 100.00)");
        exec("INSERT INTO pgd_items (order_id, product) VALUES (1, 'Widget')");
        assertEquals("1", query1("SELECT id FROM pgd_orders"));
        assertEquals("1", query1("SELECT id FROM pgd_items"));
    }

    // =========================================================================
    // Schema-qualified table in ALTER COLUMN ADD GENERATED
    // =========================================================================

    @Test
    void testSchemaQualifiedAlterColumnAddGenerated() throws SQLException {
        exec("CREATE TABLE public.gen_schema (id bigint NOT NULL, val text)");
        exec("ALTER TABLE public.gen_schema ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY");
        exec("INSERT INTO public.gen_schema (val) VALUES ('qualified')");
    }

    // =========================================================================
    // RESTART / SET sequence options on identity column
    // =========================================================================

    @Test
    void testAlterIdentityRestart() throws SQLException {
        exec("CREATE TABLE gen_restart (id bigint GENERATED BY DEFAULT AS IDENTITY, name text)");
        exec("INSERT INTO gen_restart (name) VALUES ('first')");
        exec("ALTER TABLE gen_restart ALTER COLUMN id RESTART WITH 100");
        exec("INSERT INTO gen_restart (name) VALUES ('after_restart')");
        assertEquals("100", query1("SELECT id FROM gen_restart WHERE name = 'after_restart'"));
    }

    @Test
    void testAlterIdentitySetIncrement() throws SQLException {
        exec("CREATE TABLE gen_incr (id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1), name text)");
        exec("ALTER TABLE gen_incr ALTER COLUMN id SET INCREMENT BY 5");
        exec("INSERT INTO gen_incr (name) VALUES ('a')");
        exec("INSERT INTO gen_incr (name) VALUES ('b')");
    }
}
