package com.memgres.ddl;

import com.memgres.core.Memgres;
import org.junit.jupiter.api.*;

import java.sql.*;

import static org.junit.jupiter.api.Assertions.*;

/**
 * The clauses of a column definition, and the sequence an identity column is fed by.
 *
 * <p>The clauses are a set rather than a sequence: PostgreSQL refuses a definition that says the
 * same thing twice or two contradictory things instead of letting the last clause written decide.
 * An identity column's option list describes a real sequence — every option in it, not only START
 * and INCREMENT — and the same options can be altered afterwards by the rules ALTER SEQUENCE
 * follows. Verified against PostgreSQL 18.
 */
class ColumnDefinitionClauseTest {

    static Memgres memgres;
    static Connection conn;

    @BeforeAll
    static void setUp() throws Exception {
        memgres = Memgres.builder().port(0).build().start();
        conn = DriverManager.getConnection(
                "jdbc:postgresql://localhost:" + memgres.getPort() + "/test", "test", "test");
    }

    @AfterAll
    static void tearDown() throws Exception {
        if (conn != null) conn.close();
        if (memgres != null) memgres.close();
    }

    private void exec(String sql) throws SQLException {
        try (Statement s = conn.createStatement()) { s.execute(sql); }
    }

    private String query1(String sql) throws SQLException {
        try (Statement s = conn.createStatement(); ResultSet rs = s.executeQuery(sql)) {
            assertTrue(rs.next());
            return rs.getString(1);
        }
    }

    private String refused(String sql) {
        SQLException e = assertThrows(SQLException.class, () -> exec(sql));
        return e.getSQLState() + "|" + e.getMessage();
    }

    private String seqField(String field, String seqName) throws SQLException {
        return query1("SELECT " + field + "::text FROM pg_sequence WHERE seqrelid = '"
                + seqName + "'::regclass");
    }

    @Test
    void identityOptionListDescribesTheSequence() throws SQLException {
        exec("CREATE TABLE cdc_id (id integer GENERATED ALWAYS AS IDENTITY "
                + "(SEQUENCE NAME cdc_myseq START WITH 5 INCREMENT BY 2 MINVALUE 1 MAXVALUE 100 "
                + "CACHE 3 CYCLE), v text)");
        assertEquals("5", seqField("seqstart", "cdc_myseq"));
        assertEquals("2", seqField("seqincrement", "cdc_myseq"));
        assertEquals("1", seqField("seqmin", "cdc_myseq"));
        assertEquals("100", seqField("seqmax", "cdc_myseq"));
        assertEquals("3", seqField("seqcache", "cdc_myseq"));
        assertEquals("true", seqField("seqcycle", "cdc_myseq"));
        exec("INSERT INTO cdc_id (v) VALUES ('a')");
        exec("INSERT INTO cdc_id (v) VALUES ('b')");
        assertEquals("5", query1("SELECT min(id)::text FROM cdc_id"));
        assertEquals("7", query1("SELECT max(id)::text FROM cdc_id"));
    }

    @Test
    void theIdentitySequenceBelongsToItsColumn() throws SQLException {
        exec("CREATE TABLE cdc_owned (id integer GENERATED ALWAYS AS IDENTITY "
                + "(SEQUENCE NAME cdc_ownedseq), v text)");
        exec("DROP TABLE cdc_owned");
        assertEquals("0", query1("SELECT count(*)::text FROM pg_class WHERE relname = 'cdc_ownedseq'"));
    }

    @Test
    void notNullMaySayItIsNotInherited() throws SQLException {
        exec("CREATE TABLE cdc_nn (a integer NOT NULL NO INHERIT, b integer)");
        assertEquals("NO", query1("SELECT is_nullable FROM information_schema.columns"
                + " WHERE table_name = 'cdc_nn' AND column_name = 'a'"));
    }

    @Test
    void aSecondDefaultContradictsTheFirst() {
        assertTrue(refused("CREATE TABLE cdc_dup (a integer DEFAULT 1 DEFAULT 2)")
                .contains("multiple default values specified for column \"a\" of table \"cdc_dup\""));
    }

    @Test
    void nullAndNotNullCannotBothBeWritten() {
        assertTrue(refused("CREATE TABLE cdc_nnnull (a integer NOT NULL NULL)")
                .contains("conflicting NULL/NOT NULL declarations for column \"a\""
                        + " of table \"cdc_nnnull\""));
    }

    @Test
    void aColumnIsEitherIdentityOrGenerated() {
        assertTrue(refused("CREATE TABLE cdc_both (a integer GENERATED ALWAYS AS IDENTITY"
                + " GENERATED ALWAYS AS (1) STORED)")
                .contains("both identity and generation expression specified"));
    }

    @Test
    void alterColumnAltersTheSequenceBehindIt() throws SQLException {
        exec("CREATE TABLE cdc_alt (id integer GENERATED BY DEFAULT AS IDENTITY, v text)");
        // PostgreSQL's grammar lets the options repeat, so this is one action carrying two of them.
        exec("ALTER TABLE cdc_alt ALTER COLUMN id SET INCREMENT BY 5 SET START WITH 100");
        assertEquals("100", seqField("seqstart", "cdc_alt_id_seq"));
        assertEquals("5", seqField("seqincrement", "cdc_alt_id_seq"));
        // NO MAXVALUE asks for the bound the column's own type gives it back.
        exec("ALTER TABLE cdc_alt ALTER COLUMN id SET NO MAXVALUE");
        assertEquals("2147483647", seqField("seqmax", "cdc_alt_id_seq"));
        exec("ALTER TABLE cdc_alt ALTER COLUMN id SET CACHE 7");
        assertEquals("7", seqField("seqcache", "cdc_alt_id_seq"));
    }

    @Test
    void addColumnKeepsTheCheckWrittenOnIt() throws SQLException {
        exec("CREATE TABLE cdc_addchk (a integer)");
        exec("ALTER TABLE cdc_addchk ADD COLUMN b integer CHECK (b > 0)");
        exec("INSERT INTO cdc_addchk VALUES (1, 1)");
        assertThrows(SQLException.class, () -> exec("INSERT INTO cdc_addchk VALUES (1, -1)"));
    }
}
