package com.memgres.ddl;

import com.memgres.core.Memgres;
import org.junit.jupiter.api.*;

import java.sql.*;
import java.util.*;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Tests for GENERATED ALWAYS AS IDENTITY, GENERATED BY DEFAULT, OVERRIDING clauses,
 * generated stored columns, and identity column ALTER behavior.
 *
 * Key behaviors from PG:
 * - GENERATED ALWAYS AS IDENTITY rejects explicit values (unless OVERRIDING SYSTEM VALUE)
 * - OVERRIDING USER VALUE ignores the user-supplied value
 * - ALTER COLUMN SET GENERATED BY DEFAULT/ALWAYS toggles behavior
 * - DROP IDENTITY / ADD GENERATED ALWAYS AS IDENTITY
 * - Generated stored columns cannot be directly written
 */
class IdentityAndGeneratedColumnTest {

    static Memgres memgres;
    static Connection conn;

    @BeforeAll
    static void setUp() throws Exception {
        memgres = Memgres.builder().port(0).build().start();
        conn = DriverManager.getConnection(
                memgres.getJdbcUrl() + "?preferQueryMode=simple",
                memgres.getUser(), memgres.getPassword());
        conn.setAutoCommit(true);
    }

    @AfterAll
    static void tearDown() throws Exception {
        if (conn != null) conn.close();
        if (memgres != null) memgres.close();
    }

    static void exec(String sql) throws SQLException {
        try (Statement s = conn.createStatement()) { s.execute(sql); }
    }

    static String scalar(String sql) throws SQLException {
        try (Statement s = conn.createStatement(); ResultSet rs = s.executeQuery(sql)) {
            return rs.next() ? rs.getString(1) : null;
        }
    }

    static List<List<String>> query(String sql) throws SQLException {
        try (Statement s = conn.createStatement(); ResultSet rs = s.executeQuery(sql)) {
            ResultSetMetaData md = rs.getMetaData();
            int cols = md.getColumnCount();
            List<List<String>> rows = new ArrayList<>();
            while (rs.next()) {
                List<String> row = new ArrayList<>();
                for (int i = 1; i <= cols; i++) row.add(rs.getString(i));
                rows.add(row);
            }
            return rows;
        }
    }

    static void assertSqlFails(String sql, String expectedState) {
        try {
            exec(sql);
            fail("Expected error for: " + sql);
        } catch (SQLException e) {
            assertEquals(expectedState, e.getSQLState(),
                    "Wrong SQLSTATE for: " + sql + ": " + e.getMessage());
        }
    }

    // ========================================================================
    // GENERATED ALWAYS AS IDENTITY
    // ========================================================================

    @Test
    void generated_always_rejects_explicit_value() throws SQLException {
        exec("CREATE TABLE ga_t(id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY, a int)");
        try {
            // PG rejects this with SQLSTATE 428C9
            assertSqlFails(
                    "INSERT INTO ga_t(id, a) VALUES (401, 12)",
                    "428C9");
        } finally {
            exec("DROP TABLE IF EXISTS ga_t");
        }
    }

    @Test
    void generated_always_with_overriding_system_value() throws SQLException {
        exec("CREATE TABLE ga_t2(id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY, a int)");
        try {
            exec("INSERT INTO ga_t2(a) VALUES (1)");
            exec("INSERT INTO ga_t2(id, a) OVERRIDING SYSTEM VALUE VALUES (100, 2)");
            List<List<String>> rows = query("SELECT * FROM ga_t2 ORDER BY id");
            assertEquals(2, rows.size());
            assertEquals("100", rows.get(1).get(0), "OVERRIDING SYSTEM VALUE should use supplied id");
        } finally {
            exec("DROP TABLE IF EXISTS ga_t2");
        }
    }

    @Test
    void generated_always_with_overriding_user_value() throws SQLException {
        exec("CREATE TABLE ga_t3(id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY, a int)");
        try {
            exec("INSERT INTO ga_t3(id, a) OVERRIDING USER VALUE VALUES (200, 9)");
            String id = scalar("SELECT id FROM ga_t3");
            // OVERRIDING USER VALUE ignores the 200 and uses the identity sequence
            assertNotEquals("200", id, "OVERRIDING USER VALUE should ignore the supplied id");
        } finally {
            exec("DROP TABLE IF EXISTS ga_t3");
        }
    }

    // ========================================================================
    // ALTER IDENTITY: BY DEFAULT ↔ ALWAYS, DROP IDENTITY
    // ========================================================================

    @Test
    void alter_identity_to_by_default_allows_explicit() throws SQLException {
        exec("CREATE TABLE ai_t(id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY, a int)");
        try {
            exec("ALTER TABLE ai_t ALTER COLUMN id SET GENERATED BY DEFAULT");
            // Now explicit values should be accepted
            exec("INSERT INTO ai_t(id, a) VALUES (300, 10)");
            assertEquals("300", scalar("SELECT id FROM ai_t WHERE a = 10"));
        } finally {
            exec("DROP TABLE IF EXISTS ai_t");
        }
    }

    @Test
    void alter_identity_back_to_always_rejects_explicit() throws SQLException {
        exec("CREATE TABLE ai_t2(id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY, a int)");
        try {
            exec("ALTER TABLE ai_t2 ALTER COLUMN id SET GENERATED BY DEFAULT");
            exec("ALTER TABLE ai_t2 ALTER COLUMN id SET GENERATED ALWAYS");
            assertSqlFails("INSERT INTO ai_t2(id, a) VALUES (999, 1)", "428C9");
        } finally {
            exec("DROP TABLE IF EXISTS ai_t2");
        }
    }

    @Test
    void drop_identity_and_re_add() throws SQLException {
        exec("CREATE TABLE ai_t3(id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY, a int)");
        try {
            exec("ALTER TABLE ai_t3 ALTER COLUMN id DROP IDENTITY");
            // After dropping identity, explicit values should work (no sequence)
            exec("INSERT INTO ai_t3(id, a) VALUES (1, 10)");
            assertEquals("1", scalar("SELECT id FROM ai_t3"));
            // Re-add identity
            exec("ALTER TABLE ai_t3 ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY");
            assertSqlFails("INSERT INTO ai_t3(id, a) VALUES (2, 20)", "428C9");
        } finally {
            exec("DROP TABLE IF EXISTS ai_t3");
        }
    }

    // ========================================================================
    // GENERATED ALWAYS AS (expr) STORED
    // ========================================================================

    @Test
    void generated_stored_column_computed_correctly() throws SQLException {
        exec("CREATE TABLE gs_t(id int PRIMARY KEY, a int, c int GENERATED ALWAYS AS (a * 10) STORED)");
        try {
            exec("INSERT INTO gs_t(id, a) VALUES (1, 5)");
            assertEquals("50", scalar("SELECT c FROM gs_t WHERE id = 1"));
        } finally {
            exec("DROP TABLE IF EXISTS gs_t");
        }
    }

    @Test
    void generated_stored_column_rejects_direct_write() throws SQLException {
        exec("CREATE TABLE gs_t2(id int PRIMARY KEY, a int, c int GENERATED ALWAYS AS (a * 10) STORED)");
        try {
            // Can't set a generated stored column directly
            assertThrows(SQLException.class,
                    () -> exec("UPDATE gs_t2 SET c = 123 WHERE id = 1"));
            assertThrows(SQLException.class,
                    () -> exec("INSERT INTO gs_t2(id, a, c) VALUES (2, 3, 999)"));
        } finally {
            exec("DROP TABLE IF EXISTS gs_t2");
        }
    }

    @Test
    void generated_column_with_nonexistent_reference_fails() throws SQLException {
        exec("CREATE TABLE gs_t3(id int PRIMARY KEY, a int)");
        try {
            assertThrows(SQLException.class,
                    () -> exec("ALTER TABLE gs_t3 ADD COLUMN e int GENERATED ALWAYS AS (no_such_col * 2) STORED"));
        } finally {
            exec("DROP TABLE IF EXISTS gs_t3");
        }
    }

    // ========================================================================
    // Identity sequence values: monotonic and correct after mixed operations
    // ========================================================================

    @Test
    void identity_values_are_monotonically_increasing() throws SQLException {
        exec("CREATE TABLE mono_t(id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY, a int, b text DEFAULT 'd')");
        try {
            exec("INSERT INTO mono_t(a, b) VALUES (1, 'x'), (2, 'y')");
            exec("INSERT INTO mono_t(a) VALUES (7)");
            List<List<String>> rows = query("SELECT id FROM mono_t ORDER BY id");
            // Should be 1, 2, 3 (not 1, 2, 4 or similar)
            assertEquals(3, rows.size());
            int prev = 0;
            for (List<String> row : rows) {
                int id = Integer.parseInt(row.get(0));
                assertTrue(id > prev, "Identity should be monotonically increasing: prev=" + prev + " cur=" + id);
                prev = id;
            }
        } finally {
            exec("DROP TABLE IF EXISTS mono_t");
        }
    }

    @Test
    void identity_continues_after_overriding_system() throws SQLException {
        exec("CREATE TABLE ov_t(id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY, a int)");
        try {
            exec("INSERT INTO ov_t(a) VALUES (1)"); // id=1
            exec("INSERT INTO ov_t(id, a) OVERRIDING SYSTEM VALUE VALUES (100, 2)"); // id=100
            exec("INSERT INTO ov_t(a) VALUES (3)"); // should be id=2 (sequence isn't affected by explicit id)
            List<List<String>> rows = query("SELECT id FROM ov_t ORDER BY id");
            assertEquals(3, rows.size());
            // The third insert should get the next sequence value (2), not 101
            int thirdId = Integer.parseInt(rows.get(1).get(0));
            assertTrue(thirdId < 100, "Sequence should continue from where it was, not from OVERRIDING value");
        } finally {
            exec("DROP TABLE IF EXISTS ov_t");
        }
    }
}
