package com.memgres.ddl;

import com.memgres.core.Memgres;
import org.junit.jupiter.api.*;

import java.sql.*;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Verifies that GENERATED AS IDENTITY columns (with and without explicit
 * START/INCREMENT) create real, usable sequences that match PG 18 behavior.
 * Covers the same lifecycle aspects as SerialSequenceLifecycleTest but for
 * the identity column syntax.
 */
class IdentitySequenceLifecycleTest {

    static Memgres memgres;
    static Connection conn;

    @BeforeAll
    static void setUp() throws Exception {
        memgres = Memgres.builder().port(0).build().start();
        conn = DriverManager.getConnection(
                memgres.getJdbcUrl() + "?preferQueryMode=simple",
                memgres.getUser(), memgres.getPassword());
        conn.setAutoCommit(true);
    }

    @AfterAll
    static void tearDown() throws Exception {
        if (conn != null) conn.close();
        if (memgres != null) memgres.close();
    }

    private static void exec(String sql) throws SQLException {
        try (Statement s = conn.createStatement()) { s.execute(sql); }
    }

    private static String querySingle(String sql) throws SQLException {
        try (Statement s = conn.createStatement(); ResultSet rs = s.executeQuery(sql)) {
            return rs.next() ? rs.getString(1) : null;
        }
    }

    private static int queryInt(String sql) throws SQLException {
        try (Statement s = conn.createStatement(); ResultSet rs = s.executeQuery(sql)) {
            assertTrue(rs.next());
            return rs.getInt(1);
        }
    }

    private static long queryLong(String sql) throws SQLException {
        try (Statement s = conn.createStatement(); ResultSet rs = s.executeQuery(sql)) {
            assertTrue(rs.next());
            return rs.getLong(1);
        }
    }

    // =========================================================================
    // 1. GENERATED ALWAYS AS IDENTITY (no explicit params) creates a sequence
    // =========================================================================

    @Test void identity_always_creates_sequence() throws SQLException {
        exec("CREATE TABLE iden_t1 (id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY, val text)");
        try {
            String seqName = querySingle("SELECT pg_get_serial_sequence('iden_t1', 'id')");
            assertNotNull(seqName, "pg_get_serial_sequence should find the identity sequence");
            assertTrue(seqName.contains("iden_t1_id_seq"));
        } finally {
            exec("DROP TABLE iden_t1");
        }
    }

    // =========================================================================
    // 2. GENERATED BY DEFAULT AS IDENTITY creates a sequence
    // =========================================================================

    @Test void identity_by_default_creates_sequence() throws SQLException {
        exec("CREATE TABLE iden_t2 (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, val text)");
        try {
            String seqName = querySingle("SELECT pg_get_serial_sequence('iden_t2', 'id')");
            assertNotNull(seqName);
            assertTrue(seqName.contains("iden_t2_id_seq"));

            exec("INSERT INTO iden_t2 (val) VALUES ('auto')");
            assertEquals(1, queryInt("SELECT id FROM iden_t2 WHERE val = 'auto'"));
        } finally {
            exec("DROP TABLE iden_t2");
        }
    }

    // =========================================================================
    // 3. IDENTITY with explicit START creates a correctly initialized sequence
    // =========================================================================

    @Test void identity_with_start_uses_custom_start() throws SQLException {
        exec("CREATE TABLE iden_t3 (id integer GENERATED ALWAYS AS IDENTITY (START WITH 100) PRIMARY KEY, val text)");
        try {
            exec("INSERT INTO iden_t3 (val) VALUES ('a')");
            assertEquals(100, queryInt("SELECT id FROM iden_t3 WHERE val = 'a'"));

            exec("INSERT INTO iden_t3 (val) VALUES ('b')");
            assertEquals(101, queryInt("SELECT id FROM iden_t3 WHERE val = 'b'"));
        } finally {
            exec("DROP TABLE iden_t3");
        }
    }

    // =========================================================================
    // 4. INSERT uses real sequence — currval tracks it
    // =========================================================================

    @Test void identity_insert_tracks_currval() throws SQLException {
        exec("CREATE TABLE iden_t4 (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, val text)");
        try {
            exec("INSERT INTO iden_t4 (val) VALUES ('first')");
            assertEquals(1, queryInt("SELECT id FROM iden_t4 WHERE val = 'first'"));
            assertEquals(1L, queryLong("SELECT currval('iden_t4_id_seq')"));

            exec("INSERT INTO iden_t4 (val) VALUES ('second')");
            assertEquals(2, queryInt("SELECT id FROM iden_t4 WHERE val = 'second'"));
            assertEquals(2L, queryLong("SELECT currval('iden_t4_id_seq')"));
        } finally {
            exec("DROP TABLE iden_t4");
        }
    }

    // =========================================================================
    // 5. setval affects next INSERT for identity column
    // =========================================================================

    @Test void identity_setval_affects_insert() throws SQLException {
        exec("CREATE TABLE iden_t5 (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, val text)");
        try {
            exec("INSERT INTO iden_t5 (val) VALUES ('before')");
            assertEquals(1, queryInt("SELECT id FROM iden_t5 WHERE val = 'before'"));

            exec("SELECT setval('iden_t5_id_seq', 50)");

            exec("INSERT INTO iden_t5 (val) VALUES ('after')");
            assertEquals(51, queryInt("SELECT id FROM iden_t5 WHERE val = 'after'"));
        } finally {
            exec("DROP TABLE iden_t5");
        }
    }

    // =========================================================================
    // 6. Sequence queryable as relation immediately
    // =========================================================================

    @Test void identity_sequence_queryable_as_relation() throws SQLException {
        exec("CREATE TABLE iden_t6 (id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY, val text)");
        try {
            long lastVal = queryLong("SELECT last_value FROM iden_t6_id_seq");
            assertEquals(1L, lastVal, "initial last_value should be 1");
        } finally {
            exec("DROP TABLE iden_t6");
        }
    }

    // =========================================================================
    // 7. DROP TABLE cascades to identity sequence
    // =========================================================================

    @Test void identity_drop_table_drops_sequence() throws SQLException {
        exec("CREATE TABLE iden_t7 (id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY, val text)");
        exec("INSERT INTO iden_t7 (val) VALUES ('x')");

        assertEquals(1, queryInt(
                "SELECT count(*) FROM pg_sequences WHERE sequencename = 'iden_t7_id_seq'"));

        exec("DROP TABLE iden_t7");

        assertEquals(0, queryInt(
                "SELECT count(*) FROM pg_sequences WHERE sequencename = 'iden_t7_id_seq'"));
    }

    // =========================================================================
    // 8. ALTER SEQUENCE RESTART WITH affects identity INSERT
    // =========================================================================

    @Test void identity_alter_sequence_restart() throws SQLException {
        exec("CREATE TABLE iden_t8 (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, val text)");
        try {
            exec("INSERT INTO iden_t8 (val) VALUES ('a')");
            assertEquals(1, queryInt("SELECT id FROM iden_t8 WHERE val = 'a'"));

            exec("ALTER SEQUENCE iden_t8_id_seq RESTART WITH 200");

            exec("INSERT INTO iden_t8 (val) VALUES ('b')");
            assertEquals(200, queryInt("SELECT id FROM iden_t8 WHERE val = 'b'"));
        } finally {
            exec("DROP TABLE iden_t8");
        }
    }

    // =========================================================================
    // 9. TRUNCATE RESTART IDENTITY resets identity sequence
    // =========================================================================

    @Test void identity_truncate_restart_identity() throws SQLException {
        exec("CREATE TABLE iden_t9 (id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY, val text)");
        try {
            exec("INSERT INTO iden_t9 (val) VALUES ('a'), ('b'), ('c')");
            assertEquals(3L, queryLong("SELECT last_value FROM iden_t9_id_seq"));

            exec("TRUNCATE iden_t9 RESTART IDENTITY");

            exec("INSERT INTO iden_t9 (val) VALUES ('fresh')");
            assertEquals(1, queryInt("SELECT id FROM iden_t9 WHERE val = 'fresh'"));
        } finally {
            exec("DROP TABLE iden_t9");
        }
    }

    // =========================================================================
    // 10. Manual nextval skips values for identity column
    // =========================================================================

    @Test void identity_manual_nextval_skips_value() throws SQLException {
        exec("CREATE TABLE iden_t10 (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, val text)");
        try {
            exec("INSERT INTO iden_t10 (val) VALUES ('row1')");
            assertEquals(1, queryInt("SELECT id FROM iden_t10 WHERE val = 'row1'"));

            // Manually consume value 2
            queryLong("SELECT nextval('iden_t10_id_seq')");

            exec("INSERT INTO iden_t10 (val) VALUES ('row2')");
            assertEquals(3, queryInt("SELECT id FROM iden_t10 WHERE val = 'row2'"));
        } finally {
            exec("DROP TABLE iden_t10");
        }
    }

    // =========================================================================
    // 11. IDENTITY without explicit params — bigint variant
    // =========================================================================

    @Test void identity_bigint_without_params() throws SQLException {
        exec("CREATE TABLE iden_t11 (id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY, val text)");
        try {
            String seqName = querySingle("SELECT pg_get_serial_sequence('iden_t11', 'id')");
            assertNotNull(seqName);
            assertTrue(seqName.contains("iden_t11_id_seq"));

            exec("INSERT INTO iden_t11 (val) VALUES ('big')");
            assertEquals(1L, queryLong("SELECT id FROM iden_t11 WHERE val = 'big'"));
            assertEquals(1L, queryLong("SELECT last_value FROM iden_t11_id_seq"));
        } finally {
            exec("DROP TABLE iden_t11");
        }
    }

    // =========================================================================
    // 12. Column default expression stored for identity column
    // =========================================================================

    @Test void identity_visible_in_pg_sequences() throws SQLException {
        exec("CREATE TABLE iden_t12 (id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY, val text)");
        try {
            assertEquals(1, queryInt(
                    "SELECT count(*) FROM pg_sequences WHERE sequencename = 'iden_t12_id_seq'"));
        } finally {
            exec("DROP TABLE iden_t12");
        }
    }

    // =========================================================================
    // 13. ADD COLUMN with SERIAL creates a working sequence
    // =========================================================================

    @Test void alter_table_add_serial_column_creates_sequence() throws SQLException {
        exec("CREATE TABLE iden_t13 (val text)");
        try {
            exec("ALTER TABLE iden_t13 ADD COLUMN id serial");
            exec("INSERT INTO iden_t13 (val) VALUES ('added')");
            assertEquals(1, queryInt("SELECT id FROM iden_t13 WHERE val = 'added'"));

            String seqName = querySingle("SELECT pg_get_serial_sequence('iden_t13', 'id')");
            assertNotNull(seqName);
            assertTrue(seqName.contains("iden_t13_id_seq"));
        } finally {
            exec("DROP TABLE iden_t13");
        }
    }

    // =========================================================================
    // 14. setval with is_called=false on identity sequence
    // =========================================================================

    @Test void identity_setval_is_called_false() throws SQLException {
        exec("CREATE TABLE iden_t14 (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, val text)");
        try {
            exec("SELECT setval('iden_t14_id_seq', 42, false)");

            exec("INSERT INTO iden_t14 (val) VALUES ('exact')");
            assertEquals(42, queryInt("SELECT id FROM iden_t14 WHERE val = 'exact'"));

            exec("INSERT INTO iden_t14 (val) VALUES ('next')");
            assertEquals(43, queryInt("SELECT id FROM iden_t14 WHERE val = 'next'"));
        } finally {
            exec("DROP TABLE iden_t14");
        }
    }
}
