package com.memgres.ddl;

import com.memgres.core.Memgres;
import org.junit.jupiter.api.*;

import java.io.*;
import java.nio.file.*;
import java.sql.*;
import java.util.*;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Runs every SQL statement from the pg18_sample_sql_6 .sql and .md files against Memgres,
 * comparing results to the PG 18 baseline file generated by IndexSqlFileBaselineCollector.
 *
 * Does NOT require a real PostgreSQL instance; uses the committed baseline file.
 * To regenerate the baseline, run:
 *   mvn -pl memgres-core exec:java \
 *     -Dexec.mainClass="com.memgres.ddl.IndexSqlFileBaselineCollector" \
 *     -Dexec.classpathScope=test
 */
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
class IndexSqlFileComparisonTest {

    static final String BASELINE_RESOURCE = "pg-baselines/index-sql-file-baseline.txt";

    static Memgres memgres;
    static Connection mgConn;
    static Map<String, List<StmtBaseline>> baseline;
    static final List<String> diffs = new ArrayList<>();

        public static final class StmtBaseline {
        public final String sql;
        public final boolean success;
        public final String errorState;
        public final String columns;
        public final List<String> rows;
        public final int updateCount;

        public StmtBaseline(
                String sql,
                boolean success,
                String errorState,
                String columns,
                List<String> rows,
                int updateCount
        ) {
            this.sql = sql;
            this.success = success;
            this.errorState = errorState;
            this.columns = columns;
            this.rows = rows;
            this.updateCount = updateCount;
        }

        public String sql() { return sql; }
        public boolean success() { return success; }
        public String errorState() { return errorState; }
        public String columns() { return columns; }
        public List<String> rows() { return rows; }
        public int updateCount() { return updateCount; }

        @Override
        public boolean equals(Object o) {
            if (this == o) return true;
            if (o == null || getClass() != o.getClass()) return false;
            StmtBaseline that = (StmtBaseline) o;
            return java.util.Objects.equals(sql, that.sql)
                && success == that.success
                && java.util.Objects.equals(errorState, that.errorState)
                && java.util.Objects.equals(columns, that.columns)
                && java.util.Objects.equals(rows, that.rows)
                && updateCount == that.updateCount;
        }

        @Override
        public int hashCode() {
            return java.util.Objects.hash(sql, success, errorState, columns, rows, updateCount);
        }

        @Override
        public String toString() {
            return "StmtBaseline[sql=" + sql + ", " + "success=" + success + ", " + "errorState=" + errorState + ", " + "columns=" + columns + ", " + "rows=" + rows + ", " + "updateCount=" + updateCount + "]";
        }
    }

    @BeforeAll
    static void setUp() throws Exception {
        memgres = Memgres.builder().port(0).build().start();
        mgConn = DriverManager.getConnection(memgres.getJdbcUrl(), memgres.getUser(), memgres.getPassword());
        mgConn.setAutoCommit(true);

        baseline = loadBaseline();
    }

    @AfterAll
    static void tearDown() throws Exception {
        if (!diffs.isEmpty()) {
            System.out.println("\n=== Memgres vs PG 18 Baseline Differences ===");
            for (String d : diffs) System.out.println(d);
            System.out.println("=== Total: " + diffs.size() + " differences ===\n");
        } else {
            System.out.println("\n=== Memgres vs PG 18 Baseline: NO DIFFERENCES (all identical) ===\n");
        }
        if (mgConn != null) mgConn.close();
        if (memgres != null) memgres.close();
    }

    // === Baseline loading ================================================

    static Map<String, List<StmtBaseline>> loadBaseline() throws Exception {
        InputStream is = IndexSqlFileComparisonTest.class.getClassLoader()
                .getResourceAsStream(BASELINE_RESOURCE);
        assertNotNull(is, "Baseline file not found: " + BASELINE_RESOURCE +
                ". Run IndexSqlFileBaselineCollector to generate it.");

        Map<String, List<StmtBaseline>> groups = new LinkedHashMap<>();
        String currentGroup = null;
        String currentSql = null;
        boolean currentSuccess = true;
        String currentErrorState = null;
        String currentColumns = null;
        List<String> currentRows = new ArrayList<>();
        int currentUpdateCount = -1;

        try (BufferedReader br = new BufferedReader(new InputStreamReader(is))) {
            String line;
            while ((line = br.readLine()) != null) {
                if (line.startsWith("=== GROUP: ")) {
                    // Flush previous statement
                    if (currentSql != null && currentGroup != null) {
                        groups.computeIfAbsent(currentGroup, k -> new ArrayList<>())
                                .add(new StmtBaseline(currentSql, currentSuccess, currentErrorState,
                                        currentColumns, new ArrayList<>(currentRows), currentUpdateCount));
                    }
                    currentGroup = line.substring("=== GROUP: ".length(), line.length() - " ===".length());
                    currentSql = null;
                    currentSuccess = true;
                    currentErrorState = null;
                    currentColumns = null;
                    currentRows = new ArrayList<>();
                    currentUpdateCount = -1;
                } else if (line.startsWith("--- SQL: ")) {
                    // Flush previous statement
                    if (currentSql != null && currentGroup != null) {
                        groups.computeIfAbsent(currentGroup, k -> new ArrayList<>())
                                .add(new StmtBaseline(currentSql, currentSuccess, currentErrorState,
                                        currentColumns, new ArrayList<>(currentRows), currentUpdateCount));
                    }
                    currentSql = line.substring("--- SQL: ".length());
                    currentSuccess = true;
                    currentErrorState = null;
                    currentColumns = null;
                    currentRows = new ArrayList<>();
                    currentUpdateCount = -1;
                } else if (line.startsWith("OK: ")) {
                    currentSuccess = true;
                    String num = line.substring("OK: ".length()).replace(" rows affected", "");
                    currentUpdateCount = Integer.parseInt(num);
                } else if (line.startsWith("ERROR: ")) {
                    currentSuccess = false;
                    // "ERROR: 23505: ERROR: duplicate key..."
                    String rest = line.substring("ERROR: ".length());
                    int colon = rest.indexOf(':');
                    currentErrorState = rest.substring(0, colon);
                } else if (line.startsWith("COLUMNS: ")) {
                    currentColumns = line.substring("COLUMNS: ".length());
                } else if (line.startsWith("ROW: ")) {
                    currentRows.add(line.substring("ROW: ".length()));
                }
            }
            // Flush last statement
            if (currentSql != null && currentGroup != null) {
                groups.computeIfAbsent(currentGroup, k -> new ArrayList<>())
                        .add(new StmtBaseline(currentSql, currentSuccess, currentErrorState,
                                currentColumns, new ArrayList<>(currentRows), currentUpdateCount));
            }
        }
        return groups;
    }

    // === Comparison engine ===============================================

        public static final class StmtResult {
        public final boolean success;
        public final String errorState;
        public final String columns;
        public final List<String> rows;
        public final int updateCount;

        public StmtResult(
                boolean success,
                String errorState,
                String columns,
                List<String> rows,
                int updateCount
        ) {
            this.success = success;
            this.errorState = errorState;
            this.columns = columns;
            this.rows = rows;
            this.updateCount = updateCount;
        }

        public boolean success() { return success; }
        public String errorState() { return errorState; }
        public String columns() { return columns; }
        public List<String> rows() { return rows; }
        public int updateCount() { return updateCount; }

        @Override
        public boolean equals(Object o) {
            if (this == o) return true;
            if (o == null || getClass() != o.getClass()) return false;
            StmtResult that = (StmtResult) o;
            return success == that.success
                && java.util.Objects.equals(errorState, that.errorState)
                && java.util.Objects.equals(columns, that.columns)
                && java.util.Objects.equals(rows, that.rows)
                && updateCount == that.updateCount;
        }

        @Override
        public int hashCode() {
            return java.util.Objects.hash(success, errorState, columns, rows, updateCount);
        }

        @Override
        public String toString() {
            return "StmtResult[success=" + success + ", " + "errorState=" + errorState + ", " + "columns=" + columns + ", " + "rows=" + rows + ", " + "updateCount=" + updateCount + "]";
        }
    }

    static StmtResult runStmt(String sql) {
        try (Statement s = mgConn.createStatement()) {
            boolean hasRs = s.execute(sql);
            if (hasRs) {
                ResultSet rs = s.getResultSet();
                ResultSetMetaData md = rs.getMetaData();
                int cc = md.getColumnCount();
                List<String> cols = new ArrayList<>();
                for (int i = 1; i <= cc; i++) cols.add(md.getColumnName(i));
                List<String> rows = new ArrayList<>();
                while (rs.next()) {
                    List<String> vals = new ArrayList<>();
                    for (int i = 1; i <= cc; i++) {
                        String v = rs.getString(i);
                        vals.add(v == null ? "NULL" : v);
                    }
                    rows.add(String.join("|", vals));
                }
                Collections.sort(rows);
                rs.close();
                return new StmtResult(true, null, String.join("|", cols), rows, -1);
            } else {
                return new StmtResult(true, null, null, null, s.getUpdateCount());
            }
        } catch (SQLException e) {
            return new StmtResult(false, e.getSQLState(), null, null, -1);
        }
    }

    /** Compare Memgres result against PG 18 baseline for one statement. */
    boolean compareStmt(StmtBaseline expected, String groupLabel) {
        StmtResult mg = runStmt(expected.sql);

        if (expected.success != mg.success) {
            diffs.add(groupLabel + " | " + expected.sql + "\n  PG baseline: " +
                    (expected.success ? "OK" : "ERROR " + expected.errorState) +
                    "\n  Memgres:     " +
                    (mg.success ? "OK" : "ERROR " + mg.errorState));
            return false;
        }

        if (!expected.success) {
            if (!Objects.equals(expected.errorState, mg.errorState)) {
                diffs.add(groupLabel + " | " + expected.sql + "\n  PG SQLSTATE: " +
                        expected.errorState + "\n  MG SQLSTATE: " + mg.errorState);
                return false;
            }
            return true;
        }

        // Both success; compare results
        if (expected.columns != null && mg.columns != null) {
            if (!Objects.equals(expected.columns, mg.columns)) {
                diffs.add(groupLabel + " | " + expected.sql + "\n  PG cols: " +
                        expected.columns + "\n  MG cols: " + mg.columns);
                return false;
            }
            List<String> expectedRows = new ArrayList<>(expected.rows);
            List<String> mgRows = new ArrayList<>(mg.rows);
            Collections.sort(expectedRows);
            Collections.sort(mgRows);
            if (!expectedRows.equals(mgRows)) {
                diffs.add(groupLabel + " | " + expected.sql + "\n  PG rows: " +
                        expectedRows + "\n  MG rows: " + mgRows);
                return false;
            }
        }
        return true;
    }

    void runGroup(String groupName) {
        List<StmtBaseline> stmts = baseline.get(groupName);
        assertNotNull(stmts, "No baseline found for group: " + groupName);
        int total = 0, same = 0;
        for (StmtBaseline stmt : stmts) {
            total++;
            if (compareStmt(stmt, groupName)) same++;
        }
        System.out.println(groupName + ": " + same + "/" + total + " match PG 18 baseline");
        assertEquals(total, same, groupName + ": found differences (see output above)");
    }

    // ═══════════════════════════════════════════════════════════════════════

    @Test @Order(1)  void file_1600() { runGroup("1600"); }
    @Test @Order(2)  void file_1610() { runGroup("1610"); }
    @Test @Order(3)  void file_1620() { runGroup("1620"); }
    @Test @Order(4)  void file_1630() { runGroup("1630"); }
    @Test @Order(5)  void file_1640() { runGroup("1640"); }
    @Test @Order(6)  void file_1650() { runGroup("1650"); }
    @Test @Order(7)  void file_1660() { runGroup("1660"); }
    @Test @Order(8)  void file_1670() { runGroup("1670"); }
    @Test @Order(9)  void file_1680() { runGroup("1680"); }
    @Test @Order(10) void file_1690() { runGroup("1690"); }
    @Test @Order(11) void md_1700()   { runGroup("1700 (MD: strategy/correctness)"); }
    @Test @Order(12) void md_1710()   { runGroup("1710 (MD: capability matrix)"); }
    @Test @Order(13) void md_1720()   { runGroup("1720 (MD: concurrency/reindex)"); }
}
