package com.memgres.ddl;

import com.memgres.core.Memgres;
import org.junit.jupiter.api.*;

import java.sql.*;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Round 14 gaps: Identity + generated columns.
 *
 * - OVERRIDING SYSTEM VALUE / OVERRIDING USER VALUE
 * - ALTER COLUMN DROP IDENTITY
 * - ALTER COLUMN SET GENERATED { ALWAYS | BY DEFAULT }
 * - pg_sequence_last_value()
 * - VIRTUAL generated columns (PG 18)
 * - STORED recalc on UPDATE
 * - Cross-generated-column references
 * - ON DELETE SET DEFAULT (column_list) — PG 15+
 */
class Round14IdentityGeneratedTest {

    static Memgres memgres;
    static Connection conn;

    @BeforeAll
    static void setUp() throws Exception {
        memgres = Memgres.builder().port(0).build().start();
        conn = DriverManager.getConnection(
                memgres.getJdbcUrl() + "?preferQueryMode=simple",
                memgres.getUser(), memgres.getPassword());
        conn.setAutoCommit(true);
    }

    @AfterAll
    static void tearDown() throws Exception {
        if (conn != null) conn.close();
        if (memgres != null) memgres.close();
    }

    private static void exec(String sql) throws SQLException {
        try (Statement s = conn.createStatement()) { s.execute(sql); }
    }

    private static int scalarInt(String sql) throws SQLException {
        try (Statement s = conn.createStatement(); ResultSet rs = s.executeQuery(sql)) {
            assertTrue(rs.next());
            return rs.getInt(1);
        }
    }

    private static String scalarString(String sql) throws SQLException {
        try (Statement s = conn.createStatement(); ResultSet rs = s.executeQuery(sql)) {
            assertTrue(rs.next());
            return rs.getString(1);
        }
    }

    // =========================================================================
    // A. OVERRIDING SYSTEM/USER VALUE
    // =========================================================================

    @Test
    void overriding_system_value_on_always_column() throws SQLException {
        exec("CREATE TABLE r14_os (id int GENERATED ALWAYS AS IDENTITY, v text)");
        // Without OVERRIDING, inserting into ALWAYS column errors
        SQLException ex = assertThrows(SQLException.class,
                () -> exec("INSERT INTO r14_os (id, v) VALUES (100, 'a')"));
        assertNotNull(ex.getMessage());
        // With OVERRIDING SYSTEM VALUE it succeeds
        exec("INSERT INTO r14_os (id, v) OVERRIDING SYSTEM VALUE VALUES (100, 'b')");
        assertEquals(100, scalarInt("SELECT id FROM r14_os WHERE v = 'b'"));
    }

    @Test
    void overriding_user_value_on_by_default_column() throws SQLException {
        exec("CREATE TABLE r14_ou (id int GENERATED BY DEFAULT AS IDENTITY, v text)");
        // OVERRIDING USER VALUE forces sequence default even when user supplies a value
        exec("INSERT INTO r14_ou (id, v) OVERRIDING USER VALUE VALUES (999, 'a')");
        // id should have come from sequence, not 999
        assertEquals(0, scalarInt("SELECT count(*)::int FROM r14_ou WHERE id = 999"));
    }

    // =========================================================================
    // B. ALTER COLUMN DROP IDENTITY / SET GENERATED
    // =========================================================================

    @Test
    void alter_column_drop_identity() throws SQLException {
        exec("CREATE TABLE r14_di (id int GENERATED ALWAYS AS IDENTITY, v text)");
        exec("ALTER TABLE r14_di ALTER COLUMN id DROP IDENTITY");
        // After drop, a plain INSERT with user value should work
        exec("INSERT INTO r14_di (id, v) VALUES (42, 'x')");
        assertEquals(42, scalarInt("SELECT id FROM r14_di WHERE v = 'x'"));
    }

    @Test
    void alter_column_set_generated_by_default() throws SQLException {
        exec("CREATE TABLE r14_sg (id int GENERATED ALWAYS AS IDENTITY, v text)");
        exec("ALTER TABLE r14_sg ALTER COLUMN id SET GENERATED BY DEFAULT");
        // Now user-supplied id should work without OVERRIDING
        exec("INSERT INTO r14_sg (id, v) VALUES (7, 'a')");
        assertEquals(7, scalarInt("SELECT id FROM r14_sg WHERE v = 'a'"));
    }

    @Test
    void alter_column_restart_identity() throws SQLException {
        exec("CREATE TABLE r14_ri (id int GENERATED BY DEFAULT AS IDENTITY, v text)");
        exec("INSERT INTO r14_ri(v) VALUES ('a'), ('b')");
        exec("ALTER TABLE r14_ri ALTER COLUMN id RESTART WITH 100");
        exec("INSERT INTO r14_ri(v) VALUES ('c')");
        assertEquals(100, scalarInt("SELECT id FROM r14_ri WHERE v = 'c'"));
    }

    // =========================================================================
    // C. pg_sequence_last_value
    // =========================================================================

    @Test
    void pg_sequence_last_value_exists() throws SQLException {
        exec("CREATE SEQUENCE r14_slv_seq");
        exec("SELECT nextval('r14_slv_seq')");
        assertEquals(1L, (long) scalarInt(
                "SELECT pg_sequence_last_value('r14_slv_seq'::regclass)::int"));
    }

    // =========================================================================
    // D. VIRTUAL generated columns (PG 18)
    // =========================================================================

    @Test
    void virtual_generated_column_computed_on_read() throws SQLException {
        exec("CREATE TABLE r14_vg (a int, b int GENERATED ALWAYS AS (a * 2) VIRTUAL)");
        exec("INSERT INTO r14_vg (a) VALUES (5)");
        assertEquals(10, scalarInt("SELECT b FROM r14_vg"));
    }

    @Test
    void virtual_generated_column_recalc_after_update() throws SQLException {
        exec("CREATE TABLE r14_vgu (a int, b int GENERATED ALWAYS AS (a * 2) VIRTUAL)");
        exec("INSERT INTO r14_vgu (a) VALUES (5)");
        exec("UPDATE r14_vgu SET a = 10");
        assertEquals(20, scalarInt("SELECT b FROM r14_vgu"));
    }

    @Test
    void virtual_generated_column_cannot_be_indexed() throws SQLException {
        exec("CREATE TABLE r14_vgi (a int, b int GENERATED ALWAYS AS (a * 2) VIRTUAL)");
        SQLException ex = assertThrows(SQLException.class,
                () -> exec("CREATE INDEX r14_vgi_idx ON r14_vgi (b)"));
        assertNotNull(ex.getMessage());
    }

    // =========================================================================
    // E. STORED recalc on UPDATE
    // =========================================================================

    @Test
    void stored_generated_column_recalc_after_update() throws SQLException {
        exec("CREATE TABLE r14_sgc (a int, b int GENERATED ALWAYS AS (a * 2) STORED)");
        exec("INSERT INTO r14_sgc (a) VALUES (5)");
        assertEquals(10, scalarInt("SELECT b FROM r14_sgc"));
        exec("UPDATE r14_sgc SET a = 7");
        assertEquals(14, scalarInt("SELECT b FROM r14_sgc"));
    }

    @Test
    void generated_column_cannot_depend_on_other_generated() throws SQLException {
        // PG rejects a generated column whose expression references another generated column
        SQLException ex = assertThrows(SQLException.class,
                () -> exec("CREATE TABLE r14_gcg ("
                        + "a int, "
                        + "b int GENERATED ALWAYS AS (a * 2) STORED, "
                        + "c int GENERATED ALWAYS AS (b + 1) STORED)"));
        assertNotNull(ex.getMessage());
    }

    // =========================================================================
    // F. ON DELETE SET DEFAULT (col_list) — PG 15+
    // =========================================================================

    @Test
    void on_delete_set_default_column_list() throws SQLException {
        exec("CREATE TABLE r14_sdp (id int PRIMARY KEY)");
        exec("INSERT INTO r14_sdp VALUES (1), (99)");
        exec("CREATE TABLE r14_sdc ("
                + "  pid int DEFAULT 99 REFERENCES r14_sdp(id) ON DELETE SET DEFAULT (pid))");
        exec("INSERT INTO r14_sdc VALUES (1)");
        exec("DELETE FROM r14_sdp WHERE id = 1");
        assertEquals(99, scalarInt("SELECT pid FROM r14_sdc"));
    }

    // =========================================================================
    // G. GENERATED column with expression referencing domain types
    // =========================================================================

    @Test
    void stored_generated_null_handling() throws SQLException {
        exec("CREATE TABLE r14_gnh (a int, b int GENERATED ALWAYS AS (a + 1) STORED)");
        exec("INSERT INTO r14_gnh (a) VALUES (NULL)");
        String v = scalarString("SELECT b::text FROM r14_gnh");
        assertNull(v, "NULL + 1 = NULL per generated column semantics");
    }
}
