package com.memgres.client;

import com.memgres.core.Memgres;
import org.junit.jupiter.api.*;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

/**
 * The content of information_schema, as opposed to its shape.
 *
 * <p>A standard view that lists its columns and returns nothing is the failure this covers: a
 * migration tool reads element_types to learn what an array column holds, reads
 * column_udt_usage to learn a column's underlying type, reads table_privileges to decide whether
 * it may write, and reads constraint_table_usage to learn which foreign keys point at a table it
 * is about to drop. An empty answer to any of those is read as "no such dependency" rather than
 * as "unknown", so the tool proceeds and gets it wrong.
 *
 * <p>Every expectation here was measured on PostgreSQL 18 against the same objects this test
 * creates, and each assertion names the row it is about rather than counting rows: the counts
 * differ between servers for reasons that have nothing to do with correctness.
 */
class InformationSchemaContentTest {

    private static Memgres memgres;
    private static Connection conn;

    @BeforeAll
    static void setUp() throws Exception {
        memgres = Memgres.builder().port(0).build().start();
        conn = DriverManager.getConnection(memgres.getJdbcUrl(), memgres.getUser(), memgres.getPassword());
        try (Statement s = conn.createStatement()) {
            s.execute("CREATE SCHEMA isc_s");
            s.execute("CREATE DOMAIN isc_s.isc_dom AS varchar(10) CHECK (VALUE <> '')");
            s.execute("CREATE DOMAIN isc_s.isc_dnum AS numeric(8,2)");
            s.execute("CREATE TYPE isc_ct AS (x integer, y varchar(3), z timestamp(2))");
            s.execute("CREATE TABLE isc_s.isc_parent (id int PRIMARY KEY, code varchar(20) UNIQUE)");
            s.execute("CREATE TABLE isc_s.isc_child ("
                    + "cid int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + " pid int REFERENCES isc_s.isc_parent(id) ON DELETE CASCADE ON UPDATE SET NULL,"
                    + " amt numeric(10,2) CONSTRAINT isc_amt_chk CHECK (amt > 0),"
                    + " note isc_s.isc_dom, tags text[], ts timestamp(3),"
                    + " created timestamptz, flag boolean NOT NULL)");
            s.execute("CREATE TABLE isc_s.isc_types (c_bit8 bit(8), c_vbit bit varying(9),"
                    + " c_arr int[], c_dom isc_s.isc_dom, c_dnum isc_s.isc_dnum,"
                    + " c_ts0 timestamp(0), c_ts3 timestamp(3), c_time4 time(4),"
                    + " c_iv interval day to second(3))");
            s.execute("CREATE VIEW isc_s.isc_v AS SELECT id, code FROM isc_s.isc_parent");
            s.execute("CREATE VIEW isc_s.isc_v2 AS SELECT id FROM isc_s.isc_parent WITH CHECK OPTION");
            s.execute("CREATE FUNCTION isc_s.isc_fn(a int, b text DEFAULT 'x') RETURNS int"
                    + " LANGUAGE sql AS $$ SELECT a $$");
            s.execute("CREATE FUNCTION isc_s.isc_trgfn() RETURNS trigger"
                    + " LANGUAGE plpgsql AS $$ BEGIN RETURN NEW; END $$");
            s.execute("CREATE TRIGGER isc_trg BEFORE INSERT OR UPDATE OF code ON isc_s.isc_parent"
                    + " FOR EACH ROW EXECUTE FUNCTION isc_s.isc_trgfn()");
        }
    }

    @AfterAll
    static void tearDown() throws Exception {
        if (conn != null) conn.close();
        if (memgres != null) memgres.close();
    }

    // ---- privilege views ------------------------------------------------------------------

    @Test
    void table_privileges_grants_the_owner_every_privilege_on_a_table_it_created() throws SQLException {
        try (Statement s = conn.createStatement()) {
            // PG: creating a relation grants its owner SELECT, INSERT, UPDATE, DELETE, TRUNCATE,
            // REFERENCES and TRIGGER on it, each grantable.
            assertEquals(List.of("DELETE|YES", "INSERT|YES", "REFERENCES|YES", "SELECT|YES",
                            "TRIGGER|YES", "TRUNCATE|YES", "UPDATE|YES"),
                    rows(s, "SELECT privilege_type, is_grantable FROM information_schema.table_privileges"
                            + " WHERE table_schema='isc_s' AND table_name='isc_child'"
                            + " AND grantee='memgres' ORDER BY privilege_type", 2));
        }
    }

    @Test
    void table_privileges_marks_only_select_with_hierarchy() throws SQLException {
        try (Statement s = conn.createStatement()) {
            assertRow(s, "SELECT grantor, grantee, with_hierarchy FROM information_schema.table_privileges"
                            + " WHERE table_schema='isc_s' AND table_name='isc_parent'"
                            + " AND privilege_type='SELECT' AND grantee='memgres'",
                    "memgres", "memgres", "YES");
            assertRow(s, "SELECT with_hierarchy FROM information_schema.table_privileges"
                            + " WHERE table_schema='isc_s' AND table_name='isc_parent'"
                            + " AND privilege_type='UPDATE' AND grantee='memgres'",
                    "NO");
        }
    }

    @Test
    void table_privileges_covers_views_as_well_as_tables() throws SQLException {
        try (Statement s = conn.createStatement()) {
            assertRow(s, "SELECT is_grantable FROM information_schema.table_privileges"
                            + " WHERE table_schema='isc_s' AND table_name='isc_v'"
                            + " AND privilege_type='SELECT' AND grantee='memgres'",
                    "YES");
        }
    }

    @Test
    void role_table_grants_answers_for_the_same_named_row() throws SQLException {
        try (Statement s = conn.createStatement()) {
            assertRow(s, "SELECT grantor, grantee, is_grantable, with_hierarchy"
                            + " FROM information_schema.role_table_grants"
                            + " WHERE table_schema='isc_s' AND table_name='isc_child'"
                            + " AND privilege_type='SELECT' AND grantee='memgres'",
                    "memgres", "memgres", "YES", "YES");
        }
    }

    @Test
    void column_privileges_lists_the_four_column_level_privileges_per_column() throws SQLException {
        try (Statement s = conn.createStatement()) {
            // PG grants INSERT, REFERENCES, SELECT and UPDATE at column granularity; DELETE,
            // TRUNCATE and TRIGGER have no column form and are absent here.
            assertEquals(List.of("code|INSERT", "code|REFERENCES", "code|SELECT", "code|UPDATE",
                            "id|INSERT", "id|REFERENCES", "id|SELECT", "id|UPDATE"),
                    rows(s, "SELECT column_name, privilege_type FROM information_schema.column_privileges"
                            + " WHERE table_schema='isc_s' AND table_name='isc_parent'"
                            + " AND grantee='memgres' ORDER BY column_name, privilege_type", 2));
        }
    }

    @Test
    void role_column_grants_answers_for_a_named_column() throws SQLException {
        try (Statement s = conn.createStatement()) {
            assertRow(s, "SELECT grantor, grantee, is_grantable FROM information_schema.role_column_grants"
                            + " WHERE table_schema='isc_s' AND table_name='isc_parent'"
                            + " AND column_name='code' AND privilege_type='UPDATE'",
                    "memgres", "memgres", "YES");
        }
    }

    @Test
    void routine_privileges_grants_execute_to_the_owner_and_to_public() throws SQLException {
        try (Statement s = conn.createStatement()) {
            assertEquals(List.of("PUBLIC|EXECUTE|NO", "memgres|EXECUTE|YES"),
                    rows(s, "SELECT grantee, privilege_type, is_grantable"
                            + " FROM information_schema.routine_privileges"
                            + " WHERE routine_schema='isc_s' AND routine_name='isc_fn'"
                            + " ORDER BY grantee", 3));
        }
    }

    @Test
    void routine_privileges_names_the_same_specific_name_as_routines() throws SQLException {
        try (Statement s = conn.createStatement()) {
            // The two views have to join, or nothing can get from a privilege to the routine.
            assertRow(s, "SELECT p.routine_name FROM information_schema.routine_privileges p"
                            + " JOIN information_schema.routines r"
                            + "   ON r.specific_schema = p.specific_schema"
                            + "  AND r.specific_name = p.specific_name"
                            + " WHERE p.routine_schema='isc_s' AND p.routine_name='isc_fn'"
                            + "   AND p.grantee='memgres'",
                    "isc_fn");
        }
    }

    @Test
    void role_routine_grants_keeps_the_grant_to_public() throws SQLException {
        try (Statement s = conn.createStatement()) {
            // PG's role_* views keep a grant whose grantor or grantee is a role the session may
            // act as, and every grant to PUBLIC, so this is the base view over again.
            assertEquals(List.of("PUBLIC|EXECUTE|NO", "memgres|EXECUTE|YES"),
                    rows(s, "SELECT grantee, privilege_type, is_grantable"
                            + " FROM information_schema.role_routine_grants"
                            + " WHERE routine_schema='isc_s' AND routine_name='isc_trgfn'"
                            + " ORDER BY is_grantable", 3));
        }
    }

    @Test
    void udt_privileges_reports_type_usage_on_a_relations_row_type() throws SQLException {
        try (Statement s = conn.createStatement()) {
            assertEquals(List.of("PUBLIC|TYPE USAGE|NO", "memgres|TYPE USAGE|YES"),
                    rows(s, "SELECT grantee, privilege_type, is_grantable"
                            + " FROM information_schema.udt_privileges"
                            + " WHERE udt_schema='isc_s' AND udt_name='isc_parent'"
                            + " ORDER BY grantee", 3));
        }
    }

    @Test
    void udt_privileges_reports_type_usage_on_a_composite_type() throws SQLException {
        try (Statement s = conn.createStatement()) {
            assertRow(s, "SELECT privilege_type, is_grantable FROM information_schema.udt_privileges"
                            + " WHERE udt_name='isc_ct' AND grantee='memgres'",
                    "TYPE USAGE", "YES");
        }
    }

    @Test
    void usage_privileges_reports_usage_on_a_domain() throws SQLException {
        try (Statement s = conn.createStatement()) {
            assertEquals(List.of("PUBLIC|DOMAIN|USAGE|NO", "memgres|DOMAIN|USAGE|YES"),
                    rows(s, "SELECT grantee, object_type, privilege_type, is_grantable"
                            + " FROM information_schema.usage_privileges"
                            + " WHERE object_schema='isc_s' AND object_name='isc_dom'"
                            + " ORDER BY grantee", 4));
        }
    }

    @Test
    void data_type_privileges_gives_one_descriptor_per_column_of_a_table() throws SQLException {
        try (Statement s = conn.createStatement()) {
            assertEquals(List.of("TABLE|1", "TABLE|2", "TABLE|3", "TABLE|4",
                            "TABLE|5", "TABLE|6", "TABLE|7", "TABLE|8"),
                    rows(s, "SELECT object_type, dtd_identifier"
                            + " FROM information_schema.data_type_privileges"
                            + " WHERE object_schema='isc_s' AND object_name='isc_child'"
                            + " ORDER BY dtd_identifier", 2));
        }
    }

    @Test
    void data_type_privileges_gives_a_domain_one_descriptor_and_a_routine_one_per_parameter()
            throws SQLException {
        try (Statement s = conn.createStatement()) {
            assertRow(s, "SELECT object_type, dtd_identifier"
                            + " FROM information_schema.data_type_privileges"
                            + " WHERE object_schema='isc_s' AND object_name='isc_dnum'",
                    "DOMAIN", "1");
            // Descriptor 0 is the routine's result, 1 and 2 its two parameters.
            assertEquals(List.of("0", "1", "2"),
                    rows(s, "SELECT p.dtd_identifier FROM information_schema.data_type_privileges p"
                            + " JOIN information_schema.routines r"
                            + "   ON r.specific_schema = p.object_schema"
                            + "  AND r.specific_name = p.object_name"
                            + " WHERE p.object_type='ROUTINE' AND r.routine_name='isc_fn'"
                            + " ORDER BY p.dtd_identifier", 1));
        }
    }

    // ---- type-description views -----------------------------------------------------------

    @Test
    void element_types_names_what_a_text_array_column_holds() throws SQLException {
        try (Statement s = conn.createStatement()) {
            // tags is the fifth column of isc_child, so the collection identifier is 5 and the
            // element's own descriptor is a5.
            assertRow(s, "SELECT object_type, collection_type_identifier, data_type,"
                            + " udt_schema, udt_name, dtd_identifier"
                            + " FROM information_schema.element_types"
                            + " WHERE object_schema='isc_s' AND object_name='isc_child'",
                    "TABLE", "5", "text", "pg_catalog", "text", "a5");
        }
    }

    @Test
    void element_types_names_what_an_integer_array_column_holds() throws SQLException {
        try (Statement s = conn.createStatement()) {
            assertRow(s, "SELECT collection_type_identifier, data_type, udt_name, dtd_identifier"
                            + " FROM information_schema.element_types"
                            + " WHERE object_schema='isc_s' AND object_name='isc_types'",
                    "3", "integer", "int4", "a3");
        }
    }

    @Test
    void element_types_joins_back_to_the_array_column_it_describes() throws SQLException {
        try (Statement s = conn.createStatement()) {
            // This is the join a driver makes to build an array decoder: from the ARRAY column
            // in columns to its element type in element_types, on the dtd_identifier.
            assertRow(s, "SELECT c.column_name, c.data_type, e.udt_name"
                            + " FROM information_schema.columns c"
                            + " JOIN information_schema.element_types e"
                            + "   ON e.object_catalog = c.table_catalog"
                            + "  AND e.object_schema = c.table_schema"
                            + "  AND e.object_name = c.table_name"
                            + "  AND e.object_type = 'TABLE'"
                            + "  AND e.collection_type_identifier = c.dtd_identifier"
                            + " WHERE c.table_schema='isc_s' AND c.table_name='isc_child'",
                    "tags", "ARRAY", "text");
        }
    }

    @Test
    void attributes_describes_every_field_of_a_composite_type() throws SQLException {
        try (Statement s = conn.createStatement()) {
            assertEquals(List.of(
                            "x|1|integer|null|null|32|2|0|null|int4|1",
                            "y|2|character varying|3|12|null|null|null|null|varchar|2",
                            "z|3|timestamp without time zone|null|null|null|null|null|2|timestamp|3"),
                    rows(s, "SELECT attribute_name, ordinal_position, data_type,"
                            + " character_maximum_length, character_octet_length,"
                            + " numeric_precision, numeric_precision_radix, numeric_scale,"
                            + " datetime_precision, attribute_udt_name, dtd_identifier"
                            + " FROM information_schema.attributes WHERE udt_name='isc_ct'"
                            + " ORDER BY ordinal_position", 11));
        }
    }

    @Test
    void attributes_says_a_field_is_not_a_derived_reference() throws SQLException {
        try (Statement s = conn.createStatement()) {
            assertRow(s, "SELECT is_nullable, attribute_udt_schema, is_derived_reference_attribute"
                            + " FROM information_schema.attributes"
                            + " WHERE udt_name='isc_ct' AND attribute_name='y'",
                    "YES", "pg_catalog", "NO");
        }
    }

    @Test
    void user_defined_types_lists_a_composite_type_as_structured_and_instantiable() throws SQLException {
        try (Statement s = conn.createStatement()) {
            // PG answers the first five columns for a composite type and leaves the rest null:
            // is_final and the ordering columns describe a DISTINCT type, which PG has none of.
            assertRow(s, "SELECT user_defined_type_category, is_instantiable, is_final,"
                            + " ordering_form, reference_type, data_type"
                            + " FROM information_schema.user_defined_types"
                            + " WHERE user_defined_type_name='isc_ct'",
                    "STRUCTURED", "YES", null, null, null, null);
        }
    }

    @Test
    void column_udt_usage_names_the_underlying_type_of_every_column() throws SQLException {
        try (Statement s = conn.createStatement()) {
            // A domain column reports the domain's base type here; the domain itself is in
            // column_domain_usage.
            assertEquals(List.of("amt|pg_catalog|numeric", "cid|pg_catalog|int4",
                            "created|pg_catalog|timestamptz", "flag|pg_catalog|bool",
                            "note|pg_catalog|varchar", "pid|pg_catalog|int4",
                            "tags|pg_catalog|_text", "ts|pg_catalog|timestamp"),
                    rows(s, "SELECT column_name, udt_schema, udt_name"
                            + " FROM information_schema.column_udt_usage"
                            + " WHERE table_schema='isc_s' AND table_name='isc_child'"
                            + " ORDER BY column_name", 3));
        }
    }

    @Test
    void column_domain_usage_names_the_columns_typed_by_a_domain() throws SQLException {
        try (Statement s = conn.createStatement()) {
            assertEquals(List.of("isc_dom|isc_child|note", "isc_dnum|isc_types|c_dnum",
                            "isc_dom|isc_types|c_dom"),
                    rows(s, "SELECT domain_name, table_name, column_name"
                            + " FROM information_schema.column_domain_usage"
                            + " WHERE domain_schema='isc_s' ORDER BY table_name, column_name", 3));
        }
    }

    @Test
    void domain_udt_usage_names_the_base_type_of_a_domain() throws SQLException {
        try (Statement s = conn.createStatement()) {
            assertEquals(List.of("isc_dnum|pg_catalog|numeric", "isc_dom|pg_catalog|varchar"),
                    rows(s, "SELECT domain_name, udt_schema, udt_name"
                            + " FROM information_schema.domain_udt_usage"
                            + " WHERE domain_schema='isc_s' ORDER BY domain_name", 3));
        }
    }

    // ---- dependency views -----------------------------------------------------------------

    @Test
    void view_table_usage_names_the_relation_a_view_reads() throws SQLException {
        try (Statement s = conn.createStatement()) {
            assertEquals(List.of("isc_v|isc_s|isc_parent", "isc_v2|isc_s|isc_parent"),
                    rows(s, "SELECT view_name, table_schema, table_name"
                            + " FROM information_schema.view_table_usage"
                            + " WHERE view_schema='isc_s' ORDER BY view_name", 3));
        }
    }

    @Test
    void view_column_usage_names_the_columns_a_view_reads() throws SQLException {
        try (Statement s = conn.createStatement()) {
            assertEquals(List.of("isc_v|isc_parent|code", "isc_v|isc_parent|id",
                            "isc_v2|isc_parent|id"),
                    rows(s, "SELECT view_name, table_name, column_name"
                            + " FROM information_schema.view_column_usage"
                            + " WHERE view_schema='isc_s' ORDER BY view_name, column_name", 3));
        }
    }

    @Test
    void constraint_table_usage_names_the_table_a_foreign_key_points_at() throws SQLException {
        try (Statement s = conn.createStatement()) {
            // The FK lives on isc_child and PG names isc_parent here — this is the query that
            // answers "which constraints depend on this table" before a DROP.
            assertRow(s, "SELECT table_schema, table_name FROM information_schema.constraint_table_usage"
                            + " WHERE constraint_name = 'isc_child_pid_fkey'",
                    "isc_s", "isc_parent");
        }
    }

    @Test
    void constraint_table_usage_covers_only_the_key_constraints() throws SQLException {
        try (Statement s = conn.createStatement()) {
            // PG lists PRIMARY KEY, UNIQUE and FOREIGN KEY here and nothing else: no CHECK, and
            // none of the NOT NULL constraints PG 18 synthesizes.
            assertEquals(List.of("isc_child_pid_fkey|isc_parent", "isc_child_pkey|isc_child",
                            "isc_parent_code_key|isc_parent", "isc_parent_pkey|isc_parent"),
                    rows(s, "SELECT constraint_name, table_name"
                            + " FROM information_schema.constraint_table_usage"
                            + " WHERE table_schema='isc_s' ORDER BY constraint_name", 2));
        }
    }

    @Test
    void domain_constraints_names_the_check_a_domain_carries() throws SQLException {
        try (Statement s = conn.createStatement()) {
            assertRow(s, "SELECT constraint_schema, constraint_name, domain_schema, domain_name,"
                            + " is_deferrable, initially_deferred"
                            + " FROM information_schema.domain_constraints WHERE domain_schema='isc_s'",
                    "isc_s", "isc_dom_check", "isc_s", "isc_dom", "NO", "NO");
        }
    }

    @Test
    void check_constraints_files_a_domain_check_under_the_domains_own_schema() throws SQLException {
        try (Statement s = conn.createStatement()) {
            assertRow(s, "SELECT check_clause FROM information_schema.check_constraints"
                            + " WHERE constraint_schema='isc_s' AND constraint_name='isc_dom_check'",
                    "((VALUE)::text <> ''::text)");
        }
    }

    @Test
    void triggered_update_columns_names_the_column_an_update_of_trigger_watches() throws SQLException {
        try (Statement s = conn.createStatement()) {
            assertRow(s, "SELECT trigger_name, event_object_schema, event_object_table,"
                            + " event_object_column FROM information_schema.triggered_update_columns"
                            + " WHERE trigger_schema='isc_s'",
                    "isc_trg", "isc_s", "isc_parent", "code");
        }
    }

    // ---- column values that were wrong rather than absent -----------------------------------

    @Test
    void columns_reports_the_bounds_of_an_integer_identity_column() throws SQLException {
        try (Statement s = conn.createStatement()) {
            // The ceiling is the column's own type: an int identity stops at 2147483647.
            assertRow(s, "SELECT is_identity, identity_generation, identity_start,"
                            + " identity_increment, identity_maximum, identity_minimum, identity_cycle"
                            + " FROM information_schema.columns"
                            + " WHERE table_schema='isc_s' AND table_name='isc_child' AND column_name='cid'",
                    "YES", "BY DEFAULT", "1", "1", "2147483647", "1", "NO");
        }
    }

    @Test
    void columns_reports_identity_cycle_on_a_column_that_is_not_an_identity() throws SQLException {
        try (Statement s = conn.createStatement()) {
            assertRow(s, "SELECT is_identity, identity_generation, identity_start, identity_cycle"
                            + " FROM information_schema.columns"
                            + " WHERE table_schema='isc_s' AND table_name='isc_child' AND column_name='pid'",
                    "NO", null, null, "NO");
        }
    }

    @Test
    void columns_reports_the_declared_width_of_a_bit_string() throws SQLException {
        try (Statement s = conn.createStatement()) {
            assertEquals(List.of("c_bit8|bit|bit|8|null", "c_vbit|bit varying|varbit|9|null"),
                    rows(s, "SELECT column_name, data_type, udt_name, character_maximum_length,"
                            + " character_octet_length FROM information_schema.columns"
                            + " WHERE table_schema='isc_s' AND table_name='isc_types'"
                            + " AND column_name IN ('c_bit8','c_vbit') ORDER BY column_name", 5));
        }
    }

    @Test
    void views_reports_the_check_option_a_view_was_created_with() throws SQLException {
        try (Statement s = conn.createStatement()) {
            assertEquals(List.of("isc_v|NONE", "isc_v2|CASCADED"),
                    rows(s, "SELECT table_name, check_option FROM information_schema.views"
                            + " WHERE table_schema='isc_s' ORDER BY table_name", 2));
        }
    }

    @Test
    void triggers_writes_the_trigger_function_schema_qualified() throws SQLException {
        try (Statement s = conn.createStatement()) {
            assertEquals(List.of("INSERT|EXECUTE FUNCTION isc_s.isc_trgfn()",
                            "UPDATE|EXECUTE FUNCTION isc_s.isc_trgfn()"),
                    rows(s, "SELECT event_manipulation, action_statement FROM information_schema.triggers"
                            + " WHERE trigger_schema='isc_s' ORDER BY event_manipulation", 2));
        }
    }

    @Test
    void routines_calls_a_sql_language_function_body_sql() throws SQLException {
        try (Statement s = conn.createStatement()) {
            assertRow(s, "SELECT routine_body, external_language, data_type, type_udt_schema,"
                            + " type_udt_name FROM information_schema.routines"
                            + " WHERE routine_schema='isc_s' AND routine_name='isc_fn'",
                    "SQL", "SQL", "integer", "pg_catalog", "int4");
        }
    }

    @Test
    void routines_calls_a_plpgsql_function_body_external() throws SQLException {
        try (Statement s = conn.createStatement()) {
            assertRow(s, "SELECT routine_body, external_language, data_type, type_udt_name"
                            + " FROM information_schema.routines"
                            + " WHERE routine_schema='isc_s' AND routine_name='isc_trgfn'",
                    "EXTERNAL", "PLPGSQL", "trigger", "trigger");
        }
    }

    @Test
    void routines_leaves_the_columns_postgresql_has_no_answer_for_null() throws SQLException {
        try (Statement s = conn.createStatement()) {
            assertRow(s, "SELECT is_null_call, is_user_defined_cast, is_implicitly_invocable,"
                            + " new_savepoint_level, security_type FROM information_schema.routines"
                            + " WHERE routine_schema='isc_s' AND routine_name='isc_fn'",
                    "NO", null, null, null, "INVOKER");
        }
    }

    @Test
    void parameters_renders_a_text_default_with_its_cast() throws SQLException {
        try (Statement s = conn.createStatement()) {
            assertEquals(List.of("a|1|integer|null", "b|2|text|'x'::text"),
                    rows(s, "SELECT p.parameter_name, p.ordinal_position, p.data_type,"
                            + " p.parameter_default FROM information_schema.parameters p"
                            + " JOIN information_schema.routines r"
                            + "   ON r.specific_schema = p.specific_schema"
                            + "  AND r.specific_name = p.specific_name"
                            + " WHERE r.routine_name='isc_fn' ORDER BY p.ordinal_position", 4));
        }
    }

    @Test
    void schemata_hands_the_public_schema_to_the_database_owner_pseudo_role() throws SQLException {
        try (Statement s = conn.createStatement()) {
            assertRow(s, "SELECT schema_owner FROM information_schema.schemata"
                            + " WHERE schema_name = 'public'",
                    "pg_database_owner");
        }
    }

    @Test
    void character_sets_names_no_default_collation() throws SQLException {
        try (Statement s = conn.createStatement()) {
            assertRow(s, "SELECT character_set_catalog, character_set_schema, character_set_name,"
                            + " character_repertoire, form_of_use, default_collate_schema,"
                            + " default_collate_name FROM information_schema.character_sets",
                    null, null, "UTF8", "UCS", "UTF8", null, null);
        }
    }

    @Test
    void collations_lists_the_built_in_unicode_collation() throws SQLException {
        try (Statement s = conn.createStatement()) {
            assertEquals(List.of("C|NO PAD", "POSIX|NO PAD", "ucs_basic|NO PAD", "unicode|NO PAD"),
                    rows(s, "SELECT collation_name, pad_attribute FROM information_schema.collations"
                            + " WHERE collation_name IN ('C','POSIX','ucs_basic','unicode')"
                            + " ORDER BY collation_name", 2));
        }
    }

    // ---- the constant tables PostgreSQL ships ------------------------------------------------

    @Test
    void sql_parts_lists_the_named_parts_of_the_standard() throws SQLException {
        try (Statement s = conn.createStatement()) {
            assertEquals(List.of("1|Framework (SQL/Framework)|NO",
                            "2|Foundation (SQL/Foundation)|NO",
                            "11|Information and Definition Schema (SQL/Schemata)|NO",
                            "16|Property Graph Queries (SQL/PGQ)|NO"),
                    rows(s, "SELECT feature_id, feature_name, is_supported"
                            + " FROM information_schema.sql_parts"
                            + " WHERE feature_id IN ('1','2','11','16')"
                            + " ORDER BY feature_id::int", 3));
        }
    }

    @Test
    void sql_sizing_reports_the_identifier_length_limit() throws SQLException {
        try (Statement s = conn.createStatement()) {
            assertRow(s, "SELECT sizing_name, supported_value, comments"
                            + " FROM information_schema.sql_sizing WHERE sizing_id = 10005",
                    "MAXIMUM IDENTIFIER LENGTH", "63", "Might be less, depending on character set.");
        }
    }

    @Test
    void sql_sizing_reports_the_column_limits_of_a_table_and_a_select() throws SQLException {
        try (Statement s = conn.createStatement()) {
            assertEquals(List.of("100|MAXIMUM COLUMNS IN SELECT|1664",
                            "101|MAXIMUM COLUMNS IN TABLE|1600"),
                    rows(s, "SELECT sizing_id, sizing_name, supported_value"
                            + " FROM information_schema.sql_sizing WHERE sizing_id IN (100, 101)"
                            + " ORDER BY sizing_id", 3));
        }
    }

    @Test
    void sql_implementation_info_names_the_dbms_and_its_transaction_behaviour() throws SQLException {
        try (Statement s = conn.createStatement()) {
            assertRow(s, "SELECT implementation_info_name, character_value"
                            + " FROM information_schema.sql_implementation_info"
                            + " WHERE implementation_info_id = '17'",
                    "DBMS NAME", "PostgreSQL");
            assertRow(s, "SELECT implementation_info_name, integer_value, comments"
                            + " FROM information_schema.sql_implementation_info"
                            + " WHERE implementation_info_id = '26'",
                    "DEFAULT TRANSACTION ISOLATION", "2", "READ COMMITTED; user-settable");
        }
    }

    // ---- the helper relations information_schema is built on ---------------------------------

    @Test
    void tables_lists_the_underscore_prefixed_helper_views() throws SQLException {
        try (Statement s = conn.createStatement()) {
            assertEquals(List.of("_pg_foreign_data_wrappers|VIEW", "_pg_foreign_servers|VIEW",
                            "_pg_foreign_table_columns|VIEW", "_pg_foreign_tables|VIEW",
                            "_pg_user_mappings|VIEW"),
                    rows(s, "SELECT table_name, table_type FROM information_schema.tables"
                            + " WHERE table_schema='information_schema' AND table_name LIKE '\\_pg\\_%'"
                            + " ORDER BY table_name", 2));
        }
    }

    @Test
    void columns_describes_the_helper_views_it_now_lists() throws SQLException {
        try (Statement s = conn.createStatement()) {
            assertEquals(List.of("nspname|1", "relname|2", "attname|3", "attfdwoptions|4"),
                    rows(s, "SELECT column_name, ordinal_position FROM information_schema.columns"
                            + " WHERE table_schema='information_schema'"
                            + " AND table_name='_pg_foreign_table_columns'"
                            + " ORDER BY ordinal_position", 2));
        }
    }

    // ---- the catalog still answers the queries that join it ----------------------------------

    @Test
    void a_column_can_still_be_followed_from_tables_through_columns_to_its_privileges()
            throws SQLException {
        try (Statement s = conn.createStatement()) {
            assertRow(s, "SELECT t.table_type, c.data_type, cp.privilege_type"
                            + " FROM information_schema.tables t"
                            + " JOIN information_schema.columns c"
                            + "   ON c.table_schema = t.table_schema AND c.table_name = t.table_name"
                            + " JOIN information_schema.column_privileges cp"
                            + "   ON cp.table_schema = c.table_schema"
                            + "  AND cp.table_name = c.table_name"
                            + "  AND cp.column_name = c.column_name"
                            + " WHERE t.table_schema='isc_s' AND t.table_name='isc_parent'"
                            + "   AND c.column_name='code' AND cp.privilege_type='SELECT'"
                            + "   AND cp.grantee='memgres'",
                    "BASE TABLE", "character varying", "SELECT");
        }
    }

    @Test
    void a_view_can_still_be_followed_to_the_column_of_the_table_underneath_it() throws SQLException {
        try (Statement s = conn.createStatement()) {
            assertRow(s, "SELECT v.check_option, c.data_type"
                            + " FROM information_schema.views v"
                            + " JOIN information_schema.view_column_usage u"
                            + "   ON u.view_schema = v.table_schema AND u.view_name = v.table_name"
                            + " JOIN information_schema.columns c"
                            + "   ON c.table_schema = u.table_schema AND c.table_name = u.table_name"
                            + "  AND c.column_name = u.column_name"
                            + " WHERE v.table_schema='isc_s' AND v.table_name='isc_v2'",
                    "CASCADED", "integer");
        }
    }

    // ---- helpers ------------------------------------------------------------------------------

    private static void assertRow(Statement s, String sql, String... expected) throws SQLException {
        try (ResultSet rs = s.executeQuery(sql)) {
            assertTrue(rs.next(), "no row for: " + sql);
            for (int i = 0; i < expected.length; i++) {
                assertEquals(expected[i], rs.getString(i + 1),
                        "column " + (i + 1) + " of: " + sql);
            }
            assertFalse(rs.next(), "more than one row for: " + sql);
        }
    }

    /** Every row of the result, each rendered as its first {@code n} columns joined by "|". */
    private static List<String> rows(Statement s, String sql, int n) throws SQLException {
        List<String> out = new ArrayList<>();
        try (ResultSet rs = s.executeQuery(sql)) {
            while (rs.next()) {
                StringBuilder b = new StringBuilder();
                for (int i = 1; i <= n; i++) {
                    if (i > 1) b.append('|');
                    b.append(rs.getString(i));
                }
                out.add(b.toString());
            }
        }
        return out;
    }
}
