package com.memgres.client;

import com.memgres.core.Memgres;
import org.junit.jupiter.api.*;

import java.sql.*;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Results are computed in the width they are declared in, and stop at its bounds.
 *
 * <p>A shift was computed in {@code long} and widened whenever the answer did not fit an int, so
 * {@code 1::int4 << 31} answered 2147483648 rather than the int4 it is. A sequence added its
 * increment before it compared anything with its maximum, so one sitting on the largest bigint
 * handed out the smallest. An identity column's sequence carried no bound at all, so an int column
 * was handed a value outside integer. And several counters overflowed silently where PostgreSQL
 * raises.
 */
class IntegerBoundsAndShiftsTest {

    static Memgres memgres;
    static Connection conn;

    @BeforeAll
    static void setUp() throws Exception {
        memgres = Memgres.builder().port(0).build().start();
        conn = DriverManager.getConnection(memgres.getJdbcUrl(), memgres.getUser(),
                memgres.getPassword());
    }

    @AfterAll
    static void tearDown() throws Exception {
        if (conn != null) conn.close();
        if (memgres != null) memgres.close();
    }

    private static String scalar(String sql) throws SQLException {
        try (Statement st = conn.createStatement(); ResultSet rs = st.executeQuery(sql)) {
            assertTrue(rs.next(), "expected a row from: " + sql);
            return rs.getString(1);
        }
    }

    private static void exec(String sql) throws SQLException {
        try (Statement st = conn.createStatement()) { st.execute(sql); }
    }

    private static SQLException refused(String sql) {
        return assertThrows(SQLException.class, () -> exec(sql), sql);
    }

    /** A shift happens in the width of the value being shifted. */
    @Test
    void shiftsStayInTheirWidth() throws Exception {
        assertEquals("-2147483648", scalar("SELECT 1::int4 << 31"));
        assertEquals("1", scalar("SELECT 1 << 32"));
        assertEquals("4", scalar("SELECT 1024 >> 40"));
        assertEquals("-2147483648", scalar("SELECT 1 << -1"));
        assertEquals("-32768", scalar("SELECT 1::int2 << 15"));
        assertEquals("4611686018427387904", scalar("SELECT 1::int8 << 62"));
    }

    /** A sequence that has run out says so. */
    @Test
    void aSequenceStopsAtItsMaximum() throws Exception {
        exec("CREATE SEQUENCE zz_ib_s START 9223372036854775807");
        try {
            assertEquals("9223372036854775807", scalar("SELECT nextval('zz_ib_s')"));
            SQLException e = assertThrows(SQLException.class,
                    () -> scalar("SELECT nextval('zz_ib_s')"));
            assertEquals("2200H", e.getSQLState());
            assertTrue(e.getMessage().contains("reached maximum value"));
        } finally {
            exec("DROP SEQUENCE IF EXISTS zz_ib_s");
        }
    }

    /** An identity column's sequence is bounded by the column's own type. */
    @Test
    void anIdentitySequenceIsBoundedByItsColumn() throws Exception {
        exec("CREATE TABLE zz_ib_id (a int GENERATED BY DEFAULT AS IDENTITY, b text)");
        try {
            assertEquals("2147483647", scalar("SELECT max_value FROM pg_sequences"
                    + " WHERE sequencename = 'zz_ib_id_a_seq'"));
            exec("SELECT setval('zz_ib_id_a_seq', 2147483647)");
            SQLException e = refused("INSERT INTO zz_ib_id (b) VALUES ('x')");
            assertEquals("2200H", e.getSQLState());
            assertEquals("0", scalar("SELECT count(*) FROM zz_ib_id"));
        } finally {
            exec("DROP TABLE IF EXISTS zz_ib_id");
        }
    }

    /** An xmltable column is read in the type it declares. */
    @Test
    void xmltableReadsItsDeclaredTypes() throws Exception {
        assertEquals("9999999999", scalar("SELECT v FROM xmltable('/r/x'"
                + " PASSING '<r><x><v>9999999999</v></x></r>' COLUMNS v bigint PATH 'v')"));
    }

    /** SKIP LOCKED with an OFFSET and no LIMIT still returns the rows past the offset. */
    @Test
    void skipLockedWithAnOffsetStillAnswers() throws Exception {
        exec("CREATE TEMP TABLE zz_ib_sk (a int)");
        exec("INSERT INTO zz_ib_sk VALUES (1),(2),(3),(4),(5)");
        try (Statement st = conn.createStatement();
             ResultSet rs = st.executeQuery(
                     "SELECT a FROM zz_ib_sk ORDER BY a OFFSET 2 FOR UPDATE SKIP LOCKED")) {
            assertTrue(rs.next());
            assertEquals(3, rs.getInt(1));
            assertTrue(rs.next());
            assertTrue(rs.next());
            assertFalse(rs.next());
        }
    }

    /** GROUPING answers an int4 bitmask, so it has room for fewer than 32 arguments. */
    @Test
    void groupingHasRoomForThirtyOneArguments() throws Exception {
        exec("CREATE TEMP TABLE zz_ib_g (a int)");
        exec("INSERT INTO zz_ib_g VALUES (1)");
        StringBuilder args = new StringBuilder("a");
        for (int i = 1; i < 32; i++) args.append(",a");
        SQLException e = assertThrows(SQLException.class,
                () -> scalar("SELECT grouping(" + args + ") FROM zz_ib_g GROUP BY a"));
        assertEquals("54023", e.getSQLState());
        assertTrue(e.getMessage().contains("fewer than 32 arguments"));
        assertEquals("0", scalar("SELECT grouping(a) FROM zz_ib_g GROUP BY a"));
    }

    /** A length in octets that no integer holds is reported as the overflow it is. */
    @Test
    void anOctetLengthPastAnIntegerRaises() {
        SQLException e = assertThrows(SQLException.class,
                () -> scalar("SELECT information_schema._pg_char_octet_length(1043, 2147483647)"));
        assertEquals("22003", e.getSQLState());
        assertTrue(e.getMessage().contains("integer out of range"));
    }
}
