package com.memgres.client;

import com.memgres.core.Memgres;
import org.junit.jupiter.api.*;

import java.sql.*;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Validation permissiveness tests.
 * Ensures Memgres correctly rejects SQL that PostgreSQL 18 rejects.
 * Each test verifies that invalid SQL produces an error (any error, or a specific SQLSTATE).
 */
class ValidationPermissivenessTest {

    static Memgres memgres;
    static Connection conn;

    @BeforeAll
    static void setUp() throws Exception {
        memgres = Memgres.builder().port(0).build().start();
        conn = DriverManager.getConnection(
                memgres.getJdbcUrl(),
                memgres.getUser(), memgres.getPassword());
        conn.setAutoCommit(true);

        // === Section 1: Partition tables ===
        exec("CREATE TABLE vp_range_parent (id INT, val TEXT) PARTITION BY RANGE (id)");
        exec("CREATE TABLE vp_range_p1 PARTITION OF vp_range_parent FOR VALUES FROM (1) TO (100)");
        exec("CREATE TABLE vp_range_p2 PARTITION OF vp_range_parent FOR VALUES FROM (100) TO (200)");

        exec("CREATE TABLE vp_list_parent (region TEXT, val INT) PARTITION BY LIST (region)");
        exec("CREATE TABLE vp_list_east PARTITION OF vp_list_parent FOR VALUES IN ('east')");
        exec("CREATE TABLE vp_list_west PARTITION OF vp_list_parent FOR VALUES IN ('west')");

        exec("CREATE TABLE vp_hash_parent (id INT, val TEXT) PARTITION BY HASH (id)");
        exec("CREATE TABLE vp_hash_p0 PARTITION OF vp_hash_parent FOR VALUES WITH (MODULUS 4, REMAINDER 0)");
        exec("CREATE TABLE vp_hash_p1 PARTITION OF vp_hash_parent FOR VALUES WITH (MODULUS 4, REMAINDER 1)");

        // === Section 2: GENERATED ALWAYS AS IDENTITY ===
        exec("CREATE TABLE vp_ident_always (id INT GENERATED ALWAYS AS IDENTITY, val TEXT)");
        exec("CREATE TABLE vp_ident_default (id INT GENERATED BY DEFAULT AS IDENTITY, val TEXT)");

        // === Section 3: GENERATED ALWAYS AS (expression) STORED ===
        exec("CREATE TABLE vp_generated (a INT, b INT, c INT GENERATED ALWAYS AS (a + b) STORED)");

        // === Section 4: View WITH CHECK OPTION ===
        exec("CREATE TABLE vp_view_base (id SERIAL PRIMARY KEY, status TEXT, val INT)");
        exec("INSERT INTO vp_view_base (status, val) VALUES ('active', 10), ('active', 20), ('inactive', 30)");
        exec("CREATE VIEW vp_active_view AS SELECT * FROM vp_view_base WHERE status = 'active' WITH CHECK OPTION");
        exec("CREATE VIEW vp_val_view AS SELECT * FROM vp_view_base WHERE val > 0 WITH LOCAL CHECK OPTION");
        // Note: CASCADED is not a registered keyword in the lexer, so
        // WITH CASCADED CHECK OPTION fails to parse. We use the default
        // (WITH CHECK OPTION = CASCADED per SQL standard) for the cascaded view.
        exec("CREATE VIEW vp_cascaded_view AS SELECT * FROM vp_active_view WHERE val < 100 WITH CHECK OPTION");

        // === Section 5: Prepared statement tables ===
        exec("CREATE TABLE vp_prep (id INT, val TEXT)");

        // === Section 6: Function/Procedure argument validation ===
        exec("CREATE FUNCTION vp_add(a INT, b INT) RETURNS INT LANGUAGE SQL AS $$ SELECT a + b $$");
        exec("CREATE FUNCTION vp_greet(name TEXT) RETURNS TEXT LANGUAGE SQL AS $$ SELECT 'Hello ' || name $$");
        exec("CREATE PROCEDURE vp_do_nothing() LANGUAGE SQL AS $$ SELECT 1 $$");

        // === Section 8: Trigger tables ===
        exec("CREATE TABLE vp_trig_t (id INT, val TEXT, updated_at TIMESTAMP)");
        exec("CREATE FUNCTION vp_trig_fn() RETURNS TRIGGER LANGUAGE plpgsql AS $$ BEGIN RETURN NEW; END $$");

        // === Section 9: Index tables ===
        exec("CREATE TABLE vp_idx_t (id INT, name TEXT, val INT)");

        // === Section 10: ALTER TABLE tables ===
        exec("CREATE TABLE vp_alter_t (id INT PRIMARY KEY, name TEXT, val INT)");
        exec("CREATE VIEW vp_alter_v AS SELECT id, name FROM vp_alter_t");
        exec("CREATE INDEX vp_alter_idx ON vp_alter_t (val)");

        // === Section 15: Sequences ===
        exec("CREATE SEQUENCE vp_seq START 1");

        // === Section 16: Schema evolution ===
        exec("CREATE TABLE vp_evolve (id INT, val INT CHECK (val > 0))");
        exec("INSERT INTO vp_evolve VALUES (1, 10)");
    }

    @AfterAll
    static void tearDown() throws Exception {
        if (conn != null) {
            try {
                // Clean up in reverse order
                exec("DROP TABLE IF EXISTS vp_evolve CASCADE");
                exec("DROP SEQUENCE IF EXISTS vp_seq CASCADE");
                exec("DROP TABLE IF EXISTS vp_alter_t CASCADE");
                exec("DROP VIEW IF EXISTS vp_alter_v CASCADE");
                exec("DROP TABLE IF EXISTS vp_idx_t CASCADE");
                exec("DROP TABLE IF EXISTS vp_trig_t CASCADE");
                exec("DROP FUNCTION IF EXISTS vp_trig_fn() CASCADE");
                exec("DROP TABLE IF EXISTS vp_prep CASCADE");
                exec("DROP VIEW IF EXISTS vp_cascaded_view CASCADE");
                exec("DROP VIEW IF EXISTS vp_val_view CASCADE");
                exec("DROP VIEW IF EXISTS vp_active_view CASCADE");
                exec("DROP TABLE IF EXISTS vp_view_base CASCADE");
                exec("DROP TABLE IF EXISTS vp_generated CASCADE");
                exec("DROP TABLE IF EXISTS vp_ident_always CASCADE");
                exec("DROP TABLE IF EXISTS vp_ident_default CASCADE");
                exec("DROP TABLE IF EXISTS vp_hash_p0 CASCADE");
                exec("DROP TABLE IF EXISTS vp_hash_p1 CASCADE");
                exec("DROP TABLE IF EXISTS vp_hash_parent CASCADE");
                exec("DROP TABLE IF EXISTS vp_list_east CASCADE");
                exec("DROP TABLE IF EXISTS vp_list_west CASCADE");
                exec("DROP TABLE IF EXISTS vp_list_parent CASCADE");
                exec("DROP TABLE IF EXISTS vp_range_p1 CASCADE");
                exec("DROP TABLE IF EXISTS vp_range_p2 CASCADE");
                exec("DROP TABLE IF EXISTS vp_range_parent CASCADE");
                exec("DROP FUNCTION IF EXISTS vp_add(INT, INT) CASCADE");
                exec("DROP FUNCTION IF EXISTS vp_greet(TEXT) CASCADE");
                exec("DROP PROCEDURE IF EXISTS vp_do_nothing() CASCADE");
                exec("DEALLOCATE ALL");
            } catch (SQLException ignored) {}
            conn.close();
        }
        if (memgres != null) memgres.close();
    }

    static void exec(String sql) throws SQLException {
        try (Statement s = conn.createStatement()) { s.execute(sql); }
    }

    static String q(String sql) throws SQLException {
        try (Statement s = conn.createStatement(); ResultSet rs = s.executeQuery(sql)) {
            return rs.next() ? rs.getString(1) : null;
        }
    }

    /** Assert that the given SQL fails with any error. */
    static void assertSqlFails(String sql) {
        assertThrows(SQLException.class, () -> exec(sql), "Expected error for: " + sql);
    }

    /** Assert that the given SQL fails with a specific SQLSTATE. */
    static void assertSqlState(String sql, String expectedState) {
        try {
            exec(sql);
            fail("Expected error with SQLSTATE " + expectedState + " for: " + sql);
        } catch (SQLException e) {
            assertEquals(expectedState, e.getSQLState(),
                    "Wrong SQLSTATE for: " + sql + ", got: " + e.getMessage());
        }
    }

    // ========================================================================
    // Section 1: Partition Bound Validation
    // ========================================================================

    @Test
    void partition_range_overlapping_bounds_rejected() {
        // Range 50-150 overlaps with existing p1 (1-100)
        assertSqlFails(
                "CREATE TABLE vp_range_overlap PARTITION OF vp_range_parent FOR VALUES FROM (50) TO (150)");
    }

    @Test
    void partition_range_exact_overlap_rejected() {
        // Range 1-100 exactly matches p1
        assertSqlFails(
                "CREATE TABLE vp_range_exact PARTITION OF vp_range_parent FOR VALUES FROM (1) TO (100)");
    }

    @Test
    void partition_range_subsumed_overlap_rejected() {
        // Range 10-50 is fully within p1 (1-100)
        assertSqlFails(
                "CREATE TABLE vp_range_sub PARTITION OF vp_range_parent FOR VALUES FROM (10) TO (50)");
    }

    @Test
    void partition_list_duplicate_value_rejected() {
        // 'east' is already covered by vp_list_east
        assertSqlFails(
                "CREATE TABLE vp_list_dup PARTITION OF vp_list_parent FOR VALUES IN ('east')");
    }

    @Test
    void partition_list_partially_duplicate_value_rejected() {
        // 'east' overlaps even when combined with new value
        assertSqlFails(
                "CREATE TABLE vp_list_partial PARTITION OF vp_list_parent FOR VALUES IN ('north', 'east')");
    }

    @Test
    void partition_hash_invalid_modulus_rejected() {
        // Modulus 0 is invalid
        assertSqlFails(
                "CREATE TABLE vp_hash_bad PARTITION OF vp_hash_parent FOR VALUES WITH (MODULUS 0, REMAINDER 0)");
    }

    @Test
    void partition_hash_remainder_exceeds_modulus_rejected() {
        // Remainder must be < modulus
        assertSqlFails(
                "CREATE TABLE vp_hash_bad2 PARTITION OF vp_hash_parent FOR VALUES WITH (MODULUS 4, REMAINDER 5)");
    }

    @Test
    void partition_hash_negative_remainder_rejected() {
        assertSqlFails(
                "CREATE TABLE vp_hash_neg PARTITION OF vp_hash_parent FOR VALUES WITH (MODULUS 4, REMAINDER -1)");
    }

    @Test
    void partition_hash_duplicate_remainder_rejected() {
        // Remainder 0 with modulus 4 is already taken by vp_hash_p0
        assertSqlFails(
                "CREATE TABLE vp_hash_dup PARTITION OF vp_hash_parent FOR VALUES WITH (MODULUS 4, REMAINDER 0)");
    }

    @Test
    void partition_insert_no_matching_partition_rejected() {
        // Value 500 has no partition (range only covers 1-200)
        assertSqlFails("INSERT INTO vp_range_parent VALUES (500, 'out of range')");
    }

    @Test
    void partition_insert_negative_no_matching_partition_rejected() {
        // Value -1 has no partition
        assertSqlFails("INSERT INTO vp_range_parent VALUES (-1, 'negative')");
    }

    @Test
    void partition_list_insert_unmatched_value_rejected() {
        // 'south' is not covered by any partition
        assertSqlFails("INSERT INTO vp_list_parent VALUES ('south', 1)");
    }

    @Test
    void partition_list_insert_null_no_null_partition_rejected() {
        // NULL not covered by any partition
        assertSqlFails("INSERT INTO vp_list_parent VALUES (NULL, 1)");
    }

    @Test
    void partition_detach_nonexistent_rejected() {
        assertSqlFails("ALTER TABLE vp_range_parent DETACH PARTITION vp_nonexistent");
    }

    @Test
    void partition_attach_already_attached_rejected() throws SQLException {
        // vp_range_p1 is already a partition of vp_range_parent
        assertSqlFails(
                "ALTER TABLE vp_range_parent ATTACH PARTITION vp_range_p1 FOR VALUES FROM (1) TO (100)");
    }

    @Test
    void partition_attach_overlapping_bounds_rejected() throws SQLException {
        exec("CREATE TABLE vp_attach_overlap (id INT, val TEXT)");
        try {
            // Bounds 50-150 overlap with existing p1 (1-100)
            assertSqlFails(
                    "ALTER TABLE vp_range_parent ATTACH PARTITION vp_attach_overlap FOR VALUES FROM (50) TO (150)");
        } finally {
            exec("DROP TABLE IF EXISTS vp_attach_overlap");
        }
    }

    @Test
    void partition_list_null_when_already_covered_rejected() throws SQLException {
        exec("CREATE TABLE vp_list_null PARTITION OF vp_list_parent FOR VALUES IN (NULL)");
        try {
            // NULL already covered by vp_list_null
            assertSqlFails(
                    "CREATE TABLE vp_list_null2 PARTITION OF vp_list_parent FOR VALUES IN (NULL)");
        } finally {
            exec("DROP TABLE IF EXISTS vp_list_null");
        }
    }

    @Test
    void partition_sub_partition_outside_parent_bounds_rejected() throws SQLException {
        exec("CREATE TABLE vp_sub_parent (id INT, cat TEXT) PARTITION BY RANGE (id)");
        exec("CREATE TABLE vp_sub_p1 PARTITION OF vp_sub_parent FOR VALUES FROM (1) TO (100) PARTITION BY RANGE (id)");
        try {
            // Sub-partition bounds 50-200 exceed parent bounds 1-100
            assertSqlFails(
                    "CREATE TABLE vp_sub_child PARTITION OF vp_sub_p1 FOR VALUES FROM (50) TO (200)");
        } finally {
            exec("DROP TABLE IF EXISTS vp_sub_parent CASCADE");
        }
    }

    // ========================================================================
    // Section 2: GENERATED ALWAYS AS IDENTITY Column Enforcement
    // ========================================================================

    @Test
    void identity_always_insert_explicit_value_rejected() {
        // 428C9 = cannot_insert_generated_column or generated_always
        assertSqlState("INSERT INTO vp_ident_always (id, val) VALUES (100, 'bad')", "428C9");
    }

    @Test
    void identity_always_insert_explicit_null_rejected() {
        assertSqlFails("INSERT INTO vp_ident_always (id, val) VALUES (NULL, 'null bad')");
    }

    @Test
    void identity_always_update_rejected() throws SQLException {
        exec("INSERT INTO vp_ident_always (val) VALUES ('test')");
        assertSqlFails("UPDATE vp_ident_always SET id = 999 WHERE val = 'test'");
    }

    @Test
    void identity_always_insert_without_column_list_rejected() {
        // INSERT without column list provides value for identity column
        assertSqlFails("INSERT INTO vp_ident_always VALUES (100, 'bad')");
    }

    @Test
    void identity_always_overriding_system_value_succeeds() throws SQLException {
        // OVERRIDING SYSTEM VALUE allows explicit value
        exec("INSERT INTO vp_ident_always OVERRIDING SYSTEM VALUE VALUES (9999, 'override ok')");
        assertEquals("override ok", q("SELECT val FROM vp_ident_always WHERE id = 9999"));
    }

    @Test
    void identity_always_without_overriding_clause_rejected() {
        // No OVERRIDING SYSTEM VALUE clause => error
        assertSqlFails("INSERT INTO vp_ident_always (id, val) VALUES (5000, 'no override')");
    }

    @Test
    void identity_always_insert_omitting_column_succeeds() throws SQLException {
        // Omitting the identity column entirely should succeed
        exec("INSERT INTO vp_ident_always (val) VALUES ('omitted id ok')");
    }

    @Test
    void identity_default_insert_explicit_value_succeeds() throws SQLException {
        // GENERATED BY DEFAULT allows explicit values
        exec("INSERT INTO vp_ident_default (id, val) VALUES (100, 'explicit ok')");
        assertEquals("explicit ok", q("SELECT val FROM vp_ident_default WHERE id = 100"));
    }

    @Test
    void identity_always_via_updatable_view_explicit_rejected() throws SQLException {
        exec("CREATE VIEW vp_ident_view AS SELECT id, val FROM vp_ident_always");
        try {
            assertSqlFails("INSERT INTO vp_ident_view (id, val) VALUES (200, 'view bad')");
        } finally {
            exec("DROP VIEW IF EXISTS vp_ident_view");
        }
    }

    // ========================================================================
    // Section 3: GENERATED ALWAYS AS (expression) STORED Column Enforcement
    // ========================================================================

    @Test
    void generated_stored_insert_explicit_value_rejected() {
        // 42601 = syntax_error / cannot insert into generated column
        assertSqlState("INSERT INTO vp_generated (a, b, c) VALUES (1, 2, 5)", "428C9");
    }

    @Test
    void generated_stored_update_rejected() throws SQLException {
        exec("INSERT INTO vp_generated (a, b) VALUES (10, 20)");
        assertSqlFails("UPDATE vp_generated SET c = 99 WHERE a = 10");
    }

    @Test
    void generated_stored_insert_without_explicit_succeeds() throws SQLException {
        exec("INSERT INTO vp_generated (a, b) VALUES (3, 4)");
        assertEquals("7", q("SELECT c FROM vp_generated WHERE a = 3"));
    }

    @Test
    void generated_stored_referencing_nonexistent_column_rejected() {
        assertSqlFails(
                "CREATE TABLE vp_gen_bad (a INT, b INT GENERATED ALWAYS AS (a + nonexistent) STORED)");
    }

    @Test
    void generated_stored_referencing_another_generated_column_rejected() {
        // A generated column cannot reference another generated column
        assertSqlFails(
                "CREATE TABLE vp_gen_chain (a INT, b INT GENERATED ALWAYS AS (a * 2) STORED, " +
                        "c INT GENERATED ALWAYS AS (b + 1) STORED)");
    }

    @Test
    void generated_stored_alter_add_bad_expression_rejected() {
        assertSqlFails(
                "ALTER TABLE vp_generated ADD COLUMN d INT GENERATED ALWAYS AS (nonexistent_col * 2) STORED");
    }

    // ========================================================================
    // Section 4: View WITH CHECK OPTION Enforcement
    // ========================================================================

    @Test
    void view_check_option_insert_violating_where_rejected() {
        // Inserting status='inactive' violates WHERE status='active'
        assertSqlState(
                "INSERT INTO vp_active_view (status, val) VALUES ('inactive', 5)", "44000");
    }

    @Test
    void view_check_option_update_violating_where_rejected() {
        // Moving a row from active to inactive violates the check
        assertSqlState(
                "UPDATE vp_active_view SET status = 'inactive' WHERE val = 10", "44000");
    }

    @Test
    void view_check_option_insert_satisfying_where_succeeds() throws SQLException {
        exec("INSERT INTO vp_active_view (status, val) VALUES ('active', 50)");
    }

    @Test
    void view_check_option_delete_succeeds() throws SQLException {
        // DELETE through a view with CHECK OPTION should always succeed
        exec("DELETE FROM vp_active_view WHERE val = 50");
    }

    @Test
    void view_cascaded_check_violating_parent_rejected() {
        // vp_cascaded_view cascades to vp_active_view's WHERE status='active'
        // Inserting status != 'active' should fail even though val < 100
        assertSqlState(
                "INSERT INTO vp_cascaded_view (status, val) VALUES ('inactive', 50)", "44000");
    }

    @Test
    void view_cascaded_check_violating_own_where_rejected() {
        // val=200 violates vp_cascaded_view's own WHERE val < 100
        assertSqlState(
                "INSERT INTO vp_cascaded_view (status, val) VALUES ('active', 200)", "44000");
    }

    @Test
    void view_local_check_insert_violating_own_rejected() {
        // vp_val_view: WHERE val > 0 WITH LOCAL CHECK OPTION
        assertSqlState(
                "INSERT INTO vp_val_view (status, val) VALUES ('active', -5)", "44000");
    }

    @Test
    void view_on_join_not_auto_updatable_rejected() throws SQLException {
        exec("CREATE TABLE vp_vj1 (id INT PRIMARY KEY, val TEXT)");
        exec("CREATE TABLE vp_vj2 (id INT PRIMARY KEY, ref INT)");
        exec("CREATE VIEW vp_join_view AS SELECT vp_vj1.id, vp_vj1.val, vp_vj2.ref FROM vp_vj1 JOIN vp_vj2 ON vp_vj1.id = vp_vj2.id");
        try {
            assertSqlFails("INSERT INTO vp_join_view (id, val, ref) VALUES (1, 'x', 1)");
        } finally {
            exec("DROP VIEW IF EXISTS vp_join_view");
            exec("DROP TABLE IF EXISTS vp_vj1");
            exec("DROP TABLE IF EXISTS vp_vj2");
        }
    }

    // ========================================================================
    // Section 5: Prepared Statement Lifecycle Validation
    // ========================================================================

    @Test
    void execute_nonexistent_prepared_statement_rejected() {
        assertSqlState("EXECUTE vp_no_such_stmt", "26000");
    }

    @Test
    void deallocate_nonexistent_prepared_statement_rejected() {
        assertSqlState("DEALLOCATE vp_no_such_stmt", "26000");
    }

    @Test
    void prepare_with_malformed_sql_rejected() {
        assertSqlFails("PREPARE vp_bad_prep AS SELEC FROM nothing");
    }

    @Test
    void prepare_same_name_twice_rejected() throws SQLException {
        exec("PREPARE vp_dup_prep AS SELECT 1");
        try {
            assertSqlState("PREPARE vp_dup_prep AS SELECT 2", "42P05");
        } finally {
            exec("DEALLOCATE vp_dup_prep");
        }
    }

    @Test
    void execute_with_wrong_parameter_count_rejected() throws SQLException {
        exec("PREPARE vp_param_prep (INT) AS SELECT $1");
        try {
            // Too many parameters
            assertSqlFails("EXECUTE vp_param_prep (1, 2)");
        } finally {
            exec("DEALLOCATE vp_param_prep");
        }
    }

    @Test
    void execute_with_too_few_parameters_rejected() throws SQLException {
        exec("PREPARE vp_param2_prep (INT, INT) AS SELECT $1 + $2");
        try {
            assertSqlFails("EXECUTE vp_param2_prep (1)");
        } finally {
            exec("DEALLOCATE vp_param2_prep");
        }
    }

    @Test
    void execute_with_wrong_type_rejected() throws SQLException {
        exec("PREPARE vp_type_prep (INT) AS SELECT $1 + 1");
        try {
            assertSqlFails("EXECUTE vp_type_prep ('not_a_number')");
        } finally {
            exec("DEALLOCATE vp_type_prep");
        }
    }

    @Test
    void deallocate_all_succeeds() throws SQLException {
        exec("PREPARE vp_da1 AS SELECT 1");
        exec("PREPARE vp_da2 AS SELECT 2");
        exec("DEALLOCATE ALL");
        // Both should be gone
        assertSqlState("EXECUTE vp_da1", "26000");
    }

    @Test
    void execute_after_deallocate_rejected() throws SQLException {
        exec("PREPARE vp_dealloc_test AS SELECT 42");
        exec("DEALLOCATE vp_dealloc_test");
        assertSqlState("EXECUTE vp_dealloc_test", "26000");
    }

    // ========================================================================
    // Section 6: Function/Procedure Argument Validation
    // ========================================================================

    @Test
    void call_function_too_few_args_rejected() {
        // vp_add expects 2 args
        assertSqlState("SELECT vp_add(1)", "42883");
    }

    @Test
    void call_function_too_many_args_rejected() {
        assertSqlState("SELECT vp_add(1, 2, 3)", "42883");
    }

    @Test
    void call_function_zero_args_when_one_expected_rejected() {
        assertSqlState("SELECT vp_greet()", "42883");
    }

    @Test
    void call_nonexistent_function_rejected() {
        assertSqlState("SELECT vp_nonexistent_func(1)", "42883");
    }

    @Test
    void call_nonexistent_procedure_rejected() {
        assertSqlState("CALL vp_nonexistent_proc()", "42883");
    }

    @Test
    void call_procedure_with_wrong_arg_count_rejected() {
        // vp_do_nothing takes 0 args
        assertSqlState("CALL vp_do_nothing(1)", "42883");
    }

    @Test
    void create_function_wrong_return_type_rejected() {
        // Returns INT but body returns TEXT
        assertSqlFails(
                "CREATE FUNCTION vp_bad_ret() RETURNS INT LANGUAGE SQL AS $$ SELECT 'hello'::text $$");
    }

    @Test
    void create_plpgsql_return_no_value_for_int_rejected() {
        // RETURN; (no value) in a function that returns INT
        assertSqlFails(
                "CREATE FUNCTION vp_bad_plpgsql() RETURNS INT LANGUAGE plpgsql AS $$ BEGIN RETURN; END $$");
    }

    @Test
    void create_function_body_references_nonexistent_table_behavior() {
        // PG may accept lazily or reject at create time depending on language
        // SQL language functions are checked at creation time
        assertSqlFails(
                "CREATE FUNCTION vp_bad_table() RETURNS INT LANGUAGE SQL AS $$ SELECT id FROM vp_table_that_does_not_exist $$");
    }

    // ========================================================================
    // Section 7: Role/Permission Validation
    // ========================================================================

    @Test
    void set_role_nonexistent_rejected() {
        assertSqlFails("SET ROLE vp_nonexistent_role");
    }

    @Test
    void drop_role_nonexistent_without_if_exists_rejected() {
        assertSqlFails("DROP ROLE vp_nonexistent_role");
    }

    @Test
    void drop_role_if_exists_nonexistent_succeeds() throws SQLException {
        exec("DROP ROLE IF EXISTS vp_nonexistent_role");
    }

    @Test
    void grant_on_nonexistent_table_rejected() {
        assertSqlState("GRANT SELECT ON vp_no_such_table TO PUBLIC", "42P01");
    }

    @Test
    void grant_invalid_privilege_on_table_rejected() {
        // EXECUTE is for functions, not tables
        assertSqlFails("GRANT EXECUTE ON TABLE vp_prep TO PUBLIC");
    }

    @Test
    void grant_on_nonexistent_column_rejected() {
        assertSqlFails("GRANT SELECT (nonexistent_col) ON vp_prep TO PUBLIC");
    }

    // ========================================================================
    // Section 8: Trigger Validation
    // ========================================================================

    @Test
    void create_trigger_nonexistent_function_rejected() {
        assertSqlState(
                "CREATE TRIGGER vp_bad_trig AFTER INSERT ON vp_trig_t " +
                        "FOR EACH ROW EXECUTE FUNCTION vp_no_such_func()", "42883");
    }

    @Test
    void create_trigger_function_wrong_return_type_rejected() throws SQLException {
        exec("CREATE FUNCTION vp_int_fn() RETURNS INT LANGUAGE SQL AS $$ SELECT 1 $$");
        try {
            // Trigger function must return TRIGGER, not INT
            assertSqlFails(
                    "CREATE TRIGGER vp_bad_ret_trig AFTER INSERT ON vp_trig_t " +
                            "FOR EACH ROW EXECUTE FUNCTION vp_int_fn()");
        } finally {
            exec("DROP FUNCTION IF EXISTS vp_int_fn()");
        }
    }

    @Test
    void create_trigger_invalid_when_clause_rejected() {
        assertSqlFails(
                "CREATE TRIGGER vp_bad_when AFTER INSERT ON vp_trig_t " +
                        "FOR EACH ROW WHEN (nonexistent_col > 0) EXECUTE FUNCTION vp_trig_fn()");
    }

    @Test
    void instead_of_trigger_on_regular_table_rejected() {
        // INSTEAD OF triggers are only for views, not tables
        assertSqlFails(
                "CREATE TRIGGER vp_instead INSTEAD OF INSERT ON vp_trig_t " +
                        "FOR EACH ROW EXECUTE FUNCTION vp_trig_fn()");
    }

    @Test
    void before_trigger_on_view_rejected() throws SQLException {
        exec("CREATE VIEW vp_trig_view AS SELECT * FROM vp_trig_t");
        try {
            // BEFORE/AFTER triggers cannot be on views; use INSTEAD OF
            assertSqlFails(
                    "CREATE TRIGGER vp_before_view BEFORE INSERT ON vp_trig_view " +
                            "FOR EACH ROW EXECUTE FUNCTION vp_trig_fn()");
        } finally {
            exec("DROP VIEW IF EXISTS vp_trig_view");
        }
    }

    // ========================================================================
    // Section 9: Index Validation
    // ========================================================================

    @Test
    void create_index_nonexistent_column_rejected() {
        assertSqlFails("CREATE INDEX vp_bad_idx ON vp_idx_t (nonexistent_col)");
    }

    @Test
    void create_index_predicate_nonexistent_column_rejected() {
        assertSqlFails("CREATE INDEX vp_bad_pred_idx ON vp_idx_t (name) WHERE nonexistent_col > 0");
    }

    @Test
    void create_index_expression_type_error_rejected() {
        // Cannot index on an expression that doesn't type-check
        assertSqlFails("CREATE INDEX vp_bad_expr_idx ON vp_idx_t ((name + val))");
    }

    @Test
    void create_index_on_nonexistent_table_rejected() {
        assertSqlFails("CREATE INDEX vp_no_table_idx ON vp_no_such_table (id)");
    }

    @Test
    void create_unique_index_volatile_expression_rejected() {
        // random() is volatile; unique index on it is problematic
        assertSqlFails("CREATE UNIQUE INDEX vp_volatile_idx ON vp_idx_t ((random()))");
    }

    @Test
    void create_index_multiple_nonexistent_columns_rejected() {
        assertSqlFails("CREATE INDEX vp_multi_bad ON vp_idx_t (col_a, col_b, col_c)");
    }

    // ========================================================================
    // Section 10: ALTER TABLE Validation
    // ========================================================================

    @Test
    void alter_table_drop_column_used_by_view_rejected() {
        // Column 'name' is used by vp_alter_v
        assertSqlFails("ALTER TABLE vp_alter_t DROP COLUMN name");
    }

    @Test
    void alter_table_drop_column_used_by_view_cascade_succeeds() throws SQLException {
        exec("CREATE TABLE vp_cascade_t (id INT, col1 TEXT)");
        exec("CREATE VIEW vp_cascade_v AS SELECT col1 FROM vp_cascade_t");
        try {
            // CASCADE should drop the dependent view
            exec("ALTER TABLE vp_cascade_t DROP COLUMN col1 CASCADE");
        } finally {
            exec("DROP VIEW IF EXISTS vp_cascade_v");
            exec("DROP TABLE IF EXISTS vp_cascade_t");
        }
    }

    @Test
    void alter_table_add_column_invalid_type_rejected() {
        assertSqlFails("ALTER TABLE vp_alter_t ADD COLUMN bad_col NO_SUCH_TYPE");
    }

    @Test
    void alter_table_add_column_if_not_exists_invalid_type_still_rejected() {
        // IF NOT EXISTS should not suppress type validation errors
        assertSqlFails("ALTER TABLE vp_alter_t ADD COLUMN IF NOT EXISTS bad_col NO_SUCH_TYPE");
    }

    @Test
    void alter_table_rename_column_depended_by_index_expression() throws SQLException {
        exec("CREATE TABLE vp_idx_dep (a INT, b INT)");
        exec("CREATE INDEX vp_idx_dep_idx ON vp_idx_dep ((a + b))");
        try {
            // Renaming 'a' when an expression index uses it; PG handles this
            // but let's check behavior
            exec("ALTER TABLE vp_idx_dep RENAME COLUMN a TO aa");
        } finally {
            exec("DROP TABLE IF EXISTS vp_idx_dep CASCADE");
        }
    }

    @Test
    void alter_table_set_type_column_in_index_rejected() throws SQLException {
        // Changing type of a column used in an index requires dropping the index first (or PG rebuilds)
        // Changing from INT to TEXT is incompatible with existing index
        exec("CREATE TABLE vp_type_chg (id INT, val INT)");
        exec("CREATE INDEX vp_type_chg_idx ON vp_type_chg (val)");
        try {
            // PG may rebuild the index or error depending on type compatibility
            assertSqlFails("ALTER TABLE vp_type_chg ALTER COLUMN val SET DATA TYPE TEXT");
        } finally {
            exec("DROP TABLE IF EXISTS vp_type_chg CASCADE");
        }
    }

    @Test
    void alter_table_alter_nonexistent_column_rejected() {
        assertSqlFails("ALTER TABLE vp_alter_t ALTER COLUMN nonexistent SET NOT NULL");
    }

    @Test
    void alter_table_add_not_null_with_existing_nulls_rejected() throws SQLException {
        exec("CREATE TABLE vp_null_chk (id INT, val TEXT)");
        exec("INSERT INTO vp_null_chk VALUES (1, NULL)");
        try {
            assertSqlFails("ALTER TABLE vp_null_chk ALTER COLUMN val SET NOT NULL");
        } finally {
            exec("DROP TABLE IF EXISTS vp_null_chk");
        }
    }

    // ========================================================================
    // Section 11: Admin Command Validation
    // ========================================================================

    @Test
    void set_time_zone_invalid_rejected() {
        assertSqlFails("SET TIME ZONE 'Not/A/Timezone'");
    }

    @Test
    void set_read_only_parameter_rejected() {
        // max_connections is a postmaster parameter, cannot be SET at session level
        assertSqlFails("SET max_connections = 200");
    }

    @Test
    void comment_on_nonexistent_view_rejected() {
        assertSqlFails("COMMENT ON VIEW vp_no_such_view IS 'comment'");
    }

    @Test
    void comment_on_nonexistent_index_rejected() {
        assertSqlFails("COMMENT ON INDEX vp_no_such_index IS 'comment'");
    }

    @Test
    void comment_on_nonexistent_table_rejected() {
        assertSqlFails("COMMENT ON TABLE vp_no_such_table IS 'comment'");
    }

    @Test
    void drop_role_without_if_exists_rejected() {
        assertSqlFails("DROP ROLE vp_role_that_does_not_exist");
    }

    @Test
    void unlisten_multiple_channels_rejected() {
        // PG only accepts a single channel (or *), not comma-separated
        assertSqlFails("UNLISTEN channel1, channel2");
    }

    @Test
    void set_invalid_boolean_parameter_rejected() {
        assertSqlFails("SET enable_seqscan = 'maybe'");
    }

    @Test
    void set_invalid_integer_parameter_rejected() {
        assertSqlFails("SET work_mem = 'not_a_number'");
    }

    // ========================================================================
    // Section 12: Range Operation Validation
    // ========================================================================

    @Test
    void range_subtraction_non_contiguous_rejected() {
        // int4range(1,10) - int4range(3,7) leaves [1,3) and [7,10), not contiguous, PG errors 22000
        assertSqlState("SELECT int4range(1,10) - int4range(3,7)", "22000");
    }

    @Test
    void range_division_no_such_operator_rejected() {
        assertSqlState("SELECT int4range(1,5) / int4range(2,3)", "42883");
    }

    @Test
    void range_invalid_bounds_rejected() {
        // Lower bound greater than upper bound
        assertSqlFails("SELECT int4range(10, 1)");
    }

    @Test
    void range_intersection_type_mismatch_rejected() {
        // Cannot intersect int4range with daterange
        assertSqlFails("SELECT int4range(1,10) * daterange('2024-01-01', '2024-12-31')");
    }

    // ========================================================================
    // Section 13: Array Operation Validation
    // ========================================================================

    @Test
    void array_mixed_types_in_literal_rejected() {
        // ARRAY[1, 'x']: integer and text cannot coexist
        assertSqlFails("SELECT ARRAY[1, 'x']");
    }

    @Test
    void array_contains_type_mismatch_rejected() {
        // int[] @> text[] is a type error
        assertSqlFails("SELECT ARRAY[1,2] @> ARRAY['x']");
    }

    @Test
    void array_plus_scalar_type_error_rejected() {
        assertSqlFails("SELECT ARRAY[1,2,3] + 1");
    }

    @Test
    void array_subquery_plus_scalar_rejected() {
        assertSqlFails("SELECT ARRAY(SELECT 1) + 1");
    }

    @Test
    void array_element_assignment_type_mismatch_rejected() throws SQLException {
        exec("CREATE TABLE vp_arr_t (id INT, vals INT[])");
        exec("INSERT INTO vp_arr_t VALUES (1, ARRAY[1,2,3])");
        try {
            assertSqlFails("UPDATE vp_arr_t SET vals[1] = 'not_an_int' WHERE id = 1");
        } finally {
            exec("DROP TABLE IF EXISTS vp_arr_t");
        }
    }

    @Test
    void array_concat_incompatible_types_rejected() {
        // Cannot concat int[] with text[]
        assertSqlFails("SELECT ARRAY[1,2] || ARRAY['a','b']");
    }

    // ========================================================================
    // Section 14: Composite Type Validation
    // ========================================================================

    @Test
    void composite_type_in_case_expression_behavior() throws SQLException {
        exec("CREATE TYPE vp_pair AS (x INT, y TEXT)");
        try {
            // PG may error on CASE returning composite type
            assertSqlFails(
                    "SELECT CASE WHEN true THEN ROW(1,'a')::vp_pair ELSE ROW(2,'b')::vp_pair END");
        } finally {
            exec("DROP TYPE IF EXISTS vp_pair CASCADE");
        }
    }

    @Test
    void composite_star_expansion_from_table_succeeds() throws SQLException {
        exec("CREATE TYPE vp_comp AS (a INT, b TEXT)");
        exec("CREATE TABLE vp_comp_t (id INT, data vp_comp)");
        exec("INSERT INTO vp_comp_t VALUES (1, ROW(10, 'hello')::vp_comp)");
        try {
            // (data).* expansion should work
            String result = q("SELECT (data).a FROM vp_comp_t WHERE id = 1");
            assertEquals("10", result);
        } finally {
            exec("DROP TABLE IF EXISTS vp_comp_t");
            exec("DROP TYPE IF EXISTS vp_comp CASCADE");
        }
    }

    @Test
    void row_cast_to_nonexistent_type_rejected() {
        assertSqlFails("SELECT ROW(1, 'a')::vp_type_that_does_not_exist");
    }

    // ========================================================================
    // Section 15: Sequence Validation
    // ========================================================================

    @Test
    void setval_nonexistent_sequence_rejected() {
        assertSqlFails("SELECT setval('vp_no_such_seq', 100)");
    }

    @Test
    void nextval_nonexistent_sequence_rejected() {
        assertSqlFails("SELECT nextval('vp_no_such_seq')");
    }

    @Test
    void currval_without_prior_nextval_rejected() {
        // currval requires nextval to have been called first in the session
        assertSqlFails("SELECT currval('vp_seq')");
    }

    @Test
    void sequence_setval_exceeds_maxvalue_rejected() throws SQLException {
        exec("CREATE SEQUENCE vp_bounded_seq MAXVALUE 100");
        try {
            // setval beyond maxvalue; PG may accept setval but nextval will fail
            exec("SELECT setval('vp_bounded_seq', 100)");
            assertSqlFails("SELECT nextval('vp_bounded_seq')");
        } finally {
            exec("DROP SEQUENCE IF EXISTS vp_bounded_seq");
        }
    }

    @Test
    void create_sequence_invalid_increment_rejected() {
        assertSqlFails("CREATE SEQUENCE vp_bad_incr INCREMENT 0");
    }

    @Test
    void create_sequence_min_greater_than_max_rejected() {
        assertSqlFails("CREATE SEQUENCE vp_bad_bounds MINVALUE 100 MAXVALUE 10");
    }

    @Test
    void alter_sequence_nonexistent_rejected() {
        assertSqlFails("ALTER SEQUENCE vp_no_such_seq RESTART WITH 1");
    }

    // ========================================================================
    // Section 16: Schema Evolution Edge Cases
    // ========================================================================

    @Test
    void add_not_null_column_without_default_on_nonempty_table_rejected() {
        // Table has rows but new NOT NULL column has no DEFAULT
        assertSqlFails("ALTER TABLE vp_evolve ADD COLUMN new_col INT NOT NULL");
    }

    @Test
    void add_column_with_default_violating_check_rejected() {
        // DEFAULT -5 violates CHECK (val > 0), but this is a different column
        // The check is on val, not on the new column, so this should succeed
        // unless the check is on the new column itself
        assertSqlFails(
                "ALTER TABLE vp_evolve ADD COLUMN restricted INT CHECK (restricted > 0) DEFAULT -5");
    }

    @Test
    void insert_violating_newly_added_check_constraint_rejected() throws SQLException {
        exec("CREATE TABLE vp_new_check (id INT, val INT)");
        exec("INSERT INTO vp_new_check VALUES (1, 10)");
        exec("ALTER TABLE vp_new_check ADD CONSTRAINT vp_chk CHECK (val >= 0)");
        try {
            assertSqlFails("INSERT INTO vp_new_check VALUES (2, -1)");
        } finally {
            exec("DROP TABLE IF EXISTS vp_new_check");
        }
    }

    @Test
    void add_check_constraint_conflicting_with_existing_data_rejected() throws SQLException {
        exec("CREATE TABLE vp_conflict (id INT, val INT)");
        exec("INSERT INTO vp_conflict VALUES (1, -5)");
        try {
            // Existing row has val=-5, which violates the new CHECK
            assertSqlFails("ALTER TABLE vp_conflict ADD CONSTRAINT vp_chk2 CHECK (val > 0)");
        } finally {
            exec("DROP TABLE IF EXISTS vp_conflict");
        }
    }

    @Test
    void alter_column_set_not_null_with_null_data_rejected() throws SQLException {
        exec("CREATE TABLE vp_null_data (id INT, val TEXT)");
        exec("INSERT INTO vp_null_data VALUES (1, NULL)");
        try {
            assertSqlFails("ALTER TABLE vp_null_data ALTER COLUMN val SET NOT NULL");
        } finally {
            exec("DROP TABLE IF EXISTS vp_null_data");
        }
    }

    // ========================================================================
    // Additional: Type Cast Validation
    // ========================================================================

    @Test
    void invalid_type_cast_text_to_int_rejected() {
        assertSqlFails("SELECT 'not_a_number'::INT");
    }

    @Test
    void invalid_type_cast_text_to_date_rejected() {
        assertSqlFails("SELECT 'not_a_date'::DATE");
    }

    @Test
    void invalid_type_cast_text_to_timestamp_rejected() {
        assertSqlFails("SELECT 'garbage'::TIMESTAMP");
    }

    @Test
    void invalid_type_cast_text_to_boolean_rejected() {
        assertSqlFails("SELECT 'maybe'::BOOLEAN");
    }

    @Test
    void cast_to_nonexistent_type_rejected() {
        assertSqlFails("SELECT 1::vp_nonexistent_type");
    }

    // ========================================================================
    // Additional: INSERT/UPDATE Constraint Violations
    // ========================================================================

    @Test
    void insert_null_into_not_null_column_rejected() throws SQLException {
        exec("CREATE TABLE vp_nn (id INT NOT NULL, val TEXT)");
        try {
            assertSqlFails("INSERT INTO vp_nn VALUES (NULL, 'bad')");
        } finally {
            exec("DROP TABLE IF EXISTS vp_nn");
        }
    }

    @Test
    void insert_duplicate_primary_key_rejected() throws SQLException {
        exec("CREATE TABLE vp_pk (id INT PRIMARY KEY, val TEXT)");
        exec("INSERT INTO vp_pk VALUES (1, 'first')");
        try {
            assertSqlFails("INSERT INTO vp_pk VALUES (1, 'duplicate')");
        } finally {
            exec("DROP TABLE IF EXISTS vp_pk");
        }
    }

    @Test
    void insert_violating_unique_constraint_rejected() throws SQLException {
        exec("CREATE TABLE vp_uq (id INT, email TEXT UNIQUE)");
        exec("INSERT INTO vp_uq VALUES (1, 'a@b.com')");
        try {
            assertSqlFails("INSERT INTO vp_uq VALUES (2, 'a@b.com')");
        } finally {
            exec("DROP TABLE IF EXISTS vp_uq");
        }
    }

    @Test
    void insert_violating_check_constraint_rejected() throws SQLException {
        exec("CREATE TABLE vp_chk (id INT, val INT CHECK (val BETWEEN 1 AND 100))");
        try {
            assertSqlFails("INSERT INTO vp_chk VALUES (1, 200)");
        } finally {
            exec("DROP TABLE IF EXISTS vp_chk");
        }
    }

    @Test
    void insert_violating_foreign_key_rejected() throws SQLException {
        exec("CREATE TABLE vp_fk_parent (id INT PRIMARY KEY)");
        exec("CREATE TABLE vp_fk_child (id INT, parent_id INT REFERENCES vp_fk_parent(id))");
        try {
            assertSqlFails("INSERT INTO vp_fk_child VALUES (1, 999)");
        } finally {
            exec("DROP TABLE IF EXISTS vp_fk_child");
            exec("DROP TABLE IF EXISTS vp_fk_parent");
        }
    }

    @Test
    void delete_violating_foreign_key_restrict_rejected() throws SQLException {
        exec("CREATE TABLE vp_fk_p2 (id INT PRIMARY KEY)");
        exec("CREATE TABLE vp_fk_c2 (id INT, pid INT REFERENCES vp_fk_p2(id) ON DELETE RESTRICT)");
        exec("INSERT INTO vp_fk_p2 VALUES (1)");
        exec("INSERT INTO vp_fk_c2 VALUES (1, 1)");
        try {
            assertSqlFails("DELETE FROM vp_fk_p2 WHERE id = 1");
        } finally {
            exec("DROP TABLE IF EXISTS vp_fk_c2");
            exec("DROP TABLE IF EXISTS vp_fk_p2");
        }
    }

    // ========================================================================
    // Additional: DDL on nonexistent objects
    // ========================================================================

    @Test
    void drop_table_nonexistent_without_if_exists_rejected() {
        assertSqlFails("DROP TABLE vp_table_that_does_not_exist");
    }

    @Test
    void drop_table_if_exists_nonexistent_succeeds() throws SQLException {
        exec("DROP TABLE IF EXISTS vp_table_that_does_not_exist");
    }

    @Test
    void drop_view_nonexistent_without_if_exists_rejected() {
        assertSqlFails("DROP VIEW vp_view_that_does_not_exist");
    }

    @Test
    void drop_sequence_nonexistent_without_if_exists_rejected() {
        assertSqlFails("DROP SEQUENCE vp_seq_that_does_not_exist");
    }

    @Test
    void drop_index_nonexistent_without_if_exists_rejected() {
        assertSqlFails("DROP INDEX vp_index_that_does_not_exist");
    }

    @Test
    void drop_function_nonexistent_without_if_exists_rejected() {
        assertSqlFails("DROP FUNCTION vp_func_that_does_not_exist()");
    }

    @Test
    void alter_table_nonexistent_rejected() {
        assertSqlFails("ALTER TABLE vp_table_that_does_not_exist ADD COLUMN x INT");
    }

    @Test
    void create_table_duplicate_column_name_rejected() {
        assertSqlFails("CREATE TABLE vp_dup_col (id INT, id INT)");
    }

    @Test
    void create_table_with_nonexistent_type_column_rejected() {
        assertSqlFails("CREATE TABLE vp_bad_type (id INT, data NO_SUCH_TYPE)");
    }

    // ========================================================================
    // Additional: Expression Validation
    // ========================================================================

    @Test
    void division_by_zero_rejected() {
        assertSqlFails("SELECT 1 / 0");
    }

    @Test
    void modulo_by_zero_rejected() {
        assertSqlFails("SELECT 1 % 0");
    }

    @Test
    void negative_array_subscript_behavior() throws SQLException {
        // PG returns NULL for out-of-range subscripts, not an error
        String result = q("SELECT (ARRAY[1,2,3])[-1]");
        assertNull(result);
    }

    @Test
    void select_from_nonexistent_table_rejected() {
        assertSqlState("SELECT * FROM vp_table_not_here", "42P01");
    }

    @Test
    void column_reference_ambiguous_rejected() throws SQLException {
        exec("CREATE TABLE vp_amb1 (id INT, val TEXT)");
        exec("CREATE TABLE vp_amb2 (id INT, name TEXT)");
        try {
            // 'id' is ambiguous in a cross join
            assertSqlFails("SELECT id FROM vp_amb1, vp_amb2");
        } finally {
            exec("DROP TABLE IF EXISTS vp_amb1");
            exec("DROP TABLE IF EXISTS vp_amb2");
        }
    }

    @Test
    void subquery_returning_multiple_rows_in_scalar_context_rejected() throws SQLException {
        exec("CREATE TABLE vp_multi (id INT)");
        exec("INSERT INTO vp_multi VALUES (1), (2), (3)");
        try {
            assertSqlFails("SELECT (SELECT id FROM vp_multi)");
        } finally {
            exec("DROP TABLE IF EXISTS vp_multi");
        }
    }
}
